### ISSUE TITLE
Integration test is flaky for status updates

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#101]
see https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/90/pull-kueue-test-integration-main/1501214768197799936

**Comment by alculquicondor** [comment]
I have been thinking about a possible flake that would affect all our status updates.

1. We get an event for the updated QueuedWorkload.
2. The queue controller picks it up, updates the Queue status.
3. The queuedcontroller picks it up, updates the queue manager.

Result: the Queue status is outdated and nothing will bring it back :(

The same could happen for ClusterQueue status and the cache.

If that's the case, we should look into a way for the queuedworkload controller to `Add` events to the Queue/ClusterQueue reconcilers' workerqueue.

**Comment by denkensk** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/104/pull-kueue-test-integration-main/1501588334315573248

**Comment by ArangoGutierrez** [comment]
Spending today afternoon on this topic
might un-assign if not successful 
/assign

**Comment by ArangoGutierrez** [comment]
Managed to reproduce locally after several runs 
```bash
    STEP: Creating workloads 03/09/22 16:48:04.446
  << End Captured GinkgoWriter Output

  Timed out after 10.001s.
  Mismatch (-want,+got):
    v1alpha1.QueueStatus{
  -     PendingWorkloads: 3,
  +     PendingWorkloads: 2,
    }
  
  In [It] at: /home/eduardo/sdk/github/kubernetes-sigs/kueue/test/integration/controller/core/queue_controller_test.go:84
------------------------------
•

Ran 2 of 2 Specs in 17.084 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestAPIs (17.08s)
```

Seems to alight with Aldo idea of it being around the Queue controller

**Comment by ArangoGutierrez** [comment]
I think #105 can help fix this, one of the issues is that we are not updating the queuedWorkload.Status enough, I could test by changing 
https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/core/queue_controller.go#L136-L143

to

```go
func (h *queuedWorkloadHandler) Update(e event.UpdateEvent, q workqueue.RateLimitingInterface) {
	oldQW := e.ObjectOld.(*kueue.QueuedWorkload)
	newQW := e.ObjectOld.(*kueue.QueuedWorkload)
	if workloadStatus(oldQW) != workloadStatus(newQW) {
		q.Add(requestForQueueStatus(newQW))
	}
	if newQW.Spec.QueueName != oldQW.Spec.QueueName {
		q.Add(requestForQueueStatus(oldQW))
	}
}
```

Test now fails every time, meaning the old and new status are almost always the same

**Comment by alculquicondor** [comment]
Did you observe any failures for the ClusterQueue controller?

>  one of the issues is that we are not updating the queuedWorkload.Status enough

I don't think we should solve this by "being more noisy". If there is a race condition, we should solve it.

Were you able to confirm if my theory in https://github.com/kubernetes-sigs/kueue/issues/101#issuecomment-1062084107 is the actual cause?

**Comment by ArangoGutierrez** [comment]
After a long `while true` loop, the only test failing is always `queue_controller_test.go` , so it is probably around that place , always around `PendingWorkloads` not being what expected 

It feels like a race condition when calling 
https://github.com/kubernetes-sigs/kueue/blob/b40d12cb980faa3f6d3b308f93502a6acba3b8b9/pkg/queue/manager.go#L108-L115

**Comment by alculquicondor** [comment]
If my theory is correct, we should also observe failures for cluster queues.

**But...**

The reason we don't might be because of the "assume" mechanism: Before we update the QW in the API, we update it in the cache, so the cache is up to date.

Maybe it could still fail for the case when a workload finishes (we do a CQ reconcile, but the cache update happens later).

**Comment by alculquicondor** [comment]
I this you should be able to verify my theory if you raise the log level to 2 or 3 (not sure how to do that on tests) to see the order in which we process events. If it's not easy to setup a flag, feel free to hardcode the level somewhere in test/integration/framework.

**Comment by ArangoGutierrez** [comment]
> I think you should be able to verify my theory if you raise the log level to 2 or 3 (not sure how to do that on tests) to see the order in which we process events. If it's not easy to setup a flag, feel free to hardcode the level somewhere in test/integration/framework.

`--args --ginkgo.vv -test.v`

**Comment by ahg-g** [comment]
It seems that the different between Queue and ClusterQueue is that in ClusterQueue we always add an event when an admitted QW is updated https://github.com/kubernetes-sigs/kueue/blob/b40d12cb980faa3f6d3b308f93502a6acba3b8b9/pkg/controller/core/clusterqueue_controller.go#L147

While in Queue we do that only if the queue name changed
https://github.com/kubernetes-sigs/kueue/blob/b40d12cb980faa3f6d3b308f93502a6acba3b8b9/pkg/controller/core/queue_controller.go#L140

**Comment by ahg-g** [comment]
> I don't think we should solve this by "being more noisy". If there is a race condition, we should solve it.

@alculquicondor shouldn't we update the Queue status when a Workload finishes? currently this is not guaranteed, right?

**Comment by alculquicondor** [comment]
> While in Queue we do that only if the queue name changed

But if the queue name doesn't change, that's covered too:

https://github.com/kubernetes-sigs/kueue/blob/b40d12cb980faa3f6d3b308f93502a6acba3b8b9/pkg/controller/core/queue_controller.go#L139-L142

> shouldn't we update the Queue status when a Workload finishes? currently this is not guaranteed, right?

We do. But I think the queue manager might have old information, because the code to update it is in the queuedworkload_controller.

**Comment by ahg-g** [comment]
ah, I missed the line above!

**Comment by ArangoGutierrez** [comment]
with verbosity activated

this can provide clues to this
```bash
    1.6469298507993455e+09      ERROR   controller.queue        Reconciler error        {"reconciler group": "kueue.x-k8s.io", "reconciler kind": "Queue", "name": "queue", "namespace": "core-queue-sx92t", "error": "Operation cannot be ful
filled on queues.kueue.x-k8s.io \"queue\": the object has been modified; please apply your changes to the latest version and try again"}
```
This flake is indeed a race condition around queue controller

**Comment by alculquicondor** [comment]
Those kind of errors are expected. We always load the object from the informer cache and then update. It's possible that we are trying to update a queue that just got updated and the informer cache didn't have the time to update. But that's fine, because we will try to reconcile again.

**Comment by ArangoGutierrez** [comment]
Agree, after a lot of back and forth , the race condition is on the `queuedworkload_controller` 
https://github.com/kubernetes-sigs/kueue/blob/14cc822119b2b7eb9bc8480e8d2088da263830ca/pkg/controller/core/queuedworkload_controller.go#L65L170

During the integration tests, the race condition is seen after creating, updating or deleting (finishing) a workload, the queue.status or clusterqueue.status has still 1 or 2 pendingWorkloads.

**Comment by ahg-g** [comment]
I actually wonder if we should simply have a timer that wakes up every few seconds to check if there was an update and reflect it, this should be simpler, reliable and fairly acceptable UX.

**Comment by ArangoGutierrez** [comment]
/retitle Integration test is flaky for status updates

**Comment by ahg-g** [comment]
> workqueue.AddAfter(key, batchPeriod)

How would that batch things? doesn't it just shift it?

This actually might a good short term hack to fix the flake, just delay the status update a few seconds :)

**Comment by ahg-g** [comment]
> How would that batch things? doesn't it just shift processing the events?

hmm, actually this would help because we don't need the other events to be processed to reflect on the status.

**Comment by alculquicondor** [comment]
so if at 00:00 you do `AddAfter(key, 1h)`

Any other calls between 00:00 and 01:00 are basically ignored.

**Comment by ArangoGutierrez** [comment]
Yesterday I played around changing the controller watch from `kind` to `informer` but is still the same race.

**Comment by ArangoGutierrez** [comment]
testing it on PROW infra.

**Comment by ArangoGutierrez** [comment]
Here you go -> https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/120/pull-kueue-test-integration-main/1503761433379213312

**Comment by ArangoGutierrez** [comment]
#120 got 2/3 runs

**Comment by ArangoGutierrez** [comment]
Locally using `while true; do KUBEBUILDER_ASSETS="/home/eduardo/.local/share/kubebuilder-envtest/k8s/1.23.3-linux-amd64" go test -count=1 ./test/integration/...; done` 
Test fails 1/8 times

**Comment by alculquicondor** [comment]
/reopen

this is mitigated, not fixed.
