### ISSUE TITLE
Set pending condition on QueuedWorkload with message

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#102]
A queued workload can be pending for several reasons:

- The Queue doesn't exist
- The ClusterQueue doesn't exist
- The QW's namespace is not allowed by the ClusterQueue
- The workload was attempted for scheduling but it didn't fit.

We need to find a way to set this information.

Probably the first 2 can happen in the queuedworkload_controller, after every update.
The other 2 should probably during scheduling.

/kind feature

**Comment by ArangoGutierrez** [comment]
I think this can help with #88 as well

**Comment by ahg-g** [comment]
is this still in progress?

**Comment by ArangoGutierrez** [comment]
yes, will take back on this. I have been busy and #101 distracted me for a bit

**Comment by ahg-g** [comment]
sg, thanks, I will remove the help tag then.

/remove-help

**Comment by ArangoGutierrez** [comment]
Question:
Why  https://github.com/kubernetes-sigs/kueue/blob/main/api/v1alpha1/queuedworkload_types.go#L96 is a map and not an array?

**Comment by ArangoGutierrez** [comment]
```go
// QueuedWorkloadStatus defines the observed state of QueuedWorkload
type QueuedWorkloadStatus struct {
	// conditions hold the latest available observations of the QueuedWorkload
	// current state.
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []QueuedWorkloadCondition `json:"conditions,omitempty"`
}
```
Why is a map, if we want to keep the conditions as an array in the order they occur

**Comment by ArangoGutierrez** [comment]
And we have been treating that var like an array in places where the conditions are set.

**Comment by alculquicondor** [comment]
The order shouldn't matter. Each condition has a timestamp.

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/kueue/pull/150 should be enough to close this one
/close
