### ISSUE TITLE
Flaky test: Kueue when Creating a Job With Queueing [It] Should unsuspend a job and set nodeSelectors

### ISSUE THREAD

**Issue by BinL233** [kubernetes-sigs/kueue#1021]
**What happened**:
`Kueue when Creating a Job With Queueing [It] Should unsuspend a job and set nodeSelectors` is flaky.

e2e test failed link: 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1018/pull-kueue-test-e2e-main-1-26/1684507556703113216

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by BinL233** [comment]
`apimeta.IsStatusConditionTrue` in line 142 of kueue/test/e2e/e2e_test.go, always takes more than 15 seconds to run. I think this is because the pod needs time to pull image and run sleep. There is a risk that the job will trig `util.Timeout`.

**Comment by BinL233** [comment]
Can we just extend the time limit like `util.Timeout * 1.5`?

**Comment by alculquicondor** [comment]
That sounds plausible.
We can introduce another constant `LongTimeout` and put a comment that is meant for E2E tests when waiting for complex operations such as running pods to completion.

**Comment by alculquicondor** [comment]
Not sure if it's reproducible in 1.25

Let's reopen if we see it again.

/close
