### ISSUE TITLE
ClusterQueue updates/deletions and running workloads

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#103]
With regards to CQ deletions, perhaps we can inject finalizers to block the delete until all running workloads finish, at the same time stop admitting new workloads.

What about CQ updates? One simple solution is to make everything immutable, and so updating a CQ is only possible by recreating it, hence we reduce update to a delete which we already handled above. We can relax this a little by allowing the following updates:
1) an increase to existing quota 
2) adding new resources and/or flavors
3) setting a cohort only if it was not set before

all of those updates don't impact running workloads and can be done without checking for current usage levels.

/kind feature

**Comment by alculquicondor** [comment]
My hesitation is that it would make a simple use case: increase/decrease quotas much harder to do.

But we could start with adding a finalizer to restrict deletion and stop admitting workloads into a CQ if it has a deletionTimestamp

**Comment by ahg-g** [comment]
what do we do with downsizing then in the meantime?

**Comment by alculquicondor** [comment]
You just wait for some workloads to finish and the remaining ones to fit in the smaller quota.

**Comment by ahg-g** [comment]
ok, and I am guessing we don't need to do anything to support this path, it is already what we do; we probably still need to make sure that there are no assumptions on the cohort quota being greater than or equal to the sum of running workloads requests.

**Comment by alculquicondor** [comment]
We only look at the (sum of) quotas when scheduling, so the behavior is the same for cohorts.

**Comment by ahg-g** [comment]
Done.
