### ISSUE TITLE
Update workload when job changes before admission

### ISSUE THREAD

**Issue by GhangZh** [kubernetes-sigs/kueue#1038]
The current workload design is that if the configuration of workload and job is found to be inconsistent, the current workload will be deleted and re-created.

If there are some special scenarios where I need to change the job configuration, it will cause my job to be re-queued, which is not very reasonable from a product perspective, the expectation is that the workload will not be re-created but will change as the job changes.

**Comment by GhangZh** [comment]
> 
Yes, I'll modify it when the job is queued or suspended

**Comment by alculquicondor** [comment]
That sounds feasible.

@trasc, could you investigate if it's possible?

**Comment by trasc** [comment]
Yes, it should be doable.
/assign
