### ISSUE TITLE
Revisit `pkg/util/maps` and `pkg/util/slices` after switching to go 1.21

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#1047]
**What would you like to be cleaned**:
[Go 1.21](https://tip.golang.org/doc/go1.21) some cages that could simplify our `slices` and `maps` like:
  
New slices package
The new [slices](https://tip.golang.org/pkg/slices) package provides many common operations on slices, using generic functions that work with slices of any element type.

New maps package
The new [maps](https://tip.golang.org/pkg/maps/) package provides several common operations on maps, using generic functions that work with maps of any key or element type.

[min and max](https://tip.golang.org/ref/spec#Min_and_max)

**Why is this needed**:

**Comment by alculquicondor** [comment]
Sounds exciting!

Although I would prefer to wait for 1.21.1 to be released before we upgrade. Ideally k/k also moves.

**Comment by alculquicondor** [comment]
I asked some sig-architecture folks, and there doesn't seem to be a date for upgrading k/k to golang 1.21

Since 1.21.1 was already released, I'm ok upgrading kueue now.

**Comment by tenzen-y** [comment]
/reopen

I think `slices` still remain.

**Comment by PBundyra** [comment]
> /reopen
> 
> I think `slices` still remain.

I've gone through ```slices``` and didn't find anything that can be useful for our current use cases

**Comment by tenzen-y** [comment]
> > /reopen
> > I think `slices` still remain.
> 
> I've gone through `slices` and didn't find anything that can be useful for our current use cases

I see. Thank you!
/close
