### ISSUE TITLE
Use k8s.io/utils/ptr package

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1051]
**What would you like to be cleaned**:

This package uses generics to wrap values into pointers.

**Why is this needed**:

Eliminates the need for our own pkg/utils/pointer package

**Comment by kannon92** [comment]
So your package does utilize this and it is mostly defining aliases to K8s pointer package.

**Comment by tenzen-y** [comment]
We can remove `pkg/util/pointer`, then we use `ptr.To(resource.Quantity)`each location.

**Comment by alculquicondor** [comment]
Yes, `ptr` is a new package, different from `pointer`

**Comment by kannon92** [comment]
TIL I learned that pointer is deprecated.  And there is `ptr`.  That will be a lot of work to change in k/k.
