### ISSUE TITLE
Change a way to check if the GVK is registered

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1054]
**What would you like to be cleaned**:

Once https://github.com/kubernetes-sigs/controller-runtime/pull/2425 commit is released, we need to use only `!meta.IsNoMatchError(err)` to check if the GVK is registered.

https://github.com/kubernetes-sigs/kueue/blob/b95d0fd979ae210e1dd6834523f3bb407db86bf8/main.go#L223-L233

**Why is this needed**:

The behavior of `mgr.GetRESTMapper().RESTMapping()` will be changed once https://github.com/kubernetes-sigs/controller-runtime/pull/2425 is released.

Follow-ups: #1046

**Comment by mimowo** [comment]
I think this is unblocked after https://github.com/kubernetes-sigs/controller-runtime/pull/2472 is merged.

**Comment by tenzen-y** [comment]
> I think this is unblocked after [kubernetes-sigs/controller-runtime#2472](https://github.com/kubernetes-sigs/controller-runtime/pull/2472) is merged.

Oh, right. Thank you for the notifications!
/assign

**Comment by tenzen-y** [comment]
I will bump K8s dependencies to address this issue.
