### ISSUE TITLE
[website] Add download icon next to file names

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1065]
**What would you like to be added**:

We have a shortcode that writes the contents of a static file into the website, along with a link for downloading it.
There should be:
- an icon before the file name.
- a box around the name

https://kubernetes.io/docs/concepts/workloads/controllers/job/#running-an-example-job

Perhaps we can adapt the shortcode that kubernetes uses https://github.com/kubernetes/website/blob/3c9c3afd2abd086f79b7d220884f39747d06496c/layouts/shortcodes/code.html

**Why is this needed**:

An icon would make it clear that it's a link for downloading the file

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by FZhg** [comment]
- [x]  Design doc
I used the solid document download icon in free font-awesome free icon set  and light-bordered button in Bootstrap. Both Bootstrap and font-awesome free icon set are supported by docsy by default.
![image](https://github.com/kubernetes-sigs/kueue/assets/22489650/8b937067-968d-4ef7-964a-d6e5ddad06ec)

- [x] API change
To embed an static code file into the a content page of the website, just add the the following code inside the page html file.
```
{{% include filename="<your-filename>" codelang="<your-code-language>"}}
```
You need to place the code file as the following path `/site/example/your-code-language/your-filename`.
For example, if you want to include the file with the path `/site/example/java/sample.java` , you need to add the following code to your page html.

```
{{% include filename="sample.java" codelang="java"}}
```
- [x] Docs update
Only the `run_python_jobs.md` inside the `/site/content/tasks` directory used the `include` shortcode. I updated all 5 usages in this page: 
    - [x] install-kueue-queues.py
    - [x] sample-job.py
    - [x] sample-queue-control.py
    - [x] sample-flux-operator-job.py
    - [x] sample-mpijob.py
