### ISSUE TITLE
A sample for out-of-tree integrations and a directory for experimental integrations

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1087]
**What would you like to be added**:

A directory structure that allow us to host code for integrations with Kueue that are not part of the main binary.

**Why is this needed**:

This would allow:

- a sample for how to write out-of-tree integrations
- experimental integrations: integrations without long term support or that might otherwise have some caveats

A useful sample could be pod support using taints and tolerations. This is not a good candidate for long term support, as we already have a better mechanism using scheduling gates. But otherwise, the sample could be useful for users who can't upgrade to 1.27 yet.

**Comment by alculquicondor** [comment]
cc @tenzen-y @kerthcet 
Any concerns or ideas for interesting samples?

**Comment by alculquicondor** [comment]
That's great feedback. I included it in the README in #1088

**Comment by kerthcet** [comment]
Make sense to me to reduce the maintenance cost, also the stability. A general question is how to determine a job is in-tree or out-of-tree then, based on the popularity? 

And I think we may have to provide some test libraries for integration/e2e tests with kueue.

**Comment by alculquicondor** [comment]
> A general question is how to determine a job is in-tree or out-of-tree then, based on the popularity?

That could be one criteria. The other could be how long the contributor that is proposing it has been in the project. There should be some idea that they will help maintain the integration long term, for it to be in-tree.

> And I think we may have to provide some test libraries for integration/e2e tests with kueue.

I think they might be able to reuse the existing packages. But overall, we could allow code in the experimental directory to merge with much less testing. Maybe we can have a README for each folder similar to https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/capacityscheduling/README.md

**Comment by alculquicondor** [comment]
We can consider this as completed by #1092.

/close
