### ISSUE TITLE
Add `QueueVisibility` to featureGate

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1102]
**What would you like to be cleaned**:
Adding `QueueVisibility` to featureGate to manage if Kueue enables the feature for the KEP 168.

**Why is this needed**:
To appropriately manage the new feature.

**Comment by mimowo** [comment]
Let's make the feature disabled by default as suggested by @tenzen-y here https://github.com/kubernetes-sigs/kueue/pull/1069#issuecomment-1711498601
