### ISSUE TITLE
Pre-pull docker images used for testing

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1108]
This is needed to prevent timeouts in e2e tests which now need to fetch images

Example flaky test, probably caused by the additional time on fetching the image: https://github.com/kubernetes-sigs/kueue/issues/1021. Another already closed issue: https://github.com/kubernetes-sigs/kueue/pull/1025.

**Comment by alculquicondor** [comment]
+1
We can use `kind load`

**Comment by tenzen-y** [comment]
fixed by: https://github.com/kubernetes-sigs/kueue/pull/1126
/close
