### ISSUE TITLE
Commonize KubeflowJob Tests

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1119]
**What would you like to be cleaned**:
We should commonize integration tests for KubeflowJobs and move test cases depending on kubeflow frameworks (TFJob, PyTorchJob...) to unit tests.

Follow-up: https://github.com/kubernetes-sigs/kueue/pull/1114#discussion_r1324240711

**Why is this needed**:
The KubeflowJobs's reconciler is commonized in https://github.com/kubernetes-sigs/kueue/blob/e5692d83fd841a57e9b41c50b48ba6776c7c134e/pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go, and some integration test cases are overkill.

**Comment by alculquicondor** [comment]
/unassign @yaroslava-serdiuk
/assign @stuton 
Anton, could you follow up with the rest of the Kubeflow integration tests, in a similar manner to #1191 ?

**Comment by stuton** [comment]
For sure, I will have a look
