### ISSUE TITLE
Switch to k8s.io/code-generator/kube_codegen.sh

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1134]
**What would you like to be cleaned**:
We should switch the tool to generate client-go libraries to [`k8s.io/code-generator/kube_codegen.sh`](https://github.com/kubernetes/code-generator/blob/e4611069dfb4b0c04c7751afae1b9fef64828964/kube_codegen.sh).

**Why is this needed**:
The `k8s.io/code-generator/generate-groups.sh` was deprecated.

https://github.com/kubernetes/code-generator/blob/e4611069dfb4b0c04c7751afae1b9fef64828964/generate-groups.sh#L52-L54

**Comment by tenzen-y** [comment]
We can work on this issue after https://github.com/kubernetes-sigs/kueue/pull/1133 is merged as `k8s.io/code-generator/kube_codegen.sh` was introduced since K8s v1.28.

**Comment by tenzen-y** [comment]
@PBundyra FYI: #1133 is merged into the main.

**Comment by trasc** [comment]
We should check if now we have better support for out of `GOPATH` generation and potentiality drop the workaround: 
https://github.com/kubernetes-sigs/kueue/blob/f9273bef71e136c0eed659ae19fce178512a6f6a/hack/update-codegen.sh#L35-L46

**Comment by tenzen-y** [comment]
> We should check if now we have better support for out of `GOPATH` generation and potentiality drop the workaround:
> 
> https://github.com/kubernetes-sigs/kueue/blob/f9273bef71e136c0eed659ae19fce178512a6f6a/hack/update-codegen.sh#L35-L46

That's right. I thought we may be able to remove this workaround using `--output-base`:

https://github.com/kubernetes/code-generator/blob/e4611069dfb4b0c04c7751afae1b9fef64828964/kube_codegen.sh#L393-L395
