### ISSUE TITLE
Support Cluster-Autoscaler's ProvisioningRequest via two-stage admission

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#1136]
**What would you like to be added**:

Use two-stage admission to support [Cluster-Autoscaler's ProvisioningRequest](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md)

**Why is this needed**:

The ProvisioningRequest API allows to request new nodes without creating Pods. Kueue can use it to provide high guarantees that the admitted workloads will fit in the cluster.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@trasc Could you update the issue description? I don't have any context as to why this feature is necessary.

**Comment by alculquicondor** [comment]
Sorry about that @tenzen-y. Updated the description.

There is a KEP coming. We are thinking of using the cmd/experimental folder to avoid tying this to the release of 0.5

**Comment by tenzen-y** [comment]
> Sorry about that @tenzen-y. Updated the description.

@alculquicondor Alright. Thank you for the updates :)

> There is a KEP coming. We are thinking of using the cmd/experimental folder to avoid tying this to the release of 0.5

It makes sense. IIUC, ProvisioningRequest is not yet released.

**Comment by trasc** [comment]
/reopen
To continue tracking the implementation #1154
