### ISSUE TITLE
Skip checking if the cluster queue pending workloads need a change based on the snapshot revision

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1138]
The idea is to extend the snapshot used for visibility with its revision (consecutive integers). The clusterQueuePendingWorkloads in the status would also keep the version of the snapshot used.  

Then, we can short-circuit the check of the update of the status, based on comparing revisions. Note that, previously the deep equal check was performed when the lastChangeTime was greater than updateStatusInterval (see https://github.com/kubernetes-sigs/kueue/blob/ee5b6ba29a1bbed1574262e362182573c5f6fa5e/pkg/controller/core/clusterqueue_controller.go#L603), while after https://github.com/kubernetes-sigs/kueue/pull/1135 eliminates this optimization. With the revisions we can do better in both cases.

**Comment by mimowo** [comment]
FYI @tenzen-y @alculquicondor

**Comment by tenzen-y** [comment]
> The idea is to extend the snapshot used for visibility with its revision (consecutive integers). The clusterQueuePendingWorkloads in the status would also keep the version of the snapshot used.

@mimowo Does that mean that we will add `revision` field to clusterQueuePendingWorkloads?

https://github.com/kubernetes-sigs/kueue/blob/84ac9527110faf24f165b7966756484a711f3417/apis/kueue/v1beta1/clusterqueue_types.go#L218-L226

If the external other controllers and humans modify the `revision`, what happens? Just reconciliation will be triggered?

**Comment by mimowo** [comment]
Yes, this is the idea. If a user changes manually to a lower version, then it would safe-heal by overriding with the current revision in the in-memory snapshot counter. If you bump to an arbitrarily high number, then (a) stop updating as this is not supported, or (b) detect that the value is higher than the current max, and override.

**Comment by alculquicondor** [comment]
Is this worth? These checks happen in a reconciler, which can have multiple workers. Is the CPU usage relevant, when compared to the latency of the API call?

**Comment by mimowo** [comment]
> Is this worth? These checks happen in a reconciler, which can have multiple workers. Is the CPU usage relevant, when compared to the latency of the API call?

Yeah, we anyway call `equality.Semantic.DeepEqual(cq.Status, oldStatus)` + send the request if there are differences. In the worst case scenario the DeepEqual for pendingWorkloadStatus needs to compare 4000 items, which seems negligible.

I'm happy to park it for now until we have some experiment, or user feedback that this is an issue.

**Comment by mimowo** [comment]
/close 
This is a performance optimization to the feature we deprecate in favor of VisibilityOnDemand, see discussion under: https://github.com/kubernetes-sigs/kueue/issues/1099
