### ISSUE TITLE
Function ```CmpNoOrder``` in ```pkg/util/slices``` fails for a few edge cases

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#1143]
**What happened**: Given slices A[1,1,2], and B[1,2,2] or  A[1,2] B[1,1] function ```CmpNoOrder``` returns wrong output - as if those slices were equal.

**What you expected to happen**: The function should return ```false``` as those slices differ.

**How to reproduce it (as minimally and precisely as possible)**: Call the function with mentioned arguments.

**Anything else we need to know?**: None

**Comment by mimowo** [comment]
Can we say "Function CmpNoOrder does work correctly in case of duplicated items"? To be more specific.
