### ISSUE TITLE
Allow AdmissionChecks controllers to set additional annotations, labels, node selectors and taints on workload pods.  

### ISSUE THREAD

**Issue by mwielgus** [kubernetes-sigs/kueue#1145]
**What would you like to be added**:

An additional field(s) in `Workload` and integration framework changes to allow setting additional
annotations, labels, node selector and taints on pods that belong to a particular `Workload`.

**Why is this needed**:

Some admission checks may want to narrow down the nodes on which the workload pods should be run. 

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by trasc** [comment]
/assign 
for API change

**Comment by mimowo** [comment]
/assign
For propagating and restoring the labels, annotations & tolerations

**Comment by trasc** [comment]
@tenzen-y I think this should be closed

**Comment by tenzen-y** [comment]
> @tenzen-y I think this should be closed

It makes sense.
/close
