### ISSUE TITLE
Preempted RayJob will not resume when resource reclaimed

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#1146]
**What happened**:

I tried with rayJob, but I guess this applies to other jobs as well. Correct me if not.
So when a lower priority rayJob preempted by a higher one and the higher rayJob completed, the lower priority rayjob will not resume.

**What you expected to happen**:

Resume when resource is sufficient.

**How to reproduce it (as minimally and precisely as possible)**:

1. Inside a clusterQueue, configured with `preemption.withinClusterQueue=LowerPriority`
2. submit a low priority rayjob
3. submit a high priority rayjob, since resource is insufficient, the high priority rayjob will preempted the lower one.
4. when the high priority rayjob completed, the lower one will not resume.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
We saw this exact problem in Jobset, but it turned out that Jobset didn't have permission to update/patch jobs.
Maybe there's a problem in the rayjob implementation of suspend?

**Comment by alculquicondor** [comment]
Or maybe it's a problem in the integration controller, but I don't think this problem is generalized for all jobs

**Comment by kerthcet** [comment]
It's a bug of rayjob controller, also maybe related to the upstream ray, but let me focus on kueue at first.
/assign
