### ISSUE TITLE
[Ray] Update Go Module version

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1155]
**What would you like to be added**:
We should upgrade go module version for kuberay.

**Why is this needed**:
Our version is outdated. However, the dependabot could not update the version.

https://github.com/kubernetes-sigs/kueue/blob/f9273bef71e136c0eed659ae19fce178512a6f6a/go.mod#L16
https://github.com/ray-project/kuberay/releases/tag/v0.6.0

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@trasc Could you take this one?

**Comment by lowang-bh** [comment]
Hi @tenzen-y  Could I take it?

/assign

**Comment by tenzen-y** [comment]
> Hi @tenzen-y Could I take it?
> 
> /assign

Sure.

**Comment by kerthcet** [comment]
@lowang-bh are you still working on this?

**Comment by lowang-bh** [comment]
> @lowang-bh are you still working on this?

Done in PR #1231
