### ISSUE TITLE
[doc] add documentation for workloadPriorityClass

### ISSUE THREAD

**Issue by Gekko0114** [kubernetes-sigs/kueue#1157]
**What would you like to be added**:
documentation for workloadPriorityClass

**Why is this needed**:
to support users

**Completion requirements**:
add documentation under site repo.

This enhancement requires the following artifacts:
- [ ] Docs update

Related to this PR https://github.com/kubernetes-sigs/kueue/pull/1081

**Comment by Gekko0114** [comment]
/assign

BTW, I can't add label on this issue. Could anyone add "kind/documentation" label?

**Comment by alculquicondor** [comment]
No idea what's happening. Can you create a new PR?

**Comment by Gekko0114** [comment]
> No idea what's happening. Can you create a new PR?

I will create a PR explaining how to use `workloadPriority` in https://kueue.sigs.k8s.io/docs/
Does it make sense?

**Comment by alculquicondor** [comment]
oops, I thought for a second this was a PR, not an issue. In that case, it doesn't matter much that this has the `needs-kind` label.

**Comment by Gekko0114** [comment]
Hi @alculquicondor , @tenzen-y

BTW, I would like to become a member of k8s/k8s-sig. Could you be willing to sponsor me?
(This is completely unrelated to this issue, I apologize.)

**Comment by tenzen-y** [comment]
> Hi @alculquicondor , @tenzen-y
> 
> BTW, I would like to become a member of k8s/k8s-sig. Could you be willing to sponsor me? (This is completely unrelated to this issue, I apologize.)

Sure. If you meet the requirements for the member, I'm happy to become a sponsor.

**Comment by alculquicondor** [comment]
Me too

**Comment by Gekko0114** [comment]
Thank you so much!!
