### ISSUE TITLE
Docs on using queue visibility feature for cluster queues

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1159]
A new docs page for the feature: https://github.com/kubernetes-sigs/kueue/issues/168

I think it could go under the tasks page: https://kueue.sigs.k8s.io/docs/tasks/, say "Monitor pending workloads in queue status". 

This could focus on the "done" part for now - the cluster queues. It would be extended for local queues in the future.

**Comment by mimowo** [comment]
FYI @stuton

**Comment by mimowo** [comment]
FYI @tenzen-y @alculquicondor 
For thoughts

**Comment by mimowo** [comment]
xref: https://github.com/kubernetes-sigs/kueue/issues/168

**Comment by tenzen-y** [comment]
How about "Monitor pending workloads"? We use `queue` as a shorter name for localQueue. So, it would be better to avoid using `queue` as a part of the title.

https://github.com/kubernetes-sigs/kueue/blob/4aea01deffc41a0c190df6608000ba2f6ab9a9c9/apis/kueue/v1beta1/localqueue_types.go#L95

**Comment by mimowo** [comment]
> How about "Monitor pending workloads"? 

sgtm
