### ISSUE TITLE
Does PodSetAssignments count have to be equal to podset count?

### ISSUE THREAD

**Issue by GhangZh** [kubernetes-sigs/kueue#1163]
![image](https://github.com/kubernetes-sigs/kueue/assets/92301646/d9c86bd9-7ddf-4b7e-a1a9-cb9bb68f715a)
If mincount is set, is workload count and PodSetAssignments count required to be the same here? Otherwise the workload will keep rebuilding, causing scheduling problems.

**Comment by alculquicondor** [comment]
we are comparing the `count`  in the job spec with the `count` coming from the assignment (the number of pods kueue allow the job to run).

we are not comparing `count` and `minCount`.

**Comment by trasc** [comment]
In sort the answer is no., in case of partial admission,  the admission `count` will be somewhere between  the `minCount` and the`count` of the podset depending on how many pod instances can fit the queue quota.

**Comment by GhangZh** [comment]
> we are comparing the `count` in the job spec with the `count` coming from the assignment (the number of pods kueue allow the job to run).
>
> we are not comparing `count` and `minCount`.

if minCount=1;count=2. According to the logic of the code will always return false, the workload will always be rebuilt.

**Comment by trasc** [comment]
In case of partial admission, the job should start running (be unsuspended) with an updated  count (the one coming from admission).

**Comment by GhangZh** [comment]
> In case of partial admission, the job should start running (be unsuspended) with an updated count (the one coming from admission).
Do you mean that the count of the podset is modified in case of partial admission? I understand that the count of the podset is constant, right?

**Comment by trasc** [comment]
The count of pod replicas that are actually run by the job (`min(Parallelism, Completions) `)  is changed, not the one found in  Workload.Spec.PodSet[*].Count.

**Comment by GhangZh** [comment]
> PodSetAssignments

Problem solved,  thanks. At startJob it changes Parallelism to stay consistent with PodSetAssignments count.

**Comment by kerthcet** [comment]
Talked with @GhangZh offline, his team is using kueue in production, I think his team can also be an adopter of kueue, feel free to fill in the list @GhangZh https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/, thanks.

**Comment by alculquicondor** [comment]
It looks like the link is wrong :)

here is the file with adopters https://github.com/kubernetes-sigs/kueue/blob/main/site/content/en/docs/adopters/index.md
