### ISSUE TITLE
[rayjob] status update not as timely as expected

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#1164]
**What would you like to be added**:

When rayjob is admitted, the status is not updated, it should be `Pending` I think.
Also, when rayjob is preempted and status transmit to `STOPPED`. Then when rayjob is `admitted` again, the status should transmit to `Pending` rather stays in `STOPPED`.

**Why is this needed**:

Better describe the job status.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
Isn't this on the rayjob side? the implementation of suspend?

**Comment by alculquicondor** [comment]
@achernevskii can you take this one?
It seems to me that this would be in kuberay side, not kueue.

**Comment by kerthcet** [comment]
Sorry, I just recorded here in case of forgotten, sorry for the confusion, I will dig into the reason and close this if necessary.
