### ISSUE TITLE
Validate workload PodSetUpdates

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1187]
**What happened**:

It is possible to set workload PodSetUpdates with invalid values, resulting in errors during workload admission.

**What you expected to happen**:

Fail fast on modifications to `workload.PodSetUpdates` which are performed by external controllers.

Validated things:
- `PodSetUpdates.name` should be a valid pod set name
- `PodSetUpdates.tolerations` should a valid list of tolerations, see https://github.com/kubernetes/kubernetes/blob/57d3cc66050545d7fefb0841e750a0a41df14144/pkg/apis/core/validation/validation.go#L3749
- validate annotations and labels, see: https://github.com/kubernetes/kubernetes/blob/57d3cc66050545d7fefb0841e750a0a41df14144/pkg/apis/core/validation/validation.go#L126

Proposed solution: workload webhook.

Part of  #1145

**Comment by mimowo** [comment]
FYI @alculquicondor

**Comment by alculquicondor** [comment]
+1
