### ISSUE TITLE
[dep] Updated `k8s.io/autoscaler/cluster-autoscaler` version to a stable one.

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#1194]
**What would you like to be cleaned**:

Use a released version of `k8s.io/autoscaler/cluster-autoscaler` containing https://github.com/kubernetes/autoscaler/commit/5155725a28189cd1b65f001fcdf90699f5cde909

**Why is this needed**:

Have clean dependencies.

**Comment by tenzen-y** [comment]
/remove-lifecycle stale

@trasc Since released the new cluster-autoscaler with PriviosningRequest API, we can do this, right?

**Comment by trasc** [comment]
@tenzen-y Indeed the the code we need is now part of a github release [1.29.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.29.0) but unfortunately the release is tagged with `cluster-autoscaler-1.29.0` instead of `cluster-autoscaler/v1.29.0` and it cannot be referenced from go.mod.

**Comment by tenzen-y** [comment]
> @tenzen-y Indeed the the code we need is now part of a github release [1.29.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.29.0) but unfortunately the release is tagged with `cluster-autoscaler-1.29.0` instead of `cluster-autoscaler/v1.29.0` and it cannot be referenced from go.mod.

@trasc Yea, that makes sense. Indeed, I'm working on new tag format `k8s.io/autoscaler/cluster-autoscaler/apis` in https://github.com/kubernetes/autoscaler/pull/6315#issuecomment-1893441957.

**Comment by tenzen-y** [comment]
This is replaced with #1896 
/close
