### ISSUE TITLE
hack/update-codegen.sh uses deprecated scripts

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1196]
**What would you like to be cleaned**:

When running `make generate`, this message shows up:

```
WARNING: generate-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.

WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.
```

**Why is this needed**:

Keep kueue building

**Comment by kannon92** [comment]
I think https://github.com/kubernetes-sigs/kueue/pull/1151/files should resolve this

**Comment by kannon92** [comment]
Maybe this ticket is a duplicate of https://github.com/kubernetes-sigs/kueue/issues/1134

**Comment by tenzen-y** [comment]
> Maybe this ticket is a duplicate of https://github.com/kubernetes-sigs/kueue/issues/1134

Yes, that's right.
/close
