### ISSUE TITLE
Add support for label as a quota key

### ISSUE THREAD

**Issue by renanvicente** [kubernetes-sigs/kueue#1209]
**What would you like to be added**:
It would be great if you could add a label as a quota key.
**Why is this needed**:
for cases where you don't want more than a certain number of pods that have a specific label to be created.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by trasc** [comment]
This might not be very easy to do, however, you can define a custom resource name, setup a quotas for that resource and set requests/limits of that resource only on the pods you want to be accounted. 

This will work at `container` level instead of `pod` but I think it might cover your usecase.

**Comment by alculquicondor** [comment]
You can implement this by:
- Having a CQ per label that you are interested.
- Have a webhook that takes the label and sets a queue name.
- Use the number of pods as quota limit for the CQ.

But maybe you can share a little about the higher level use case? Why do you need this? Maybe there is an alternate way of expressing the same requirement.
