### ISSUE TITLE
Graduate Partial admission to Beta

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1212]
**What would you like to be added**:

Graduate PartialAdmission to beta and enable by default.

**Why is this needed**:

So that the feature is readily available for use

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
I think we can graduate this feature gate to Beta in v0.5 if any bug isn't reported by users.
