### ISSUE TITLE
When a job resets reclaimable pods when evicted, it gets stuck due to Workload validation

### ISSUE THREAD

**Issue by GhangZh** [kubernetes-sigs/kueue#1215]
If the workload is preempted, will ReclaimablePod be set to nil?
![image](https://github.com/kubernetes-sigs/kueue/assets/92301646/56036425-2fc6-410d-844e-02b864c4c218)
```bash
{"level":"error","ts":"2023-10-16T12:47:55.770288657Z","caller":"controller/controller.go:324","msg":"Reconciler error","controller":"job","controllerGroup":"batch.volcano.sh","controllerKind":"Job","Job":{"name":"hobot-job-xxx","namespace":"cpu-preempt"},"namespace":"cpu-preempt","name":"hobot-job-xxx","reconcileID":"f4abf36a-f5f2-4ec0-bbae-31b49cfef394","error":"admission webhook \"[vworkload.kb.io](http://vworkload.kb.io/)\" denied the request: status.reclaimablePods[main]: Required value: cannot be removed","stacktrace":"[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler/n/t/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324/nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem/n/t/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265/nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2/n/t/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226)"}
```
Is this our normal logic, or am I using it incorrectly, which would cause the webhook checksum to fail for the departure workload.

**Comment by alculquicondor** [comment]
cc @trasc 

Yes, the reclaimable pods should stay, because those reclaimable pods shouldn't be recreated when the job is resumed.

Can you elaborate about the webhook failure?

**Comment by alculquicondor** [comment]
I opened a couple of follow ups based on your question

**Comment by GhangZh** [comment]
> cc @trasc
> 
> Yes, the reclaimable pods should stay, because those reclaimable pods shouldn't be recreated when the job is resumed.
> 
> Can you elaborate about the webhook failure?

1. Queue A resources to meet the minCount, task jobA normal operation, such as some of the pod has been completed, ReclaimPod will record the number of completed, but there are still part of the pod in the running
2. At this time, queue A is occupied by the task of queue B will happen this webhook failure

**Comment by alculquicondor** [comment]
I see
/kind bug

**Comment by GhangZh** [comment]
> I opened a couple of follow ups based on your question

That's great. I really need this.

**Comment by trasc** [comment]
skipping https://github.com/kubernetes-sigs/kueue/blob/525098b838eb28ee241cf1aaee5e53f161d30a0c/pkg/controller/jobframework/reconciler.go#L268-L278

while the workload has the evicted condition set, should do the trick.

**Comment by trasc** [comment]
> why? Are you suggesting that, during suspend, the calculation for number of reclaimable pods is somehow decreasing?

Yes it could be,  it's not the case for `batch/job` but for other kind of jobs, as long as workload is not attempting to increase it's usage while holding a quota-reservation it should be fine.

**Comment by alculquicondor** [comment]
@GhangZh in which job API were you observing this?

**Comment by GhangZh** [comment]
> @GhangZh in which job API were you observing this?

volcano job

**Comment by alculquicondor** [comment]
I see.
Yes, that's correct.
If vcjob can't support this, you can choose not to implement `ReclaimablePods` and it will be assumed zero.

Otherwise, have a look at Job's implementation https://github.com/kubernetes-sigs/kueue/blob/6c812be6d9bbe2214cae5cfcaa33953f7a14fdba/pkg/controller/jobs/job/job_controller.go#L190

We rely on the succeeded count

**Comment by alculquicondor** [comment]
/retitle When a job resets reclaimable pods when evicted, it gets stuck due to Workload validation
