### ISSUE TITLE
Let Helm chart specify which FeatureGates should be used

### ISSUE THREAD

**Issue by rhaps0dy** [kubernetes-sigs/kueue#1230]
**What would you like to be added**:

kueue uses [feature gates](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/features/kube_features.go#L29-L67) to preview features, and these are present in releases.

I would like to add a section in the Helm chart, either under [`controllerManager.config`](https://github.com/kubernetes-sigs/kueue/blob/91d5f645a326dae1ea8542879adcc62ba4db7f5d/charts/kueue/values.yaml#L19C11-L19C11) or [`managerConfig`](https://github.com/kubernetes-sigs/kueue/blob/main/charts/kueue/values.yaml#L53), which looks like this:

```yaml
featureGates:
  partialAdmission: true
  queueVisibility: false
  flavorFungibility: true
```

**Why is this needed**:

At the moment, enabling or disabling feature gates requires either:
- kustomizing the manifests
- forking the Helm chart and changing it to include feature gates

Often the feature gates are [documented in releases](https://kueue.sigs.k8s.io/docs/tasks/setup_sequential_admission/) even while they're in alpha. Changing a command-line argument shouldn't require forking.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

Is there appetite for a PR with this? I'd be happy to write the docs and API change if so

**Comment by tenzen-y** [comment]
This is a good point. Probably, we can select [controllerManager.config](https://github.com/kubernetes-sigs/kueue/blob/91d5f645a326dae1ea8542879adcc62ba4db7f5d/charts/kueue/values.yaml#L19C11-L19C11).

**Comment by kerthcet** [comment]
cc @B1F030 this also relates to kueue's features which are controlled by the feature gate.
