### ISSUE TITLE
Inject tolerations from ResourceFlavors

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1233]
**What would you like to be added**:

A field in ResourceFlavor that is used to inject tolerations in jobs that land in the flavor.

This information can then be communicated to ProvisioningRequest to inform scale ups.

Note that the ResourceFlavor already has a `nodeTaints` field that prevents jobs from landing on them, unless they explicitly tolerate them. The new `tolerations` field would be a complementary API.

**Why is this needed**:

It's useful to have taints in the nodes that back a ResourceFlavor so that they are not accidentally used by pods that are not supposed to be there.

This is common for hardware accelerators such as GPUs, to prevent non-GPU pods to land on the nodes. Cloud provider webhooks sometimes inject these tolerations into Pods, when a Pod requests the accelerator. However, they cannot possibly target every job CRD.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
@trasc I think the ResourceFlavor API is the best place to put these tolerations, as it goes beyond ProvisioningRequest.

**Comment by alculquicondor** [comment]
cc @mwielgus

**Comment by tenzen-y** [comment]
How does the kueue pass tolerations's `operator` from resourceFravor to jobs?

**Comment by alculquicondor** [comment]
this would be a new field `tolerations`, in addition to the existing `nodeTaints`.
The `tolerations` would include an `operator`.

**Comment by tenzen-y** [comment]
> this would be a new field `tolerations`, in addition to the existing `nodeTaints`. The `tolerations` would include an `operator`.

Ah, this feature aims to extend the ResourceFlavor API by adding a `tolerations` field. Thanks.

**Comment by alculquicondor** [comment]
> the provisioning admission check controller might need to check the flavors assigned (have a whitelist or something)

Don't we already do that for injecting node selectors into the template?

That said, we should probably consider putting the node selectors and tolerations somewhere in the Workload status during quota reservation. This way, the job controllers and the AC controllers don't need to know about ResourceFlavor.

Maybe we can do it as part of this effort.

> Having the toleration in the provisioning config will just require adding them in the PodSetUpdates to make it to the actual pod.

I agree that it looks simpler, but in ResourceFlavor seems more universally useful.

**Comment by trasc** [comment]
> Don't we already do that for injecting node selectors into the template?

It's done in order to add the node selectors in the pod templates, but there is no decision in terms of I "like" this flavor or not.

> That said, we should probably consider putting the node selectors and tolerations somewhere in the Workload status during quota reservation. This way, the job controllers and the AC controllers don't need to know about ResourceFlavor.

This could be helpful, but maybe in another issue.

**Comment by alculquicondor** [comment]
> It's done in order to add the node selectors in the pod templates, but there is no decision in terms of I "like" this flavor or not.

The tolerations would behave the same way. There is not decision at this point, just injection. The decision is already done by the kueue scheduler.

**Comment by tenzen-y** [comment]
/reopen 

We need to add documentation about this feature.
