### ISSUE TITLE
Avoid use of Consistently in Kubeflow tests

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1234]
**What would you like to be cleaned**:

The Kubeflow tests (MPI and others) have 5 uses of `Consistently`. We should remove them if they don't provide much value.

**Why is this needed**:

A somewhat busy wait in integration tests can increase the runtime of the tests and usually add meaningful coverage. We should avoid them as much as possible.

**Comment by alculquicondor** [comment]
@stuton can you take this one?

**Comment by tenzen-y** [comment]
And also, we should strictly verify conditions. Please see details: https://github.com/kubernetes-sigs/kueue/pull/1191#discussion_r1367415961
