### ISSUE TITLE
[Provisioning ACC] Add an event recorder.

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#1246]
**What would you like to be added**:
An Event recorder in the Provisioning Admission Check Controller.

**Why is this needed**:

- Ease tracing the Admission Check State changes in the workloads lifecycle.
- Ease tracing the Admission Check `Active` condition status changes.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
Who is working on this issue?

**Comment by stuton** [comment]
@tenzen-y, I will
/unassign @trasc

**Comment by tenzen-y** [comment]
> @tenzen-y, I will /unassign @trasc

Thank you for letting me know.
