### ISSUE TITLE
Add pages with automatically generated API documentation

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1249]
**What would you like to be added**:

API documentation auto-generated from the types.go files.

/kind documentation

**Why is this needed**:

This is an easy way to browse the definition of every field of the API.

We should investigate how kubernetes API reference is generated and use similar tools

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by trasc** [comment]
Preview link (using kubernetes-sigs/reference-docs/genref) https://deploy-preview-1263--kubernetes-sigs-kueue.netlify.app/docs/reference/kueue.v1beta1/

**Comment by alculquicondor** [comment]
/assign stuton
Can you add links from each Concept page into the relevant Reference docs?

**Comment by alculquicondor** [comment]
/unassign stuton

I opened a separate issue #1281
