### ISSUE TITLE
A cluster queue may be stuck in "Terminating" if it has Reserving workloads pending on an inactive check.

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#1253]
**What happened**:
A cluster queue may be stuck in "Terminating" if it has Reserving workloads pending on an inactive check.

**What you expected to happen**:
A deleted cluster queue should eventually release its  finalizer and be fully deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
Does "inactive" mean that cluserqueue is inactive? or admissioncontroller is inactive?

**Comment by trasc** [comment]
> Does "inactive" mean that cluserqueue is inactive? or admissioncontroller is inactive?

In this context, Admission Check, however , having an inactive Admission Check, makes the queue inactive as well.

**Comment by tenzen-y** [comment]
> > Does "inactive" mean that cluserqueue is inactive? or admissioncontroller is inactive?
> 
> In this context, Admission Check, however , having an inactive Admission Check, makes the queue inactive as well.

I see. Thanks. I think we should include this bug fixed in the next release. Can you open a PR?
The deadline for the next release will be coming up soon. Today or Tomorrow.
