### ISSUE TITLE
Adding toleration to the job doesn't trigger workload change.

### ISSUE THREAD

**Issue by yaroslava-serdiuk** [kubernetes-sigs/kueue#1264]
Due to [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/job/#mutable-scheduling-directives) 
> The fields in a Job's pod template that can be updated are node affinity, node selector, tolerations, labels, annotations and scheduling gates

However modifying those fields doesn't trigger any change in job reconciler, because workload identified as matched to the updated job (https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/jobframework/reconciler.go#L409)

We already have a todo to fix this https://github.com/kubernetes-sigs/kueue/blob/main/pkg/util/equality/podset.go#L27

**Comment by trasc** [comment]
> We already have a todo to fix this https://github.com/kubernetes-sigs/kueue/blob/main/pkg/util/equality/podset.go#L27

Indeed, at least for tolerations which could influence the flavor assigned, we should update the podsets, however the toleratoins can also be changed (in the job) by Kueue on startJob()/stopJob(), this should be taken into account and propagate the change only when the workload is not reserving quota.
