### ISSUE TITLE
Policy to put Workloads in front of the queue after eviction

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1282]
**What would you like to be added**:

A policy that allows to put evicted jobs in the front of the queue after eviction.

**Why is this needed**:

This is particularly important for WaitForPodsReady: if a job is stuck in a low availability flavor, after timeout, it should go to the front of the queue and immediately considered for admission in other flavors, which might have higher availability (like being backed by a reservation).

The case of preemption might be more tricky: we want the preempted jobs to be readmitted as soon as possible. But if a job is waiting for more than one job to be preempted and the queueing strategy is BestEffortFIFO, we don't want the preempted pods to take the head of the queue.
Maybe we need to hold them until the preemptor job is admitted, and then they should use the regular priority.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
As we discussed in KEP (https://github.com/kubernetes-sigs/kueue/pull/1311#issuecomment-1870531528), we will introduce a backoff and a max number of retries mechanism to prevent infinity requeuing the job to the head.

So, I will update KEP 1282.
/assign

**Comment by alculquicondor** [comment]
@tenzen-y could you add a quick note in the documentation?

**Comment by tenzen-y** [comment]
> @tenzen-y could you add a quick note in the documentation?

Sure, I will extend documentation by stable v0.6 release.
