### ISSUE TITLE
Update High-level Kueue operation diagram

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1317]
We should update the diagram in https://kueue.sigs.k8s.io/docs/overview/#high-level-kueue-operation.

We should probably update admissionChecks and clusterAutoscaler integration.

/kind documentation

**Comment by tenzen-y** [comment]
xref: https://static.sched.com/hosted_files/colocatedeventsna2023/78/Batch%20systems%20in%20production%20with%20Kueue.pdf

**Comment by mbobrovskyi** [comment]
@tenzen-y I'm working on the new diagram [here](https://drive.google.com/file/d/17YGvk5_6rgsWdSbOQ0ICnXee-E0zQqMH/view?usp=drive_link). Could you check please? Did I miss something?
