### ISSUE TITLE
Support Kuberay v1 CRDs

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/kueue#1335]
**What would you like to be added**:

Kuberay released v1.0.0 last week, which introduces v1 version for their CRDs. We should ensure that v1 RayJobs (and soon RayClusters) can be supported with Kueue.

**Why is this needed**:

To support future versions of kuberay APIs

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [X] API change
- [X] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
Does kuberay provide conversion webhooks?

**Comment by andrewsykim** [comment]
> Does kuberay provide conversion webhooks?

No it does not :(

**Comment by tenzen-y** [comment]
> > Does kuberay provide conversion webhooks?
> 
> No it does not :(

I see... Maybe, we need to implement a job controller for RayJob v1 separate from v1alpha1 :(
