### ISSUE TITLE
Confusing QueueingStrategy API description

### ISSUE THREAD

**Issue by yaroslava-serdiuk** [kubernetes-sigs/kueue#1379]
From API: 
```
type QueueingStrategy string

const (
	// StrictFIFO means that workloads are ordered strictly by creation time.
	// Older workloads that can't be admitted will block admitting newer
	// workloads even if they fit available quota.
	StrictFIFO QueueingStrategy = "StrictFIFO"

	// BestEffortFIFO means that workloads are ordered by creation time,
	// however older workloads that can't be admitted will not block
	// admitting newer workloads that fit existing quota.
	BestEffortFIFO QueueingStrategy = "BestEffortFIFO"
)
```

however in fact we use priority queueing: 
https://github.com/kubernetes-sigs/kueue/blob/main/pkg/queue/cluster_queue_strict_fifo.go#L47

I found it confusing and doesn't correspond to the API description.

**Comment by aleksandra-malinowska** [comment]
+1, also got confused by this. If we can't change strategy names, maybe sth like this would help?

```
	// StrictFIFO means that workloads of the same priority are ordered strictly by creation time.
	(...)
	// BestEffortFIFO means that workloads of the same priority are ordered by creation time,
```

**Comment by tenzen-y** [comment]
We mention priority in this document: https://kueue.sigs.k8s.io/docs/concepts/cluster_queue/#queueing-strategy
So, I guess that we missed to update the API description.

**Comment by yaroslava-serdiuk** [comment]
If we can't change names, maybe worth introduce the new proper names and depreciate those ones?

**Comment by yaroslava-serdiuk** [comment]
The comments were updated in https://github.com/kubernetes-sigs/kueue/pull/1399
