### ISSUE TITLE
Respect NS ResourceQuota in Kueue

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#1403]
**What would you like to be added**:

NS ResourceQuota helps to constrain the quota for each ns, however, we didn't count this resource in Kueue, this will lead to like workload admitted in kueue, but blocked by kubernetes pod creation as violating the NS ResourceQuota.

Some rough ideas:
- For localQueue, since it's namespaced, jobs belong to one localQueue should not exceed the NS ResourceQuota.
- For clusterQueue, in creation, if all NS has ResourceQuota, then the sum of clusterQueue should not exceed the sum of ResourceQuota.

Glad to hear other ideas.

**Why is this needed**:

Fill up the gap with plain kubernetes.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
cc @B1F030

**Comment by tenzen-y** [comment]
This is duplicated with #696
