### ISSUE TITLE
Flaky admission checks integration tests

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#1424]
**What happened**:
Admission checks provisioning integration tests failed

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1415/pull-kueue-test-integration-main/1733054915275657216

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment]
This seams to be a test runner issue.

**Comment by tenzen-y** [comment]
> https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1415/pull-kueue-test-integration-main/1733054915275657216

It seems right. It seems that CPU throttling sometimes happens (limit 4core, used 6core):

https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&from=now-7d&to=now&var-org=kubernetes-sigs&var-repo=kueue&var-job=pull-kueue-test-integration-main&var-build=All&refresh=30s

**Comment by mimowo** [comment]
/close
we probably don't have any logs from this run anyway, let's open a new one if re-occurs. 

For the runner we bumped the resources recently: https://github.com/kubernetes/test-infra/pull/32150
