### ISSUE TITLE
Should we move QueuedWorkload.Admission to Status?

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#143]
With the recent re-definition of object Status semantics, it is now acceptable to have persistent fields there. Given that, it seems more appropriate to have the `Admission` field of QueuedWorkload in the Status field rather than the Spec.

**Comment by alculquicondor** [comment]
My main motivation for putting it in the spec is to give break-glass capabilities to administrators to start jobs directly assigned to a QC. It's not easy to "apply" the status from a yaml.

**Comment by ahg-g** [comment]
I keep forgetting that reason! Worth documenting it in the docs.

**Comment by ahg-g** [comment]
> is to give break-glass capabilities to administrators to start jobs directly assigned to a QC

They need to set the flavors as well, which is not a pretty experience.
