### ISSUE TITLE
AdmissionChecks should be configurable per flavor

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1432]
**What would you like to be added**:

Allow AdmissionChecks to be required for a Workload if it gets assigned a specific flavor.

**Why is this needed**:

The user might want to only issue a ProvisioningRequest if targeting a specific flavor, or might want different engines.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by maci0** [comment]
+1
