### ISSUE TITLE
Implement cache dump via signals

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1437]
**What would you like to be added**:

A cache dump that is activated through a signal, similar to kube-scheduler:

https://github.com/kubernetes/kubernetes/blob/0c645922edcc06adff43c70c02fb56751364bbb5/pkg/scheduler/internal/cache/debugger/debugger.go#L59

**Why is this needed**:

To debug complex issues

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
Or we could maybe use the apiserver extension?
But I'm not too eager to use this mechanism for debugging purposes, only for things that end-users might care about visualizing.

wdyt @mimowo?

**Comment by mimowo** [comment]
> Or we could maybe use the apiserver extension?
> But I'm not too eager to use this mechanism for debugging purposes, only for things that end-users might care about visualizing.

Yes, I prefer signals, at least as the first iteration. If we add the endpoint we commit to secure and maintain the endpoint, so substantially more work.

**Comment by mimowo** [comment]
> Yes, I prefer signals, at least as the first iteration. If we add the endpoint we commit to secure and maintain the endpoint, so substantially more work.

OTOH, the endpoint might be useful when there is no direct access to the VM running Kueue, so I don't hold a strong view.
