### ISSUE TITLE
ClusterQueue namespace selector docs is not clear

### ISSUE THREAD

**Issue by moficodes** [kubernetes-sigs/kueue#1439]
**What would you like to be added**:

Example / Clarification on how to select on specific namespace either using `matchLabel` or `matchExpressions` for `ClusterQueue`.

**Why is this needed**:

From the docs its not clear how users can target a specific namespace in clusterqueue.

**Completion requirements**:

Examples of targeting a specific namespace or a list of namespace in the clusterqueue docs.

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

@alizaidis

**Comment by alizaidis** [comment]
Example for matchLabels:

namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: team-a

Example for matchExpressions:

matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - team-a
      - team-b
      - team-c
