### ISSUE TITLE
Automatically sync webhookConfigurations to helm charts

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1461]
**What would you like to be added**:
We should implement scripts to sync webhookConfigurations to helm charts and validate automatically.

**Why is this needed**:
To avoid forgetting to sync webhookConfigurations to helm charts.

ref: https://github.com/kubernetes-sigs/kueue/issues/1407

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by B1F030** [comment]
Hi! I wirte a PR to resolve this, can you take a look? @tenzen-y
