### ISSUE TITLE
Flaky: Provisioning when A workload is using a provision admission check Should let a running workload to continue after the provisioning request deleted

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1484]
**What happened**:

Failed "[It] Provisioning when A workload is using a provision admission check Should let a running workload to continue after the provisioning request deleted"

**What you expected to happen**:

No error wouldn't happen.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1468/pull-kueue-test-integration-main/1736772290600767488

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment]
@alculquicondor where is this  test scenario coming from? What do we actually expect in this case (provisioning request deletion while admitted)?

**Comment by alculquicondor** [comment]
oh, we added this recently @B1F030

The lifecycle of ProvReq object is independent from the Workload. You can think of a customer having a controller cleaning up ProvReq objects

**Comment by tenzen-y** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1487/pull-kueue-test-integration-main/1736808350944858112

**Comment by trasc** [comment]
> The lifecycle of ProvReq object is independent from the Workload. You can think of a customer having a controller cleaning up ProvReq objects

But the admission check controller will recreate the provisioning request, which at lease in the early stages will not be available and the workload will get evicted.

**Comment by mimowo** [comment]
> But the admission check controller will recreate the provisioning request, which at lease in the early stages will not be available and the workload will get evicted.

IIUC if the workload is already admitted (running) then we would not be sync the provisioning requests (`syncOwnedProvisionRequest`), because we exit earlier: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/admissionchecks/provisioning/controller.go#L138.

**Comment by alculquicondor** [comment]
That's why we added the test. That's the behavior we want and we want to make sure it doesn't regress.
