### ISSUE TITLE
Verify shcellscript by shellcheck

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1518]
**What would you like to be cleaned**:
It would be better to verify all shell scripts by the [spellcheck](https://github.com/koalaman/shellcheck) every PR.

**Why is this needed**:
We should have more stable shell scripts.

**Comment by jaydee029** [comment]
Hi, I would like to work on this, @tenzen-y 
do we create a ci workflow for this .

**Comment by tenzen-y** [comment]
@jaydee029 No, we don't. We need to add a Make target like https://github.com/kubernetes-sigs/kueue/blob/b83b2448fbfb8ad263724ee53277081955d2735a/Makefile#L189-L191, then we can call the target in the Make verify target: https://github.com/kubernetes-sigs/kueue/blob/b83b2448fbfb8ad263724ee53277081955d2735a/Makefile#L194

**Comment by jaydee029** [comment]
okay , sure

**Comment by tenzen-y** [comment]
> okay , sure

@jaydee029 You can take this issue by the comment as `/assign`

**Comment by Vandit1604** [comment]
Hey @jaydee029, Are you still working on this?
If not, I would like to take a stab on it.

**Comment by jaydee029** [comment]
Go for it

**Comment by mayens** [comment]
Hi @Vandit1604 
Are you still working on it? If not I'm interested
Thanks

**Comment by Vandit1604** [comment]
Hey @mayens , 
I'm working on this.
Thanks
