### ISSUE TITLE
Limited scope user can have a way to get overview of quota 

### ISSUE THREAD

**Issue by panpan0000** [kubernetes-sigs/kueue#1526]
**What would you like to be added**:

For people only having **namespaced** privilege, localqueue only shows the usage and reserved resources.
but people may want to know the total usable quota , so that to plan their usage.
but the total quota only exist  in ClusterQueue CR , but it's cluster-scoped CRD, privilege stop people to get the total values:
```
Error from server (Forbidden): clusterqueues.kueue.x-k8s.io is forbidden: User "xxx" cannot list resource "clusterqueues" in API group "kueue.x-k8s.io" at the cluster scope
```

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
Since it's namespaced, doesn't this already as you expected, since clusterQueue is cluster-wide. Or a namespaced user will see all the clusterQueues out of his bounds.

**Comment by panpan0000** [comment]
thanks for reply, but please notice that in my scenario, as a limited user, I want to get the queue QUOTA, instead of ClusterQueue CR.
I think it's very reasonable that for a namespaced limited user to understand how much quota still left that he/she can use.
