### ISSUE TITLE
Filling up the gap between kueue with scheduler

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#1530]
**What would you like to be added**:

Kueue and kube-scheduler are separation of concerns, there's a gap under the hood, like kueue admits, but failed in scheduler, 
which will lead to underutilized resources as job is pending but resources are occupied. Job preemption is something out of this scope.

There's no better way standing out so far but we can mitigate this with **TTL** strategy. The general idea is when Job is **Not Ready** for a duration of time, we'll suspend the job for reclaim. But the tricky thing is how we handle this kind of Jobs, maybe a backoffQ is something we can consider.

Post for ideas.

**Why is this needed**:

As the title describes.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@kerthcet What is different between `waitForPodsReady`?
IIUC, `waitForPodsReady` seems to be sufficient for your use cases.

**Comment by kerthcet** [comment]
The mainly difference is it's non-blocking, but will **reclaim** the Job if pending in starting for a period of time, **waitForPodsReady** is slow. It's also opt-in.

**Comment by tenzen-y** [comment]
> The mainly difference is it's non-blocking, but will **reclaim** the Job if pending in starting for a period of time, **waitForPodsReady** is slow. It's also opt-in.

@kerthcet Given that the `blockAdmission` is false, kueue wouldn't block the following jobs and could reclaim the resources used in the job that exceeded the timeout.

https://kueue.sigs.k8s.io/docs/reference/kueue-config.v1beta1/#WaitForPodsReady

@kerthcet Any other difference?

**Comment by kerthcet** [comment]
Doesn't the timeout only works when `waitForPodsReady` is enabled? Do you mean when `waitForPodsReady` is enabled and `blockAdmission` is disabled, we'll have a non-blocking queue and will reclaim not-ready jobs after timeout? Based on my understanding, that's not implemented, but I'll try.

**Comment by kerthcet** [comment]
> Do you mean when waitForPodsReady is enabled and blockAdmission is disabled, we'll have a non-blocking queue and will reclaim not-ready jobs after timeout

seems the right path, I'll close this then. Thanks.

/close

**Comment by tenzen-y** [comment]
> Do you mean when waitForPodsReady is enabled and blockAdmission is disabled, we'll have a non-blocking queue and will reclaim not-ready jobs after timeout

Yes, I meant what you say. The kueue manager will block jobs only when both `waitForPodsReady=true` and `blockAdmission=true`:

https://github.com/kubernetes-sigs/kueue/blob/7bf4e920808eaac7324bee05c636721861a0280c/cmd/kueue/main.go#L365-L367

Also, the kueue manager will reclaim resources from jobs that exceeded the timeout regardless of `blockAdmission`:

https://github.com/kubernetes-sigs/kueue/blob/7bf4e920808eaac7324bee05c636721861a0280c/pkg/controller/core/core.go#L68-L79
