### ISSUE TITLE
Scheduler integration tests should be independent of the job controller

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#155]
**What would you like to be cleaned**:

The scheduler integration should create QueuedWorkloads instead of Jobs.

**Why is this needed**:

Separation of concerns.

**Comment by ahg-g** [comment]
I still think having end-to-end tests like the ones we have are necessary to have.

**Comment by ahg-g** [comment]
we could move them to be under the job controller integration tests.

**Comment by alculquicondor** [comment]
We could have a simple test case in the job controller.

But more advanced scenarios should just create a QueuedWorkload.

**Comment by thisisprasad** [comment]
@alculquicondor Here are my findings:
1. we can replace each job in the test by a workload
2. The assertions of the job should also be removed. Assertions should only be done on the basis of workload and its metrics.

Correct me if I'm wrong.
Would like to know more details on this task if there are any.

**Comment by thisisprasad** [comment]
I would like to work on this task
/assign

**Comment by alculquicondor** [comment]
That is correct. Feel free to start.

But remember to leave at least one test that uses a Job. If possible, do it in the job_controller test. But it's fine to be somewhere else if it doesn't make sense from a technical point of view.
