### ISSUE TITLE
Pod group: Replacement Pods should be added as Workload owners

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1557]
**What happened**:

When a Pod fails, it can be replaced with a new pod. However, the new pod doesn't become an owner of the Workload.

This could lead to a Workload from disappearing before all the Pod finalizers have been removed.

**What you expected to happen**:

The replacement Pod should be owner of the Workload. Excess pods should not be owners.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create pod group
2. Fail one pod
3. Create replacement pod

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
cc @achernevskii

**Comment by alculquicondor** [comment]
From @mimowo:

re-admitted workload gets deleted after completing. This is because the replacement pods don't become owners of the workload. So the workload gets deleted by garbage-collector very quickly

**Comment by mimowo** [comment]
/assign
I would like to give it a try, continuing tasks related to pod groups
