### ISSUE TITLE
Flaky Provisioning Request integration test

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1558]
**What happened**:

Flaky test:

`Provisioning when A workload is using a provision admission check with retry Should retry when ProvisioningRequestConfig has MaxRetries>o, and every Provisioning request retry fails`

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-integration-main/1743668546505805824

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
/assign @mimowo
as author of #1351

**Comment by mimowo** [comment]
ack

**Comment by mimowo** [comment]
As discussed with Aldo offline, the second creation request should conflict and fail, so still some investigation is needed.

**Comment by mimowo** [comment]
Also, weirdly I repeated the test 380 times locally already and all passed, so it is rare...

**Comment by mimowo** [comment]
Ok, got it reproduced locally!
