### ISSUE TITLE
Add documentation page on preemption

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1587]
**What would you like to be added**:

A page for documentation of preemption. Preferably with some examples and diagrams.

**Why is this needed**:

Currently, the only available documentation on preemption is API reference. This is hard to digest without supporting diagrams and examples.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Docs update

**Comment by mimowo** [comment]
cc @alculquicondor @mwielgus 
The remaining question is, do we want to as Concepts, Tasks, or idependent page, such as `Admission Checks`. 

I think we could go under "Tasks" as "Configure preemption".

**Comment by tenzen-y** [comment]
@mimowo We have documentation for the preemption here: https://kueue.sigs.k8s.io/docs/concepts/cluster_queue/#preemption

**Comment by mimowo** [comment]
@tenzen-y thank you! So, from the perspective of completing https://github.com/kubernetes-sigs/kueue/issues/1337 it should be enough to extend that page, right/

Still, I think it makes sense to keep the Issue open, because the page is pretty much just API. I imagine it would be nice to have the documentations with diagrams such as https://github.com/kubernetes-sigs/kueue/issues/1283#issuecomment-1834370396. WDYT?

**Comment by alculquicondor** [comment]
Yeah, a Task page would be great in the future, describing multiple scenarios.

**Comment by tenzen-y** [comment]
> @tenzen-y thank you! So, from the perspective of completing #1337 it should be enough to extend that page, right/

It's correct.

> Still, I think it makes sense to keep the Issue open, because the page is pretty much just API. I imagine it would be nice to have the documentations with diagrams such as [#1283 (comment)](https://github.com/kubernetes-sigs/kueue/issues/1283#issuecomment-1834370396). WDYT?

SGTM

**Comment by alculquicondor** [comment]
Another alternative would be a concept page under ClusterQueue?

**Comment by alculquicondor** [comment]
This is done in #2322
