### ISSUE TITLE
Flaky E2E test for Pod replacement

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1593]
**What happened**:

Sometimes the Workload is never declared as Finished.

```
End To End Suite: kindest/node:v1.29.0: [It] Pod groups when Single CQ Failed Pod can be replaced in group expand_less	50s
{Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:300 with:
it's finished failed [FAILED] Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:300 with:
it's finished
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:224 @ 01/16/24 20:19:48.709
}
```

Looking at the kube-scheduler logs, the Pod called `excess` got scheduled, which shouldn't have happened. This either means that some other Pod failed or was identified as an excess by Kueue.

**What you expected to happen**:

The workload to finish successfully

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1592/pull-kueue-test-e2e-main-1-29/1747351345448357888

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
This occurred here, again: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1542/pull-kueue-test-e2e-main-1-28/1747378071394062336

**Comment by B1F030** [comment]
There are some similar flaky tests: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1385/pull-kueue-test-e2e-main-1-29/1747566443098017792

**Comment by alculquicondor** [comment]
That last one doesn't seem related. It looks like there was a failure to delete a ResourceFlavor during cleanup.

Please file a separate bug if you can confirm that this is not related to your PR.

As for @tenzen-y's report, it doesn't include log level 3 yet :(

I'll keep trying to repro.

**Comment by tenzen-y** [comment]
> That last one doesn't seem related. It looks like there was a failure to delete a ResourceFlavor during cleanup.
> 
> Please file a separate bug if you can confirm that this is not related to your PR.
> 
> As for @tenzen-y's report, it didn't include log level 3 yet :(
> 
> I'll keep trying to repro.

> @B1F030

**Comment by B1F030** [comment]
> > That last one doesn't seem related. It looks like there was a failure to delete a ResourceFlavor during cleanup.
> > Please file a separate bug if you can confirm that this is not related to your PR.
> > As for @tenzen-y's report, it didn't include log level 3 yet :(
> > I'll keep trying to repro.
> 
> @B1F030

Sorry, I'm not sure if this is related to my PR.
But that didn't happen again ever since the e2e test fixed, so I think [that](https://github.com/kubernetes-sigs/kueue/issues/1593#issuecomment-1895575380) is fixed too.
If I meet a flaky test again, I will open another issue.

**Comment by tenzen-y** [comment]
> > > That last one doesn't seem related. It looks like there was a failure to delete a ResourceFlavor during cleanup.
> > > Please file a separate bug if you can confirm that this is not related to your PR.
> > > As for @tenzen-y's report, it didn't include log level 3 yet :(
> > > I'll keep trying to repro.
> > 
> > 
> > @B1F030
> 
> But that didn't happen again ever since the e2e test fixed

This E2E issue isn't resolved, yet.
