### ISSUE TITLE
Do workload.NewInfo once when inserting updating

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#162]
**What would you like to be cleaned**:

When we are inserting into Queues and ClusterQueues, we are calling `NewInfo` twice (once for Queue and once for ClusterQueue), which is wasteful.

Maybe we can call `NewInfo` in the manager and always insert `workload.Info` objects in the Queue and ClusterQueue.

Unless we want to store other information, such as last scheduling attempt? cc @denkensk
Then we need a better solution

**Why is this needed**:

The peformance of the event handlers is key to keep the cache up to date.

**Comment by denkensk** [comment]
I also found that we repeatedly call `NewInfo` in `ClusterQueue` and `Queue` when `addOrUpdateWorkload`.  :)

> Unless we want to store other information, such as last scheduling attempt
Yes. will add last scheduling attempt timestamp. Can you provide a function to sync some old info to the new workload info if we want to call `NewInfo` in manager ？like check if exist and partly deep copy?

**Comment by alculquicondor** [comment]
We could add some "recalculate" method in Info that doesn't touch queueing data

**Comment by cmssczy** [comment]
I would like to work on it.
/assign

**Comment by kerthcet** [comment]
As we merged https://github.com/kubernetes-sigs/kueue/pull/257.
