### ISSUE TITLE
Add the possibility to define bucket sizes for kueue_admission_wait_time_seconds_bucket

### ISSUE THREAD

**Issue by woehrl01** [kubernetes-sigs/kueue#1622]
**What would you like to be added**:

It would be great if you could define the bucket sizes of the `kueue_admission_wait_time_seconds_bucket` metric

**Why is this needed**:

Currently the buckets are fixed to the following ranges:

![Bildschirmfoto 2024-01-19 um 18 16 11](https://github.com/kubernetes-sigs/kueue/assets/2535856/17f498ce-6b97-4f66-a8b9-63dd8d0ed628)

It shows that you only have a granularity of up to 10 seconds, which is way too short in our case. It can be that a job is queued for multiple minutes. They currently all end up in the `+inf` bucket.

It would be great if you could define those buckets, eg. as a arg to the commandline `prometheus-wait-time-buckets=1,5,10,60,120,360,+inf`

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
Uhmm... I think we choose the current buckets poorly. In most job queuing scenarios, anything under 100ms is probably useless.

I would be happy to accept a configuration option for this, but also to change the defaults to something more reasonable.

**Comment by woehrl01** [comment]
Fixed by having better default values via #1977
