### ISSUE TITLE
Add unit tests for pod group when there are errors on pod cleanup

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1636]
**What would you like to be cleaned**:

I would like to add unit tests demonstrating the handling of errors works properly in case of errors:
- https://github.com/kubernetes-sigs/kueue/blob/44adc22853fce5daf7f898a6bb3a17ccfb0a37bf/pkg/controller/jobs/pod/pod_controller.go#L757
- https://github.com/kubernetes-sigs/kueue/blob/44adc22853fce5daf7f898a6bb3a17ccfb0a37bf/pkg/controller/jobs/pod/pod_controller.go#L765

**Why is this needed**:

This is a follow up to https://github.com/kubernetes-sigs/kueue/pull/1623, needed to verify the lines for handling errors are needed, and work properly, preventing regressions in case of changes in this code.

More context here: https://github.com/kubernetes-sigs/kueue/pull/1623/files#r1463629651

**Comment by kaisoz** [comment]
/assign 

I think I can use this to learn more about the project. @alculquicondor please let me know if you don't find this one suitable for me 😊

**Comment by alculquicondor** [comment]
If @mimowo is willing to assist, yes

**Comment by mimowo** [comment]
> If @mimowo is willing to assist, yes

sure thing, @kaisoz  let stay in touch on slack if you have some questions or get blocked
