### ISSUE TITLE
Website does not have the correct trademark disclaimer

### ISSUE THREAD

**Issue by thisisobate** [kubernetes-sigs/kueue#1647]
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

**Comment by omerap12** [comment]
Ill take it
/assign

**Comment by mariasalcedo** [comment]
Hi @omerap12 , are you still working on this? If not, I am interested to take it over.

**Comment by omerap12** [comment]
Hey, sure you can take it :) @mariasalcedo

**Comment by mariasalcedo** [comment]
@thisisobate I've just sent a PR on this! 
This is my first ever contribution, so I look forward for your feedback, though there isn't much probably to be said.
