### ISSUE TITLE
Flaky E2E test for MultiKueue

### ISSUE THREAD

**Issue by B1F030** [kubernetes-sigs/kueue#1649]
/kind flake

**What happened**:
```
Internal error occurred: failed calling webhook "vclusterqueue.kb.io": failed to call webhook:
Post "https://kueue-webhook-service.kueue-system.svc:443/validate-kueue-x-k8s-io-v1beta1-clusterqueue?timeout=10s":
dial tcp 10.96.212.22:443: connect: connection refused
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1385/pull-kueue-test-e2e-main-1-28/1750699242197880832
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
cc: @trasc

**Comment by alculquicondor** [comment]
/close
in favor of #1658
