### ISSUE TITLE
A summary of Workloads order in queues

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#168]
**What would you like to be added**:

For a pending Workload, I would like to know how many pods are ahead of it.

Of course, this has to be in a best-effort fashion, but it could get pretty accurate in a cluster with lots of long running jobs.

However, this is not trivial to implement, as we use a heap, not a literal queue.

**Why is this needed**:

To provide some level of prediction to end-users for how long their workload will be queued.

**Comment by ahg-g** [comment]
Another concern is that for each update to the queue (new Workload added or removed), many Workloads statuses will need to be reconciled. This is expensive and can't be batched since the updates will need to be done for individual objects.

Perhaps we can update the `Queue` status with the order of the workloads, up to a specific limit. The order includes the workload name and its rank in the `ClusterQueue`.

**Comment by alculquicondor** [comment]
No progress yet. The exact number is hard to calculate or even keep accurate, depending on how fast jobs are being created. It might be easier to give a time estimate based on historical data?

Feel free to add proposals.

cc @mimowo

**Comment by maaft** [comment]
I mean the obvious solution would be to switch out the heap you mentioned for actual (distributed) queue(s). 

Out of curiosity, what were the reasons to use a heap data-structure when implementing a "kueue"? And what kind of heap are you using? Knowing this, I can better start to think about proposals.

**Comment by mimowo** [comment]
@maaft IIUC the complication with the proposal is that workloads are ordered by priority and creationTimestamp's: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/queue/cluster_queue_strict_fifo.go#L48-L58. So for a newly created workload with the highest priority the position will be `pos=1` (not `i-p`).

Two proposals from me (I suppose the ideas can be combined):
1. extend the kubectl describe command with the computed information. The on-the-fly computation could probably use the cache and would only happen on demand - when `kubectl describe` is invoked.
2. a dedicated CRD, say `WorkloadQueueOrder` which in the `Reconcile` loop would update its status with the workload order within a ClusterQueue, similarly as @ahg-g  suggested with the `Queue` status, but extract the information to a dedicated CRD to avoid conflicts with other BAU updates.

@alculquicondor @ahg-g @maaft WDYT?

**Comment by ahg-g** [comment]
@mimowo Which cache are you referring to?

**Comment by mimowo** [comment]
> @mimowo Which cache are you referring to?

The Kueue's server side cache. There is server-side printing: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns, but apparently it only allows to use `jsonPath` syntax to compute the value, so seems no go. I was hoping the API would allow to run custom code to compute the value.

**Comment by alculquicondor** [comment]
/close

Follow up split in https://github.com/kubernetes-sigs/kueue/issues/1657
