### ISSUE TITLE
Knobs to configure which jobs kueue manages

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#169]
**What would you like to be added**:

Currently, kueue takes over and suspends any Job in the system that is not admitted in a ClusterQueue.

**Why is this needed**:

There might be users in a cluster that are using the Job API for supporting services (like backups), instead of batch workloads. They would likely run in dedicated nodes that should not be subject to quotas.

Also, a custom workload might use a Job underneath, perhaps more than one. Once this custom workload is accepted as a whole, we don't want the Job to be queued as well.

**Open questions**:

- Should we just do it per namespaces?
- Can we use the namespace selectors from the ClusterQueues to decide? If the controller is re-starting, we might miss some.
- Is an annotation in the job enough? This would cover both use cases, but it could be used by a malicious user to bypass Kueue.

**Comment by ahg-g** [comment]
I think we want a `ConfigMap` that includes a namespace selector to configure the job controller with which namespaces to work on. Should be none by default.

**Comment by ahg-g** [comment]
https://github.com/kubernetes-sigs/kueue/pull/207 adds component config with a flag to control if kueue will manage jobs without queue name set; defaults to not managing them.

We should still add a namespace selector to component config to allow limiting kueue to managing jobs in a select subset of namespaces.

**Comment by ahg-g** [comment]
I feel that we do not yet need a namespace selector in component config, basing it on whether the queue-name is set is sufficient for now.
