### ISSUE TITLE
Only requeue workloads in cohort when space frees up

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1692]
**What would you like to be added**:

When something happens in the cluster that frees up space, like:
- Workload finishing
- Workload partial reclaim
- ClusterQueue resize,

only requeue the Workloads that are in the same cohort as the event

**Why is this needed**:

This would avoid unnecessary admission attempts for Workloads that don't fit.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
Oops, this is actually what is currently implemented https://github.com/kubernetes-sigs/kueue/blob/892d85c35a94c875005d6b547710ad06704bccf9/pkg/queue/manager.go#L371-L377

**Comment by Bharadwajshivam28** [comment]
Hey @alculquicondor I can try it but I need some steps to get started

**Comment by tenzen-y** [comment]
@alculquicondor As I checked [this comment](https://github.com/kubernetes-sigs/kueue/issues/1692#issuecomment-1929726356), this had already completed, right?
