### ISSUE TITLE
Replicate ExtendedResourceToleration

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#170]
**What would you like to be added**:

Through the [ExtendedResourceToleration admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#extendedresourcetoleration) kubernetes automatically adds tolerations to pods requesting custom resources.

If a workload uses extended resources that match the ones set by the admission controller and the ClusterQueue has a taint for it, the workloads would be inadmissible.

**Why is this needed**:

Not sure if we actually need it. Maybe it's not a good practice for users to use these taints in their ResourceFlavors?

**Comment by ahg-g** [comment]
> If a user sets tolerations for extended resources that match the ones set by the admission controller, the workloads would be inadmissible.

Not sure I understand this, why it will be inadmissible?

**Comment by alculquicondor** [comment]
To clarify why this might not be a valid use case:

A flavor should have taints for a resource model, not the resource itself.

For example, in GKE, Pods can have the following nodeSelector to match a particular GPU model:

```yaml
cloud.google.com/gke-accelerator: nvidia-tesla-k80
```

Whereas the name of the resource itself is `nvidia.com/gpu`. Flavors shouldn't have a taint against this model.

But if someone has a use-case that I'm missing, we can probably add this feature as an option.

/triage needs-information
