### ISSUE TITLE
Cherry-picker should copy release notes

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1715]
**What would you like to be added**:

Copy release notes into the cherry-pick PR.

**Why is this needed**:

To simplify the release process.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by trasc** [comment]
@alculquicondor  in the recent generated PRs , with the exception of #1704 case in which the source PR  #1666 where the description has no `release-note` block,  the release notes are copied. Am I missing something?

**Comment by alculquicondor** [comment]
I copied them manually

**Comment by trasc** [comment]
> I copied them manually

It's strange, the implementation is in-place https://github.com/kubernetes/test-infra/blob/6d0a63230e80cf0138f83a65086f12d441756eb3/prow/external-plugins/cherrypicker/server.go#L46.

**Comment by alculquicondor** [comment]
uhm... then maybe it was only for the cherry-picks done with the script in `/hacks`

**Comment by trasc** [comment]
That one has indeed an hard-coded empty release note.

https://github.com/kubernetes-sigs/kueue/blob/4c1c6d67a3344fff3512d76b46c70aaac0bae2f5/hack/cherry_pick_pull.sh#L147-L149

**Comment by alculquicondor** [comment]
Uhm... this code seems to point out that it indeed looks at parent PRs https://github.com/kubernetes/release/blob/355b4aad5b3593b7aa0764fe5b166660bfbdd686/pkg/notes/notes.go#L1048

**Comment by alculquicondor** [comment]
I'll pay some attention next time I do a release to understand what I was doing wrong.

/unassign trasc

**Comment by alculquicondor** [comment]
/assign trasc
Based on comments in https://github.com/kubernetes/test-infra/issues/31929

**Comment by trasc** [comment]
With kubernetes/release#3468 the defaulting to the original PR's release note if not present in the current one should work for both cherry-pick methods (bit an hack script) regardless of merge method used.
