### ISSUE TITLE
Expose an eviction / re-queue related prometheus metric

### ISSUE THREAD

**Issue by astefanutti** [kubernetes-sigs/kueue#1741]
**What would you like to be added**:

A Prometheus metric that exposes the number of evicted / inactive workloads, per cluster queue, and per eviction reasons, e.g., preempted, readiness timeout, admission check down, become inactive, or cluster queue stopped.

**Why is this needed**:

The `pending_workloads` metric exposes the current number of pending workloads that are either active or inadmissible, but does not provide any finer-grained visibility to monitor eviction / re-queuing. 

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
oh, big +1

Are you suggesting 2 metrics? One for eviction and one for requeue?

**Comment by astefanutti** [comment]
My current thinking is:
* One metric for eviction, with a reason label, e.g.:
    ```
    prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "evicted_workloads",
		},
		[]string{"cluster_queue", "reason"},
	)
    ```
* Maybe, one metric for re-queuing attempts, like an histogram with the number of attempts, e.g.:
    ```
    prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:           "workload_requeueing_attempts",
			Buckets:        metrics.ExponentialBuckets(1, 2, 5),
		},
		[]string{"cluster_queue", "attempts"},
	)
    ```
* Should _inactive_ workloads, either by manual deactivation or exceeding re-queueing backoff limit, be also observed? If yes, what would be the best approach? Would adding an `inative` label to the `pending_workloads` make sense?

**Comment by astefanutti** [comment]
> > Maybe, one metric for re-queuing attempts, like an histogram with the number of attempts.
> 
> I'm not sure what you propose to record: how many attempts we did before admitting a workload?
> 
> If it is just the number of requeues, then shouldn't it be a counter?

More the distribution, by number of attempts / re-queue count, of workloads that are currently being evicted and pending re-enqueue, waiting for the backoff duration. Does that make sense?

**Comment by alculquicondor** [comment]
I'm not sure that's how a histogram works. Once you call `Observe`, there is no taking back, that is, when the workload is admitted.

Are you thinking more of a combination of a histogram and a gauge?

**Comment by astefanutti** [comment]
Right, I see what you mean. A histogram samples observations as these are made (not the state at a point in time), so that'd be more the re-queuing events that'd be observed.

So that'd indeed be closer to what you've said, the re-enqueued workloads, distributed by the number of previous attempts, but I'm not sure if that's the right approach.

Yet I still think having a metric that'd make the number of accrued attempts visible (one way or another) would be useful for the "understandability" of the system behavior.

**Comment by alculquicondor** [comment]
I'm open to other suggestions, but if the usability isn't clear, we can leave it for later.

**Comment by astefanutti** [comment]
Agreed, a metric for eviction alone would be a good improvement.
