### ISSUE TITLE
Introduce the docsy style Note

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1755]
**What would you like to be cleaned**:
It would be better to replace a simple markdown style Note with the docsy style shortcode.

The sample of Docsy style: https://github.com/kubernetes-sigs/kueue/blob/main/site/content/en/docs/tasks/setup_sequential_admission.md#enabling-waitforpodsready

**Why is this needed**:
The shortcode could be emphasize the Notes.

/kind documentation

**Comment by alculquicondor** [comment]
Is the ask to go through all of the documentation and find the cases where we are not using a Docsy alert when it would be useful?

**Comment by tenzen-y** [comment]
> Is the ask to go through all of the documentation and find the cases where we are not using a Docsy alert when it would be useful?

I meant the I would propose to replace the GitHub style Notes with Docsy style once:

GitHub Style: https://github.com/kubernetes-sigs/kueue/blob/0db23a7d8431b25ea77281fc6b7504db247c34dc/site/content/en/docs/installation/_index.md?plain=1#L149-L151

Doccy Style: https://github.com/kubernetes-sigs/kueue/blob/0db23a7d8431b25ea77281fc6b7504db247c34dc/site/content/en/docs/tasks/manage/setup_sequential_admission.md?plain=1#L53-L61
