### ISSUE TITLE
Cleanup Failed pods once replacement Pods are present

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1762]
**What would you like to be added**:

Cleanup Failed pods once there is a level of confidence that replacement Pods exist and the Workload object wouldn't be garbage collected.

We need to be mindful of possible race conditions that could end up finalizing all Pods too early. Integration and E2E tests are a must. 

**Why is this needed**:

Keeping the terminated pods was a conscious design decision for pod groups for a first implementation https://github.com/kubernetes-sigs/kueue/tree/main/keps/976-plain-pods

However, in a busy system where lots of preemptions could happen, the unfinalized pods could cause unnecessary load in the etcd+apiserver.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc: Update KEP with the proposed design
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kannon92** [comment]
A relevant upstream issue that could be a good long term solution: https://github.com/kubernetes/kubernetes/issues/122187

**Comment by alculquicondor** [comment]
Not related. Whatever k/k does, it shouldn't get in the way of finalizers, which we are using here.
