### ISSUE TITLE
A mechanism to list the Workloads that are admitted and not finished

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1776]
**What would you like to be added**:

Some way of querying the list of Workloads that are still "running", that is, they are admitted and don't have a Finished condition. Querying by ClusterQueue would be ideal too.

Some options (not necessarily exclusive to each other):
- The kueue CLI
- A visibility endpoint.
- Is there a way to do this just with a kubectl jsonpath?

**Why is this needed**:

For basic diagnostics of the state of the cluster.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change?
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
Do you expect that we extend the on-demand visibility server or save information on any CustomResource like ClusterQueue?

**Comment by alculquicondor** [comment]
I don't think we should save it. This is more for on-demand queries.

**Comment by tenzen-y** [comment]
> I don't think we should save it. This is more for on-demand queries.

It makes sense.

**Comment by astefanutti** [comment]
Tangentially, do you think adding a `running_worloads` metric could be useful too?

**Comment by tenzen-y** [comment]
> Tangentially, do you think adding a `running_worloads` metric could be useful too?

Does it mean Prometheus metric?

**Comment by astefanutti** [comment]
> > Tangentially, do you think adding a `running_worloads` metric could be useful too?
> 
> Does it mean Prometheus metric?

Yes, a Prometheus metric, that would complement the existing `pending_workloads` metric.

**Comment by alculquicondor** [comment]
we already have it https://github.com/kubernetes-sigs/kueue/blob/9afd7e6aadd49e2c44fcafb67b11cf78c5d751ae/pkg/metrics/metrics.go#L120-L126

**Comment by astefanutti** [comment]
> we already have it
> 
> https://github.com/kubernetes-sigs/kueue/blob/9afd7e6aadd49e2c44fcafb67b11cf78c5d751ae/pkg/metrics/metrics.go#L120-L126

Ah right, this is the one, thanks!

**Comment by alculquicondor** [comment]
Would you like to propose something for this area?

**Comment by astefanutti** [comment]
Yes. Do you want it to be initially proposed as a KEP?

**Comment by alculquicondor** [comment]
Given that it's an API change, a KEP would be good.

**Comment by tenzen-y** [comment]
Feel free to assign yourself with `/assign`.
Since you joined this org, the command should work well :)

**Comment by KunWuLuan** [comment]
If no one working for this, I can help.

**Comment by astefanutti** [comment]
@KunWuLuan I haven't got the chance to work on it. Feel free to assign it to you.

**Comment by KunWuLuan** [comment]
Do we still need the new endpoints if we already have the KueueCtl?

**Comment by alculquicondor** [comment]
Maybe less so? One slight advantage would be to filter on the server side.

But maybe it would add unnecessary load to the kueue binary?
