### ISSUE TITLE
Flaky integration test "RayCluster Job controller interacting with scheduler Should schedule jobs as they fit in their ClusterQueue"

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1829]
/kind flake

**What happened**:

The test failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1827/pull-kueue-test-integration-main/1767837105611870208.

**What you expected to happen**:

The test should pass consistently.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure, probably repeat the test.

**Anything else we need to know?**:

It failed on PR not related to this test. Passed after retry.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
cc @andrewsykim @vicentefb

**Comment by tenzen-y** [comment]
This happened: https://github.com/kubernetes-sigs/kueue/pull/1838
