### ISSUE TITLE
Copy some labels from Pods/Jobs into the Workload object

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1834]
**What would you like to be added**:

The ability to copy the labels from a Job or Pod (when using pod groups) into the Workload object.

This can be configurable through the configuration API, so that we don't necessarily copy every label.

**Why is this needed**:

This improves the UX for administrators, when trying to list groups of Workloads.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
> It's worth having a mention of this feature in the documentation for Workload.

I think that opening this issue would be better to avoid forgetting docs.
/reopen

**Comment by alculquicondor** [comment]
@pajakd can your write `/assign` in a comment?

**Comment by alculquicondor** [comment]
Fixed by #1959

/close

**Comment by tenzen-y** [comment]
@alculquicondor @pajakd Actually, we have never seen documentation for this feature, right?
So, could you add documentation?

/reopen

**Comment by pajakd** [comment]
@tenzen-y I assumed that documentation of field `LabelKeysToCopy` here: https://pkg.go.dev/sigs.k8s.io/kueue@v0.7.0/apis/config/v1beta1#Integrations is sufficient. Should I add something more?

**Comment by alculquicondor** [comment]
Maybe a quick mention in the Workload page.

**Comment by tenzen-y** [comment]
> Maybe a quick mention in the Workload page.

Yes, that is my assumption.
@pajakd Could you open a PR?

**Comment by pajakd** [comment]
Sure, sorry for the delay: https://github.com/kubernetes-sigs/kueue/pull/2558

**Comment by tenzen-y** [comment]
resolved by #2558
