### ISSUE TITLE
Move logic to evict on Workload deactivation to the Workload controller

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1841]
**What would you like to be cleaned**:

The logic is currently in the job reconciler:
https://github.com/kubernetes-sigs/kueue/blob/a96927de470d985f17b03a328c33bb8547eae9a4/pkg/controller/jobframework/reconciler.go#L422-L429

**Why is this needed**:

1. The logic is fully independent of the job
2. If an integration decides not to use the job reconciler framework, they would have to re-implement this logic.

**Comment by tenzen-y** [comment]
> kueue/pkg/controller/jobframework/reconciler.go

I sought https://github.com/kubernetes-sigs/kueue/pull/1252, but I could not find any reasonable reason to put this logic on the job framework-controller.

So, I'll try to move it to the workload-controller.
