### ISSUE TITLE
Backfilling when provisioningrequest adds nodes to the cluster

### ISSUE THREAD

**Issue by asm582** [kubernetes-sigs/kueue#1871]
**What would you like to be added**: A mechanism to submit queued jobs/workloads on the newly added available nodes in the cluster while the scale up completes for the previous job via provisioningrequest.  

**Why is this needed**: We block quota and later acquire resources in some what sequential fashion from cloud provider, not using newly added resources for queued jobs will lead to resource wastage and decrease in cluster throughput.

**Completion requirements**: New preemption policy may be needed to force terminate already existing running backfilled jobs on the newly acquired nodes.

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
I think a better approach is if the cloud provider gives some form of atomicity when doing scale ups.

What you are proposing sounds very problematic. How do you express that a job is ok to run in nodes provisioned for some other job? When/how to do preemption?

Do you have a more specific proposal?
