### ISSUE TITLE
Distinguish between preemption within ClusterQueue, reclaim within Cohort and preemption with borrowing

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1874]
**What would you like to be added**:

Preemption in Kueue can happen due to the following reasons:

- Within a Cluster Queue, due to an incoming Pod with higher priority
- Within a Cohort, to reclaim quota
- Within a Cohort, due to preemption with borrowing, because the preempted workload is below a threshold.

We need to enhance the Condition reason and messages to incorporate this information.

**Why is this needed**:

For users to better understand why Kueue preempted their Jobs.

Administrators might want to aggregate information for multiple preemptions, so ideally the Reason should be different, with a common prefix.
A potential problem is to break users that already depend on the `Preempted` reason to identify preemptions. Perhaps highlighting the breaking change should be enough in the release notes.

We can also incorporate the information in a metric label.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
cc @tenzen-y @astefanutti @kerthcet wdyt of the breaking change?

**Comment by astefanutti** [comment]
+1 not maintaining backward compatibility is OK on our side.

I think that relates to #1741 for the metrics part.

**Comment by alculquicondor** [comment]
Actually, the current state could be considered buggy, because the message in the Evicted condition always says: "Preempted to accommodate a higher priority Workload".

So at the very least we can start by distinguishing the message.

**Comment by tenzen-y** [comment]
@alculquicondor, I agree with making UX better.
And I'm ok with these breaking changes. I my side, we expose such reasons via our gRPC API. So, I can just modify the internal Server logic.

But, I think we need to announce this change as breaking in RELEASE NOTE and release announcement in google groups.

**Comment by alculquicondor** [comment]
Yes, we can put `ACTION REQUIRED` in the notes to highlight at the top.

**Comment by mimowo** [comment]
+1. The current message is misleading because when `reclaimWithinCohort: Any` then a workload might get preempted by a lower priority workload actually.

I'm not sure using `reason` for this purpose is the right way. Currently we have 3 modes of preemption, we are likely to have more in the future, for example, if fair sharing is implemented. 

I'm thinking about enriching the message, similarly as we build the events in the [k8s scheduler](https://github.com/kubernetes/kubernetes/blob/227c2e7c2b2c05a9c8b2885460e28e4da25cf558/pkg/scheduler/framework/preemption/preemption.go#L390).

We could have a message like: `Preempted to accommodate the "UID-x" workload  submitted to the "team-y" ClusterQueue."

**Comment by alculquicondor** [comment]
The thing is that messages are not machine-readable. For direct users of Kueue, messages are acceptable. But if you use kueue as a low-level component, then you might need a reason to distinguish between the different kinds of preemption.

The reasons having a common prefix could be good enough to group them as one thing with different variants.

Btw, in fair sharing, the preemption reason would still be PreemptDueToReclaim (or something similar). It's just that the "reclamation thresholds" are dynamic.

**Comment by mimowo** [comment]
>  The thing is that messages are not machine-readable. 

I see, so maybe instead we have an extra condition type `Preempted`, with a dedicated reason. So we have 2 conditions:
```yaml
- type: Evicted
  reason: Preempted
  message: preempted to accomodate workload UID
- type: Preempted
  reason: ReclaimWithinCohort / PreemptionWithinClusterQueue / FairSharingWithinCohort ... 
  message: preempted to accomodate workload UID # possibly some more data here 
```

> For direct users of Kueue, messages are acceptable. But if you use kueue as a low-level component, then you might need a reason to distinguish between the different kinds of preemption.

Yes, but then when a new reason is added by Kueue, then the external system also needs to be extended for monitoring, when a new version of Kueue introduces a new reason. I guess we could mitigate this by some convention, say all reasons start with "PreemptedDueTo".

**Comment by alculquicondor** [comment]
I like the idea of a dedicated Preempted condition. It's fully backwards compatible. We just need to make sure that the documentation makes a distinction between the two conditions (or that one is a subset of the other).

**Comment by astefanutti** [comment]
A separate Preempted condition looks like a good solution, bringing better structure maintaining backward compatibility.

**Comment by tenzen-y** [comment]
+1 on having the `Evicted` and the `Preempted` condition type.
Also, we may need to clarify what the difference is between Preemption and Eviction in the documentation.

**Comment by alculquicondor** [comment]
If we can make the distinction between the two, that would be better IMO.

End users might have access to the preemption condition, but they might not have access to the names or priorities or other workloads. But they still would want to know roughly why they were preempted.

A nit on `PreemptionInClusterQueue`: It shouldn't start with preemption, because that's already the name of the condition. But maybe we can say `HigherPriorityWithinClusterQueue`. And similarly `UnderPriorityThresholdForPreemptionWithBorrowing` (I'm open to ideas for a shorter version).

**Comment by mimowo** [comment]
From the offline discussions we want to balance two aspects: satisfy the MVP which distinguishes "In ClusterQueue" and "In cohort", and being as granular as possible.

I think there will always be a possibility, that a new config option or threshold is introduced, making the reason to split into two or more detailed reasons.

In that case, I would suggest to start with something simple for now, two reasons: `InClusterQueue` and `InCohort`. Then, we say that reasons prefixed by them are meant to provide more detailed information. So, in the future we may have:
`InClusterQueueByHigherPriorityWorkload` or `InCohortByBorrowingWorkload`, etc.
