### ISSUE TITLE
Pending event should include information of which resource didn't have enough quota

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#189]
**What would you like to be added**:

The current message says "Workload didn't fit in the remaining quota" with no indication of which resource doesn't fit, which flavors were tried, which ones are under `min` (this is possible because there is no preemption).

**Why is this needed**:

Improves UX and allows users and administrators to understand which quotas might need to be revisited.

**Comment by ahg-g** [comment]
We should also breakdown the reason by flavor, which may not fit because of:
1. no quota
2. untolerated taint 
3. non-matching affinity.
