### ISSUE TITLE
Flaky integration test for RayJob

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1943]
**What happened**:

```
RayJob Controller Suite: [It] Job controller with preemption enabled Should preempt lower priority rayJobs when resource insufficient expand_less	20s
{Timed out after 5.001s.
Expected
    <bool>: true
to be false failed [FAILED] Timed out after 5.001s.
Expected
    <bool>: true
to be false
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/controller/jobs/rayjob/rayjob_controller_test.go:735 @ 04/03/24 17:48:18.402
}
```

**What you expected to happen**:

No flakiness

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1777/pull-kueue-test-integration-main/1775579633484304384

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

It is possible that somehow our new timeout (5s) is too aggressive and we might want to increase it back 10s.

But it's worth investigating if something else could be going on.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment]
/repoen
In case we see it again. 
https://github.com/kubernetes-sigs/kueue/pull/1951#issuecomment-2040260375

**Comment by alculquicondor** [comment]
It looks like we haven't seen this again
/close
