### ISSUE TITLE
Does ClusterQueueFromLocalQueue need lock?

### ISSUE THREAD

**Issue by lowang-bh** [kubernetes-sigs/kueue#1954]
**What happened**:

As code shows, it does not lock and unlock when calling `ClusterQueueFromLocalQueue`.

```go
func (m *Manager) ClusterQueueFromLocalQueue(lqName string) (string, error) {
	if lq, ok := m.localQueues[lqName]; ok {
		return lq.ClusterQueue, nil
	}
	return "", errQueueDoesNotExist
}
```
**What you expected to happen**:
May be it need to lock first.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): master branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment]
In my opinion yes, but maybe @PBundyra know more about the subject, also it can help to merge the functionality with the one of `func (m *Manager) ClusterQueueForWorkload(wl *kueue.Workload) (string, bool) `.
