### ISSUE TITLE
[metrics] Add Kueue scheduler preemption metrics

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1962]
**What would you like to be added**:

Currently, there are no Scheduler metrics for preemption. 

Proposed metrics:
- `PreemptedWorkloadsTotal` (counter by analogy to `AdmittedWorkloadsTotal`)
- `PreemptionAttemptsTotal`     (counter by analogy to the kube-scheduler metric  [PreemptionAttempts](https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/scheduler/metrics/metrics.go#L95-L101)

**Why is this needed**:

This is inspired by the scalability tests in https://github.com/kubernetes-sigs/kueue/issues/1912. 

We need some observability for Job-level preemptions by Kueue.

**Comment by alculquicondor** [comment]
> PreemptedWorkloadsTotal

This one is being added in #1955

> PreemptionAttemptsTotal

This could be useful to understand the performance.

> SchedulingCycleDuration

We have `admission_attempt_duration_seconds`. But we might want to add some granularity for certain steps (like preemption calculation).

**Comment by tenzen-y** [comment]
> > PreemptedWorkloadsTotal
> 
> This one is being added in #1955
> 
> > PreemptionAttemptsTotal
> 
> This could be useful to understand the performance.
> 
> > SchedulingCycleDuration
> 
> We have `admission_attempt_duration_seconds`. But we might want to add some granularity for certain steps (like preemption calculation).

SGTM

**Comment by mimowo** [comment]
I'm hesitant regarding `PreemptionAttemptsTotal`. It will be mostly redundant to EvictedWorkloads[reason=Preempted], but maybe useful if the preemption attempts are retried continously.

**Comment by mimowo** [comment]
/close
Let's close for now, as the original plan is mostly covered as per https://github.com/kubernetes-sigs/kueue/issues/1962#issuecomment-2050369243
