### ISSUE TITLE
Add ClusterQueue and Queue Metrics

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#199]
**What would you like to be added**:

Metrics to track:
1. [x] Queue/ClusterQueue pending workloads (gauge) 
2. [x] Queue/ClusterQueue admitted workloads (gauge) 
3. [x] Admission cycle latency (histogram)
4. [ ] Workload waiting time in the queue (histogram)

what else?

**Comment by alculquicondor** [comment]
Oops, I forgot to put my name on this. I was already working on it. I hope you don't mind @kerthcet?

**Comment by kerthcet** [comment]
Plz go ahead.

**Comment by kerthcet** [comment]
I have nearly finished the `Queue/ClusterQueue pending workloads (gauge)`, some tests left. if you haven't work on this one, I can finish this one to prevent redundant works.

**Comment by ahg-g** [comment]
Aldo, I guess the following represents progress on this issue, correct?

1. [x] Queue/ClusterQueue pending workloads (gauge) 
2. [x] Admission cycle latency (histogram)
3. [ ] Queue/ClusterQueue admitted workloads (gauge) 
4. [ ] Workload waiting time in the queue (histogram)

**Comment by alculquicondor** [comment]
correct, thanks

**Comment by ahg-g** [comment]
@alculquicondor are you planning to add workload waiting time?
