### ISSUE TITLE
[metrics] Add `admission_check_wait_time` metric

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1994]
**What would you like to be added**:

A new histogram metric `admission_check_wait_time`. The metric has the `controller_name` label to discriminate between different types of admission checks.

**Why is this needed**:

The metric will allow administrators how long workloads wait for different admission checks, depending on their type (controller).

**Completion requirements**:

Aside from the implementation update the docs: https://kueue.sigs.k8s.io/docs/reference/metrics/.

**Comment by kaisoz** [comment]
I can take this one 😊 

/assign

**Comment by mbobrovskyi** [comment]
@kaisoz Is it still in progress?

**Comment by kaisoz** [comment]
> @kaisoz Is it still in progress?

@mimowo and I talked about this one on Slack and decided to put on hold for now because there's already a metric which is quite similar. He was going to open a discussion and come back to me.

**Comment by mimowo** [comment]
That's right, I'm not sure about the benefits of this metric since we already have: https://github.com/kubernetes-sigs/kueue/blob/e8e0810115f3bef7518b4c07eb4c2e2579660060/pkg/metrics/metrics.go#L128C2-L135.
The benefit is more granular, but most of the time our users still have only one AdmissionCheck - MultiKueue or ProvisioningRequest. Another benefit could be to introduce the `result` label which could have values `failed`, and `success` to indicate the result per admission check. Then, an admin could see how long it takes for ProvisioningRequests to fail / provision. 

On the implementation level we have two choices: 
1. use `workload_controller` [update handler](https://github.com/kubernetes-sigs/kueue/blob/e8e0810115f3bef7518b4c07eb4c2e2579660060/pkg/controller/core/workload_controller.go#L621) and measure the time it took from `Pending` to `Rejected`, `Retry` (for failed), or `Ready` for success
2. set the metric it per admission check, in case of ProvReq, after the update [here](https://github.com/kubernetes-sigs/kueue/blob/e8e0810115f3bef7518b4c07eb4c2e2579660060/pkg/controller/admissionchecks/provisioning/controller.go#L511-L513)

I would be leaning towards (1.) as this would work OOTB for external admission checks. A potential downside is that the metric would get counted for non-leading replicas, but we aren't strict about it anyway.

@tenzen-y @alculquicondor any opinion? Do you think its benefits (more granular, and `result` label) outweight the extra complexity? I would be in favor of adding it.

**Comment by alculquicondor** [comment]
Let's close this one for now.

We have enough information for most use cases with the existing metric.

**Comment by tenzen-y** [comment]
> That's right, I'm not sure about the benefits of this metric since we already have: https://github.com/kubernetes-sigs/kueue/blob/e8e0810115f3bef7518b4c07eb4c2e2579660060/pkg/metrics/metrics.go#L128C2-L135. The benefit is more granular, but most of the time our users still have only one AdmissionCheck - MultiKueue or ProvisioningRequest. Another benefit could be to introduce the `result` label which could have values `failed`, and `success` to indicate the result per admission check. Then, an admin could see how long it takes for ProvisioningRequests to fail / provision.
> 
> On the implementation level we have two choices:
> 
> 1. use `workload_controller` [update handler](https://github.com/kubernetes-sigs/kueue/blob/e8e0810115f3bef7518b4c07eb4c2e2579660060/pkg/controller/core/workload_controller.go#L621) and measure the time it took from `Pending` to `Rejected`, `Retry` (for failed), or `Ready` for success
> 2. set the metric it per admission check, in case of ProvReq, after the update [here](https://github.com/kubernetes-sigs/kueue/blob/e8e0810115f3bef7518b4c07eb4c2e2579660060/pkg/controller/admissionchecks/provisioning/controller.go#L511-L513)
> 
> I would be leaning towards (1.) as this would work OOTB for external admission checks. A potential downside is that the metric would get counted for non-leading replicas, but we aren't strict about it anyway.
> 
> @tenzen-y @alculquicondor any opinion? Do you think its benefits (more granular, and `result` label) outweight the extra complexity? I would be in favor of adding it.

I'm fine without this metric. Once we find any situations where we want to make it more granular, we can revisit here.
