### ISSUE TITLE
introduce priorityFIFO as another QueueingStrategy of ClusterQueue

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#200]
**What would you like to be added**:
Introduce another queue whose elements are ordered by the workload priority.
**Why is this needed**:
It's a general requirement as in kube-scheduler. We do have priority field introduced in Workload.

**Comment by kerthcet** [comment]
Well, I found @denkensk has already finished part of the feature https://github.com/kubernetes-sigs/kueue/pull/104, do you still working on the rest part?

**Comment by denkensk** [comment]
The workloads are already sorted by the priory. It's the default strategy.

**Comment by kerthcet** [comment]
got it.
