### ISSUE TITLE
Use k8s v1.30.0

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#2004]
**What would you like to be added**:

Use k8s v1.30.0

**Why is this needed**:

- Stay up to date with k/k
- Make use of the `batch.Job`  `spec.managedBy` field in MultiKueue

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kannon92** [comment]
And probably kind needs to be released with 1.30.

https://hub.docker.com/r/kindest/node/tags

**Comment by trasc** [comment]
Controller runtime v0.18 is out, now we wait for `github.com/open-policy-agent/cert-controller`.

**Comment by tenzen-y** [comment]
> github.com/open-policy-agent/cert-controller

@trasc FYI: https://github.com/open-policy-agent/cert-controller/pull/202

**Comment by trasc** [comment]
> open-policy-agent/cert-controller#202

Looks like k/k 1.30.1 is out so maybe we'll have some progress on this in the near future.
