### ISSUE TITLE
[Flaky] Preemption In a cohort with StrictFIFO Should reclaim from cohort even if another CQ has pending workloads

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2020]
**What happened**:

Flaky integration test `Preemption In a cohort with StrictFIFO Should reclaim from cohort even if another CQ has pending workloads`

```
{Timed out after 5.000s.
Not enough workloads are pending
Expected
    <int>: 1
to equal
    <int>: 2 failed [FAILED] Timed out after 5.000s.
Not enough workloads are pending
Expected
    <int>: 1
to equal
    <int>: 2
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/scheduler/preemption_test.go:536 @ 04/18/24 21:15:44.15
}
```

**What you expected to happen**:

Not to flake

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2002/pull-kueue-test-integration-main/1781067120407220224

I think I saw it again in a different PR as well.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mimowo** [comment]
/assign
I have a local repro. It seems only a test issue.
