### ISSUE TITLE
[MultiKueue] Report ClusterQueue as inactive (misconfigured) if not applied to all flavors

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2021]
**What would you like to be added**:

Fail validation for ClusterQueue in case the MultiKueue admission check is configured only for a subset of flavors. 
This can be now done with a similar mechanism to this: https://github.com/kubernetes-sigs/kueue/issues/1913. 

**Why is this needed**:

The managedBy field is immutable, so we cannot change it per flavor. 
To fail fast and avoid debugging of customer issues when using MultiKueue for a subset of flavors.

**Proposed approach**

A mechanism similar to this one: https://github.com/kubernetes-sigs/kueue/pull/1635

**Comment by alculquicondor** [comment]
as a clarification: an admission check applies to all flavors if the list in `onFlavors` is empty.
