### ISSUE TITLE
Fix transitions of Requeued condition

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2038]
The `Requeued` condition should transition to `False` in the following scenarios:

- When workload.spec.active=false. It should return to True when it's reactivated.
- When evicted due to WaitForPodsReady, the workload will temporarily be in backoff. During this time, Requeued should be false.

As per [comment](https://github.com/kubernetes-sigs/kueue/pull/1977#discussion_r1574949456).

**Comment by alculquicondor** [comment]
Also, once the transitions are fixed, we can use the timestamp of the `Requeued` condition for scheduling sorting.

**Comment by alculquicondor** [comment]
One thing to keep in mind regarding the transition after backoff:
Currently, the backoff is acted on in the event handlers. This is fine, as it's a quick in-memory operation.
OTOH, doing an API update within an event handler is not acceptable. So the update needs to happen somewhere inside the `Reconcile` method.

If you wanna bounce some ideas of how to get that implemented, feel free to reach out to me or @mimowo over slack.
