### ISSUE TITLE
Fix logging of the workload status when using admission checks

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2039]
**What happened**:

When ProvReq admission check is used, and it is in the QuotaReserved state, then the workload controller logs that it is already admitted, which is misleading. 

The produced logs look similar to:
```
{"caller":"core/workload_controller.go:507", "clusterQueue":"dws-cluster-queue", "level":"Level(-2)", "logger":"workload-reconciler", "msg":"Workload update event", "prevStatus":"pending", "queue":"dws-local-queue", "status":"admitted", "workload":{…}}
```

**What you expected to happen**:

Log properly when the workload is in the QuotaReserved, and when in the Admitted status.

**How to reproduce it (as minimally and precisely as possible)**:

Create a workload with a ProvReq and check the logs when the workload is waiting for provisioning of the request.

**Anything else we need to know?**:

Here is the code: https://github.com/kubernetes-sigs/kueue/blob/92baacd06e54f57de85a15590a1780eb84455941/pkg/controller/core/workload_controller.go#L677-L679.

**Comment by mbobrovskyi** [comment]
@mimowo Looks like it's already fixed.

https://github.com/kubernetes-sigs/kueue/blob/main/pkg/workload/workload.go#L69-L74

```
{"workload": {"name":"wl","namespace":"provisioning-5v2pn"}, "queue": "queue", "status": "quotaReserved", "prevStatus": "pending", "clusterQueue": "cluster-queue"}
```

**Comment by mimowo** [comment]
You are correct. We can close it
