### ISSUE TITLE
Add default queue name for not configured workload

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#208]
**What would you like to be added**:
Currently we construct workload in https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/workload/job/job_controller.go#L402-L418, but job's queue name might be empty. we should verify this or add a default one.

**Why is this needed**:

**Comment by alculquicondor** [comment]
Queues are namespaced, so there is no "default" queue that would apply to all workloads.

**Comment by ahg-g** [comment]
Also, if the admin wishes to set defaults, it should happen on object creation via a webhook or policy agent.

/close

**Comment by alculquicondor** [comment]
`r.manageJobsWithoutQueueName` is doing what you say. If it's true, the entire conditional is true and the rest of kueue's job controller runs, effectively "taking over".
