### ISSUE TITLE
Add priority to LocalQueue

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/kueue#2101]
**What would you like to be added**:
We would like to add priority to LocalQueue.

**Why is this needed**:
We have a need to introduce 2 dimensions of priority/preemption. Here is an example:

- We have 2 types of workloads (A & B)
- A should always preempt B
- We also want ordering within A
- We have an indefinite number of workload types where we don't want to statically define say 4 priorities (Ex: A-high-priority, A-low-priority, B-high-priority, B-low-priority)
- So with the following submission order (Where A preempts all B): (A, workload priority 0) (B, 100) (A,100) (B,0) -> Queue order should be: (A,100) (A, 0) (B, 100) (B, 0)

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
This is duplicated with #752 
/close
