### ISSUE TITLE
[kueuectl] Add list LocalQueue command

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#2115]
**What would you like to be added**:
Add list LocalQueue command.

**Why is this needed**:
To get list LocalQueues that match the given criteria: point to a specific CQ, being active/inactive, belonging to the specified namespace or matching the label selector.

Design details https://github.com/kubernetes-sigs/kueue/tree/main/keps/2076-kueuectl#list-localqueue.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@mbobrovskyi Could you track all commands by https://github.com/kubernetes-sigs/kueue/issues/2076?
