### ISSUE TITLE
It seems like the wrong function is being used when a multiKueueCluster is created

### ISSUE THREAD

**Issue by leprode** [kubernetes-sigs/kueue#2117]
**What happened**:
when a multiKueueCluster is created, the function named **queueReconcileForConfigUsers** is used directly in admissioncheck.go#L270

**What you expected to happen**:
the function named **queue**(admissioncheck.go#L313) should be used, then the function named **queueReconcileForConfigUsers** used in queue function.

**How to reproduce it (as minimally and precisely as possible)**:
when a multiKueueCluster is created

**Anything else we need to know?**:
https://github.com/kubernetes-sigs/kueue/blob/43e5eb8ee19fe69d3dd3f03c13f4ad46b77dd094/pkg/controller/admissionchecks/multikueue/admissioncheck.go#L264-L273

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment]
Thanks @leprode 

/assign
