### ISSUE TITLE
[kueuectl] Add stop LocalQueue command

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#2139]
**What would you like to be added**:
Add stop LocalQueue command.

**Why is this needed**:
To stops execution (or just admission) of Workloads coming from the given LocalQueue. This requires adding StopPolicy to LocalQueue and enforcing its changes in ClusterQueue (#2109).

Design details https://github.com/kubernetes-sigs/kueue/tree/main/keps/2076-kueuectl#stop-localqueue.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by rainfd** [comment]
I'm a new contributor to Kueue.  
Add StopPolicy for LocalQueue(#2109) is in processing. Should I wait for the completion before continuing? Or is this issue also in your implementation?
@mbobrovskyi

**Comment by mbobrovskyi** [comment]
Yes, issue blocked with #2173.

**Comment by mbobrovskyi** [comment]
Just to do not miss, #2173 merged.
