### ISSUE TITLE
Reformat all imports using gci linter

### ISSUE THREAD

**Issue by alexandear** [kubernetes-sigs/kueue#2198]
**What would you like to be cleaned**:

Reformat all imports using [`gci`](https://golangci-lint.run/usage/linters/#gci) linter once the issue daixiang0/gci#135 is resolved.

Disable `goimports` because `gci` does the same work.

**Why is this needed**:

`gci` ensures consistency of the import order.

See discussions in #2069 and #2184.

**Comment by trasc** [comment]
Maybe I'm missing something, why do we need this `gci` ?

**Comment by alexandear** [comment]
We need `gci` because it's introduced by the PR #2069.

**Comment by alculquicondor** [comment]
If the PR merged, doesn't it mean that we have no violations?

**Comment by alexandear** [comment]
> If the PR merged, doesn't it mean that we have no violations?

The PR #2069 didn't enable `gci` due to incorrect configuration, but the author and reviewers thought it was enabled. See the description in #2184 for a detailed explanation.

**Comment by alculquicondor** [comment]
gotcha, so we can't re-enable `gci` just yet.

OTOH, we don't really use kube-builder scaffolding.

How reliable is this `gci` linter? The fact that it belongs to a person's github instead of an organization seems a bit worrisome.

**Comment by alexandear** [comment]
`gci` has been included in golangci-lint since [v1.30.0](https://github.com/golangci/golangci-lint/blob/a62f1f13aa0a2b355ddd4a94448f22cbe6c0534c/pkg/lint/lintersdb/builder_linter.go#L309-L310), so it's quite stable.

But let's ask the author of the original PR who wants to enable `gci`. @vladikkuzn, is it worth replacing `goimports` with `gci`?
