### ISSUE TITLE
kueuectl: list pods for a job

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2204]
**What would you like to be added**:

The ability to list all the pods that belong to a job. This probably will have to be specialized for every kind of job.

```
kubectl kueue list pods --for job/my-job-name
```

**Why is this needed**:

To simplify the experience of users who are not very familiar with kubernetes, and label selectors.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by Kavinraja-G** [comment]
@alculquicondor @trasc  I'm happy to contribute if this is not started already?

**Comment by trasc** [comment]
I am OK with this, @alculquicondor WDYT?

**Comment by alculquicondor** [comment]
Sounds good.

@Kavinraja-G please write `/assign` in a comment.

**Comment by Kavinraja-G** [comment]
> will have to be specialized for every kind of job

@alculquicondor Can you elobrate this part? My understanding is to list the pods even when the user specifies `[cronjobs|jobs]/<job-name>` Let me know if I'm wrong.

**Comment by alculquicondor** [comment]
We also have mpijobs, kubeflow, ray clusters, etc.

The way to obtain the pods for all these different types might differ.
