### ISSUE TITLE
Faky test: Pod groups when Single CQ should admit group that fits

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#2225]
/kind flake

**What happened**:
Failed `End To End Suite: kindest/node:v1.28.0: [It] Pod groups when Single CQ should admit group that fits`

```shell
{Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:133 with:
NotFoundError expects an error failed [FAILED] Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:133 with:
NotFoundError expects an error
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:134 @ 05/17/24 17:17:58.033
}
```

**What you expected to happen**:
No errors.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2221/pull-kueue-test-e2e-main-1-28/1791517344896389120

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
It also happened in the periodic tests https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-e2e-main-1-27/1787143043464302592

/assign @trasc
