### ISSUE TITLE
Flaky integration test: Should preempt Workloads with lower priority when there is not enough quota

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2244]
/kind flake

**What happened**:

The test failed on the periodic build of the main branch: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-integration-main/1791517099273752576

**What you expected to happen**:

No flake

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the build

**Anything else we need to know?**:

```
{Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:456 with:
Expected
    <int>: 3
to equal
    <int>: 2 failed [FAILED] Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:456 with:
Expected
    <int>: 3
to equal
    <int>: 2
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/scheduler/preemption_test.go:139 @ 05/17/24 17:21:11.919
}
```

**Comment by mimowo** [comment]
> One alternative could be to increment the Eviction metric only from the workload controller's update handler when a eviction transition is detected.

This sounds like a reliable solution which could be used for other eviction reasons, allowing for less code.  Any drawbacks of the approach?

**Comment by trasc** [comment]
> > One alternative could be to increment the Eviction metric only from the workload controller's update handler when a eviction transition is detected.
> 
> This sounds like a reliable solution which could be used for other eviction reasons, allowing for less code. Any drawbacks of the approach?

Just on timing maybe, the update event is visible some milliseconds later, but when it comes to observability this should not be an issue. 

There also cold be other reasons @lowang-bh  choose this approach.  @lowang-bh?

**Comment by mimowo** [comment]
> Just on timing maybe, the update event is visible some milliseconds later, but when it comes to observability this should not be an issue.

yeah, I don't think this is any issue. I would suggest refactoring the code to use this approach.

**Comment by trasc** [comment]
Thinking about it , in case of multiple kueue-manager running, the non-leaders can "see" the same change multiple times, this could be a problem. 

I think going with #2254 is the easiest path for now.

**Comment by mimowo** [comment]
> Thinking about it , in case of multiple kueue-manager running, the non-leaders can "see" the same change multiple times, this could be a problem.

Ah, good point

**Comment by trasc** [comment]
I'd expect the Prometheus to scrape all the replicas , leader or not at any point in time.

**Comment by mimowo** [comment]
> I'd expect the Prometheus to scrape all the replicas , leader or not at any point in time.

Yeah, but Prometheus itself does not aggregate the values, so aggregation is still up to the admin.

I actually checked it using the [ai on gke](https://github.com/GoogleCloudPlatform/ai-on-gke) project, and could see that the metrics are incremented by controller-runtime per replica, also for non-leading replicas. 

Also, inside kueue we are not very consistent, for example `kueue_admitted_active_workloads` is bumped also for all replicas (via cache):
![image](https://github.com/kubernetes-sigs/kueue/assets/10359181/a615ed82-167d-45af-814c-74c778989975)

**Comment by trasc** [comment]
> > I'd expect the Prometheus to scrape all the replicas , leader or not at any point in time.
> 
> Yeah, but Prometheus itself does not aggregate the values, so aggregation is still up to the admin.
> 
> I actually checked it using the [ai on gke](https://github.com/GoogleCloudPlatform/ai-on-gke) project, and could see that the metrics are incremented by controller-runtime per replica, also for non-leading replicas.
> 
> Also, inside kueue we are not very consistent, for example `kueue_admitted_active_workloads` is bumped also for all replicas (via cache) (in this case I have only one workload admitted): ![image](https://private-user-images.githubusercontent.com/10359181/332837699-a615ed82-167d-45af-814c-74c778989975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTcyOTQsIm5iZiI6MTcxNjM5Njk5NCwicGF0aCI6Ii8xMDM1OTE4MS8zMzI4Mzc2OTktYTYxNWVkODItMTY3ZC00NWFmLTgxNGMtNzRjNzc4OTg5OTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2NTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZmIyODIzOGUyZTY0OWQ1NzM3YmI2NjBkZDdlM2NmYmIxN2FlYzY0YWU0ZGMyMTcwYTE1NzIxMjVkN2JmYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cbh6CfL5D4QhbW8cthOduv2QfIszgVK5OGNiDc7w4Vs)

In a real life dashboard is very likely that the end user don't want to take into account which of the replicas is the leader at some point so some kind of aggregation capability is expected. Maybe we should think about this for all the metrics we are producing.

**Comment by mimowo** [comment]
I guess we can park this for now. We have another good (or even better) solution to the issue.
