### ISSUE TITLE
Deprecate the `QueueVisibility` feature gate and corresponding API

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#2256]
**What would you like to be cleaned**:
I suggest coming with a plan to deprecate [the `QueueVisibility` API](https://github.com/kubernetes-sigs/kueue/tree/main/keps/168-pending-workloads-visibility). I would start with deprecating the `QueueVisiblity` feature gate and deleting logic behind it, and then remove [the visibility field](https://github.com/kubernetes-sigs/kueue/blob/a7ca2acc2042b047137a769bfcb1e6b749eba469/apis/kueue/v1beta1/clusterqueue_types.go#L302) from ClusterQueue's Status when migrating to a next beta version of Kueue API.

**Why is this needed**:
There was [the visibility API](https://github.com/kubernetes-sigs/kueue/tree/main/keps/168-2-pending-workloads-visibility) introduced that covers all business needs that were cover by the `QueueVisibility` API and more. The visibility API resolves all drawback related to the `QueueVisibility` API and addresses its limitations. For now I don't see a rationale for maintaining the `QueueVisiblity` API. Additionally I believe having two different ways (and two feature gates) to monitor pending workloads may lead to a little confusion regarding their pros and cons.

**Comment by PBundyra** [comment]
@alculquicondor @mimowo @mwielgus @tenzen-y WDYT?

**Comment by PBundyra** [comment]
If you agree with this idea I will add this to the v1beta2 wishlist.

**Comment by mimowo** [comment]
Yeah, I never liked the mechanism, but we may want to seek additional community feedback at the batch-wg meeting / slack.

**Comment by tenzen-y** [comment]
I agree with you, but let's keep it while v1beta1 for the backward compatibility.

**Comment by mimowo** [comment]
> I agree with you, but let's keep it while v1beta1 for the backward compatibility.

Keeping for backwards compatibility makes sense, but I think we can already deprecate it, so:
1. update the kube_features to mention it is deprecated, like [here](https://github.com/kubernetes/kubernetes/blob/c3ebd95c837a21c0c79ab64721c28bba44331bf9/pkg/features/kube_features.go#L49)
2. and also mention it is deprecated in the docs.

**Comment by mimowo** [comment]
Just to x-reference the related effort of promoting the VisibilityOnDemand to beta: https://github.com/kubernetes-sigs/kueue/issues/2973

**Comment by mimowo** [comment]
@mbobrovskyi would you like to continue with this as a follow up to https://github.com/kubernetes-sigs/kueue/issues/2973?
