### ISSUE TITLE
Show fair share of a CQ in status and a metric

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2258]
**What would you like to be added**:

A metric `cluster_queue_weighted_share` and a field in the ClusterQueue status that shows the live calculation of https://github.com/kubernetes-sigs/kueue/blob/a7ca2acc2042b047137a769bfcb1e6b749eba469/pkg/cache/clusterqueue.go#L673

The API could look like:

```yaml
status:
  fairSharing:
    rawShare: 50
    weightedShare: 25
```

Note that the comment in the function needs to be updated. rawShares can be 0 to 1000, but weightedShare can be up to 1M (because the smallest possible value for the weight is 0.001).

**Why is this needed**:

For visibility and debugability

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
cc @gabesaba

**Comment by mbobrovskyi** [comment]
@alculquicondor Is I correct understood that in the context of 

https://github.com/kubernetes-sigs/kueue/blob/a7ca2acc2042b047137a769bfcb1e6b749eba469/pkg/cache/clusterqueue.go#L719-L722

drs before L720 is rawShare and after that it's the weightedShare?

**Comment by alculquicondor** [comment]
correct.

**Comment by alculquicondor** [comment]
That said, I'm not convinced that `rawShare` is the best name for it. I'm open to suggestions.

**Comment by trasc** [comment]
> That said, I'm not convinced that `rawShare` is the best name for it. I'm open to suggestions.

In my opinion, if there is no  plan to change the weight algorithm, of the two fields can be skipped ,one multiply and one division  with (1000 and a spec field should not be that hard to do to extract the one from the other.

**Comment by alculquicondor** [comment]
The only value that is actually used in algorithms is `weightedShare`, so that would have to definitely be included.

The other one just increases debuggability, as it directly summarizes what the "usage" of a ClusterQueue is. But we can skip it for now and wait for user feedback if it's needed in the future.

**Comment by mbobrovskyi** [comment]
@alculquicondor should we add this metric only if `metrics.enableClusterQueueResources` is enabled?

**Comment by alculquicondor** [comment]
Also, if fairSharing is enabled.
