### ISSUE TITLE
Kueue might lose fields when admitting jobs

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2269]
**What happened**:

Whenever Kueue APIs are a version behind the latest version for a particular job type, there is the risk of dropping fields, because of the use of `Update`.

We should be using `Patch` instead.

**What you expected to happen**:

Kueue to be resilient to upgrades of Job CRDs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
As a hotfix for jobset integration, we need to bump the version of jobset in the release-0.6 branch.

We might have to do it manually https://github.com/kubernetes-sigs/kueue/pull/1984

**Comment by mimowo** [comment]
/reopen
Let's keep it open to keep track of the outstanding work in https://github.com/kubernetes-sigs/kueue/pull/2553 which is not just cleanup but also semantic change from non-strict to strict patches.
