### ISSUE TITLE
enabling manageJobsWithoutQueueName breaks OpenShift clusters

### ISSUE THREAD

**Issue by dgrove-oss** [kubernetes-sigs/kueue#2277]
**What happened**:
Deploying Kueue with `manageJobsWithoutQueueName` set to true on an OpenShift cluster broke core system functionality. 
In particular,  batchv1/Jobs that are used by OpenShift operators to perform administrative operations were suspended indefinitely resulting in degraded system functionality. 

See #2119 for discussion of some alternative solutions, such as namespace-level configuration of `manageJobsWithoutQueueName`, namespace-level configuration of the `batch/jobs` integration, and removal of the `manageJobsWithoutQueueName` functionality entirely. 

**What you expected to happen**:
In the short run, we should at least document that this configuration is ill-advised.  Ideally, we should dynamically flag it as a configuration error.

In the longer run, we should implement one of the alternatives discussed in #2119. 

**How to reproduce it (as minimally and precisely as possible)**:

Deploy Kueue with `manageJobsWithoutQueueName` true and the `batch/jobs` integration enabled.  Deploy an operator that uses Jobs (for example the Node Feature Discovery Operator) and observe that the operator does not work as intended.

**Anything else we need to know?**:

**Environment**:
An OpenShift 2.14 cluster with Kueue configured to enable `manageJobsWithoutQueueName`.

**Comment by alculquicondor** [comment]
/close
with #2279
