### ISSUE TITLE
Declare the versions of tools allowing for updates by dependabot

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2284]
**What would you like to be cleaned**:

Declare the versions of the tools in `Makefile-deps` so that they are managed by dependabot ([example of hard-coded dependency](https://github.com/kubernetes-sigs/kueue/blob/ceaa3b1fff1e2d95a2d4695d16f99b0d9a8d4ec0/Makefile-deps.mk#L34)).

**Why is this needed**:

To reduce manual maintenance and make sure the tools are not lagging behind. This ensures Kueue is compatible with the latest versions of the tools.

**Comment by mimowo** [comment]
/cc @alculquicondor @tenzen-y 
Let me know if this was discussed or maybe there are some drawbacks.

**Comment by tenzen-y** [comment]
@mimowo Actually, we should move all tool versions into `hack/internal/tools`.

https://github.com/kubernetes-sigs/kueue/pull/882#pullrequestreview-1491398785

**Comment by mimowo** [comment]
Yuki, thanks for the pointer. Will the `tools` dir have its own dedicated `go.mod` managed by dependabot, or the versions would be in the root `go.mod`

**Comment by tenzen-y** [comment]
It indicates the root go.mod.
https://github.com/kubernetes-sigs/kueue/tree/a50d395c36a2cb3965be5232162cf1fded1bdb08/hack/internal/tools

**Comment by mimowo** [comment]
sgtm, so IIUC we have the versions declared in the top `go.mod` and in the `hack/internal/tools` we import the tools sot that they are not removed by `go mod tidy`.

**Comment by tenzen-y** [comment]
> sgtm, so IIUC we have the versions declared in the top `go.mod` and in the `hack/internal/tools` we import the tools sot that they are not removed by `go mod tidy`.

Exactly. It is similar approach as this: https://github.com/golang/go/wiki/Modules/6fe9f52ac7c4d92cb8fc878d8dee1bda0c63c8a5#how-can-i-track-tool-dependencies-for-a-module

**Comment by tenzen-y** [comment]
> +1, we could follow up with the idea in the next PR

SGTM

/reopen

**Comment by mszadkow** [comment]
@tenzen-y @mimowo @trasc 
Should we apply the same set of rules (ignores) in dependabot for tools?
Those are for root `go.mod`
```  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
    ignore:
      # Ignore major and minor versions for dependencies updates
      # Allow patches and security updates.
      - dependency-name: k8s.io/*
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
```

**Comment by alculquicondor** [comment]
Yes, that seems appropriate

**Comment by tenzen-y** [comment]
> @tenzen-y @mimowo @trasc Should we apply the same set of rules (ignores) in dependabot for tools? Those are for root `go.mod`
> 
> ```
>     directory: "/"
>     schedule:
>       interval: "weekly"
>     labels:
>       - "ok-to-test"
>       - "release-note-none"
>     groups:
>       kubernetes:
>         patterns:
>           - "k8s.io/*"
>     ignore:
>       # Ignore major and minor versions for dependencies updates
>       # Allow patches and security updates.
>       - dependency-name: k8s.io/*
>         update-types: ["version-update:semver-major", "version-update:semver-minor"]
> ```

SGTM, Thank you!
