### ISSUE TITLE
Graduate API to beta

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#23]
Currently, this would be very cumbersome due to the lack of support from kubebuilder https://github.com/kubernetes-sigs/controller-tools/issues/656

Once the support is added and we are ready to publish a v1beta1, we should consider renaming the api group. Note that this requires an official api-review https://github.com/kubernetes/enhancements/pull/1111

Summary doc: https://docs.google.com/document/d/1Uu4hfGxux4Wh_laqZMLxXdEVdty06Sb2DwB035hj700/edit?usp=sharing&resourcekey=0-b7mU7mGPCkEfhjyYDsXOBg (join https://groups.google.com/a/kubernetes.io/g/wg-batch to access)

Potential changes when graduating:
- [ ] Move `admission` from Workload spec into status (from #498)
- [ ] Rename `min`, `max` into something easier to understand.
- [ ] Support queue name as a label, in addition to annotation (makes it easier to filter workloads by queue).
- [ ] Add `ObjectMeta` into each `PodSet` template.

**Comment by ahg-g** [comment]
I think using `sigs.k8s.io` as domain isn't necessary and doesn't add value. If this ever moves to core k8s, it would likely be under `batch.k8s.io` anyways.

I think for the time being, and to avoid the awkward `x-`, it seems reasonable to use the shorter `kueue.sh` domain.

**Comment by alculquicondor** [comment]
I think the value is the direct association to the Kubernetes project. I prefer having it in the API name. But what do others think?

**Comment by denkensk** [comment]
Anyway, it will be moved to core k8s in the future, so why not choose to use `batch.k8s.io` directly. This will reduce the work of users to change api groups in the future.

**Comment by alculquicondor** [comment]
Assuming that you don't mean `batch`, which would require the API to be part of k/k. 
Any `k8s.io` domain name requires an API review. This will take a week or two. Should we do it it just release the alpha APIs as-is. I think I prefer to release them sooner for more chances to get real-world feedback. And then we can go for an API review when we aim for beta.

**Comment by ahg-g** [comment]
> I think the value is the direct association to the Kubernetes project. I prefer having it in the API name. 

The `-x` makes it look weired.

> Any k8s.io domain name requires an API review. This will take a week or two.

If that is a one time thing, then we can pursue it; but I am not sure if we want it if it requires a review for every change we make.

**Comment by alculquicondor** [comment]
It probably does. But maybe we can just rename to `batch.k8s.io` and mark it as unapproved for now https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2337-k8s.io-group-protection#proposal

**Comment by denkensk** [comment]
+1 We can mark it unapproved at the alpha version.

**Comment by ahg-g** [comment]
This is discouraged, and it only adds to the confusion. Users don't look at CRD definitions.

ok, I don't want to delay things, I am fine with keeping the `x-k8s.io` domain just because it is used by other subprojects (it doesn't make it less weird though) and revisit when we go to Beta;

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

maybe for 0.3.0 :)

**Comment by alculquicondor** [comment]
/reopen

/lifecycle frozen

we need to get back to this when targeting a v1beta1 API.

**Comment by alculquicondor** [comment]
I'm starting a list of potential changes to the API. See Issue description.

**Comment by alculquicondor** [comment]
cc @kerthcet for feedback (and anyone already in the thread, of course)

**Comment by kerthcet** [comment]
> Move `admission` from Workload spec into status (from [Enforce timeout for podsReady #498](https://github.com/kubernetes-sigs/kueue/pull/498))

I'm ok with this, admission presents the actual state of a workload.

> Rename `min`, `max` into something easier to understand.

Before, we named them `requests/limits`? Anyway, I think reading document is always needed, whatever the name. So I'm fine with `min/max`, another pair maybe `guarantee/capacity`?

> Support queue name as a label, in addition to annotation (makes it easier to filter workloads by queue).

Can you provide some context why we need this?

**Comment by alculquicondor** [comment]
> Before, we named them requests/limits?

No, that would have been very confusing because they already mean something in the pod spec. I'll start a separate doc to discuss options.

> Can you provide some more context why we need this? It looks like looking for workloads via label selector.

It's actually about filtering Jobs using the queue name.

**Comment by tenzen-y** [comment]
> No, that would have been very confusing because they already mean something in the pod spec. I'll start a separate doc to discuss options.

When I joined the kueue project, one of the most confusing of the kueue specification was the relationship between `min/max` and cohort.

IMO, the `guarantee/capacity` looks good rather than `min/max`.

**Comment by kerthcet** [comment]
> It's actually about filtering Jobs using the queue name.

It made me think of adding queueName to job's spec https://github.com/kubernetes/enhancements/pull/3397, we can filter jobs with field-selector, is this the final solution we want?

**Comment by alculquicondor** [comment]
Yes, that would be ideal, but that KEP got significant push back, so I don't see it happening anytime soon.

**Comment by alculquicondor** [comment]
We might also need to add ObjectMeta into each PodSet template. Cluster autoscaler needs the metadata to properly scale up.

**Comment by kerthcet** [comment]
Is this for scaling up in advance? Or autoscaler only watching the unschedulable pods, who contains the metadata.

**Comment by alculquicondor** [comment]
I've created a summary doc with the proposed changes as we graduate to beta (also available in the issue description): https://docs.google.com/document/d/1Uu4hfGxux4Wh_laqZMLxXdEVdty06Sb2DwB035hj700/edit?usp=sharing&resourcekey=0-b7mU7mGPCkEfhjyYDsXOBg

I have a WIP in #532
