### ISSUE TITLE
Support ClusterQueues defining DWS flavors

### ISSUE THREAD

**Issue by colinjc** [kubernetes-sigs/kueue#2324]
**What would you like to be added**:

We want to be able to define a ClusterQueue that has a default flavor pointing at some fixed resources, and if that's full bursts out using the DWS API. This would be similar to having a fixed cluster that bursts to spot nodes.

**Why is this needed**:

Currently users must either submit to a fixed queue OR a DWS queue, and need to change code to do so. If we could target a single queue, it would be simpler to ensure the fixed cluster is always saturated and DWS is only used when required.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
This is already supported in the upcoming release of Kueue v0.7.

Please give us one or two days to release. We are just finishing up some documentation #2305

/close

**Comment by alculquicondor** [comment]
BTW, this was the original issue #1432
