### ISSUE TITLE
Add a hugo template to highlight minimum supported version

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2325]
**What would you like to be added**:

Some reusable block that looks similar to the following:

![image](https://github.com/kubernetes-sigs/kueue/assets/1299064/070e42d8-ffb4-494e-8f62-49d12c3a49ad)

And then use that for every time we mention that a feature is only available in a certain version.

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by ivange94** [comment]
Hi @alculquicondor, I would like to work on this. I'm new to the project and will appreciate some guidance on how to go about this.

**Comment by alculquicondor** [comment]
You can probably look at this PR for inspiration https://github.com/kubernetes-sigs/kueue/pull/2006

To see your work locally, you can run `make site-server`

**Comment by ivange94** [comment]
@alculquicondor is there somewhere that we need to use this block right now? To test this I just added it to a random page but didn't commit this change. This is how it looks like. 
<img width="806" alt="Screenshot 2024-06-01 at 6 05 09 PM" src="https://github.com/kubernetes-sigs/kueue/assets/11330494/17c039b4-96d0-4e9a-8ce6-f459c5fc30b4">

It also looks like I didn't configure my git properly so it didn't use my actual email address and the bots say I didn't sign the license agreement. Would it be okay to edit that commit and force push to my branch or should I close the current PR and create a new one?

**Comment by tenzen-y** [comment]
> It also looks like I didn't configure my git properly so it didn't use my actual email address and the bots say I didn't sign the license agreement. Would it be okay to edit that commit and force push to my branch or should I close the current PR and create a new one?

@ivange94 We're ok with either way.

**Comment by tenzen-y** [comment]
> @alculquicondor is there somewhere that we need to use this block right now? To test this I just added it to a random page but didn't commit this change. This is how it looks like.

We aim to replace the warnings/notes like the ones below.

https://kueue.sigs.k8s.io/docs/tasks/manage/setup_sequential_admission/#requeuing-strategy
