### ISSUE TITLE
Flaky integration test: Should print workloads list with paging

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#2353]
/kind flake

**What happened**:

Integration test failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2314/pull-kueue-test-integration-main/1798039851593895936

**What you expected to happen**:

No flake

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the build.

**Anything else we need to know?**:

```
  [FAILED] Expected
      <string>: "...     1s
      "
  to equal               |
      <string>: "...     0s
      "
  In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/kueuectl/list_test.go:206 @ 06/04/24 17:19:10.001
```

**Comment by mbobrovskyi** [comment]
https://github.com/kubernetes-sigs/kueue/pull/2354#discussion_r1627577356

**Comment by mimowo** [comment]
It seems the fake clock is WIP here: https://github.com/kubernetes-sigs/kueue/pull/2364

**Comment by mbobrovskyi** [comment]
Still have issue https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2392/pull-kueue-test-integration-main/1800186041294917632.

```bash
{Expected
    <string>: "...     0s
    wl1..."
to equal               |
    <string>: "...     1s
    wl1..." failed [FAILED] Expected
    <string>: "...     0s
    wl1..."
to equal               |
    <string>: "...     1s
    wl1..."
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/kueuectl/list_test.go:227 @ 06/10/24 15:26:45.03
}
```

**Comment by mbobrovskyi** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2346/pull-kueue-test-integration-main/1800200554622750720

{Expected
    <string>: "...     true  ..."
to equal               |
    <string>: "...     false ..." failed [FAILED] Expected
    <string>: "...     true  ..."
to equal               |
    <string>: "...     false ..."
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/kueuectl/list_test.go:168 @ 06/10/24 16:24:51.58
}

**Comment by mimowo** [comment]
/reopen 
For the https://github.com/kubernetes-sigs/kueue/pull/2399 fix.
