### ISSUE TITLE
Vendor dependencies

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2374]
**What would you like to be added**:

We are trying to build images in a different infrastructure that requires vendoring the dependencies.

Do you have any strong opinions against vendoring?

**Why is this needed**:

Maybe a side benefit could be to improve CI times? But we would have to test it.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
You indicated to the Go module vendor like https://github.com/kubernetes/kubernetes/tree/master/vendor.

**Comment by alculquicondor** [comment]
Yes, exactly

**Comment by tenzen-y** [comment]
TBH, I don't prefer to use the vendor since vendors will increase git diff... 
Actually, the cluster-autoscaler removes vendoring recently: https://github.com/kubernetes/autoscaler/pull/6572

I'd like to avoid the vendoring as far as possible, but if vendoring is needed in your building environments, I'm ok with vendoring...

**Comment by jasonsmithio** [comment]
I would be interested in the pros and cons of having some kind of vendoring for kueue.

**Comment by kerthcet** [comment]
We do use vendor to accelerate the CI and offline build for some projects internally, but not a buyer for this if we can avoid.

**Comment by trasc** [comment]
Also on the con side, the dependencies of kueue are not just a few and some of them (`hack/internal/tools`) are not related to the kueue's code but only the tools used.

**Comment by alculquicondor** [comment]
I'm hoping we can just vendor the main go module and not `/hack/internal/tools` or `/site`. Basically anything to build the main binary.

I also asked @liggitt about any plans for k/k to remove /vendor, and he said there are none.

**Comment by alculquicondor** [comment]
#2403 is ready for merge, if there are no strong opinions against
