### ISSUE TITLE
Distinguish between Preemption due to reclamation and fair sharing

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2404]
**What would you like to be added**:

An additional reason in the Preemption condition to indicate that the preemption was due to fair sharing and not regular reclamation.

The current reason for reclamation or fair sharing is `InCohort`

We could have: `InCohortReclamation` and `InCohortFairSharing`.

**Why is this needed**:

For better visibility

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
I think the decision is based entirely on the preemptor. If the preemptor fits in the nominal quota of its ClusterQueue, then it's preempting others that are borrowing its quota.
Otherwise, it's past the nominal quota, meaning that it's using resources from the fair share.

Note that whether fair sharing is enabled is global.

/assign @vladikkuzn

**Comment by alculquicondor** [comment]
cc @gabesaba

**Comment by trasc** [comment]
> I think the decision is based entirely on the preemptor. If the preemptor fits in the nominal quota of its ClusterQueue, then it's preempting others that are borrowing its quota.
> Otherwise, it's past the nominal quota, meaning that it's using resources from the fair share.

Also, if the preemptor and preemptee are in the same cluster queue we can say it's a simple priority based eviction (no quota is reclaimed from a borrower)
