### ISSUE TITLE
Add a watch for Ray and Training Operator CRDs

### ISSUE THREAD

**Issue by ChristianZaccaria** [kubernetes-sigs/kueue#2414]
**What happened**:
When the Kueue component is installed before the Ray OR Training Operator, Kueue doesn't monitor RayCluster or PyTorchJob resources + any other [CRDs from the Training Operator.](https://github.com/kubeflow/training-operator/tree/master/manifests/base/crds)

When the user creates a RayCluster or PyTorchJob resources, Kueue doesn't control admission of those resources.

Logs:
>{"level":"info","ts":"2024-05-30T11:07:08.761740832Z","logger":"setup","caller":"jobframework/setup.go:69","msg":"No matching API in the server for job framework, skipped setup of controller and webhook","jobFrameworkName":"kubeflow.org/pytorchjob"}

**What you expected to happen**:
JobFramework Controller and Webhook should start/restart once required CRDs from Ray OR Training-Operator are available.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Kueue without the Ray or Training-Operator CRDs.
2. Check Kueue logs.

**Anything else we need to know?**:
Proposed Solution:
Add a watcher to controller and webhook, to start/restart in the event of availability of Ray OR Training-Operator CRDs.

I have a draft PR ready - still needs some work.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment]
Adding a watch just for this looks too much for me since having the CRDs installed before enabling an integration in the Kueue's config it's a reasonable expectation and even if it's not the case `rollout restart`-ing the Kueue's controller manager can easily solve the issue.

@alculquicondor WDYT?

**Comment by alculquicondor** [comment]
I also think that it's a reasonable expectation that the administrator needs to restart Kueue.

But I'm willing to accept a PR if it doesn't add significant complexity. It's probably going to be similar to the watch we have for k8s version.

**Comment by ChristianZaccaria** [comment]
@alculquicondor here is a draft PR we have on our fork: https://github.com/opendatahub-io/kueue/pull/33/files

Planning on changing it a bit to account for Training Operator OR Ray CRDs, then restart the JobFramework controller and webhook once CRDs are available. The approach in the PR separates concerns, providing a more readable and robust code. Please let me know if it looks good, and if should continue and make a PR. Thanks a lot for your help!

**Comment by alculquicondor** [comment]
so overall you are adding a watch... Maybe it isn't too bad.

wdyt @trasc?

**Comment by trasc** [comment]
I guess it could work, but it should work for any CRD (maybe some kind of wrapper like https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/core/leader_aware_reconciler.go).

Given the limited use-case and available alternatives, the work might outweigh the added benefits, however we can try it.

(controller-runtime might a better place to implement this kind of feature)

**Comment by ChristianZaccaria** [comment]
Hi folks, before making a PR to resolve this issue, we would like to get some feedback on which option would suit best. We have 3-4 proposals in place.

Here are the 3 proposals:
https://github.com/ChristianZaccaria/kueue/pull/3 (Watcher using Dynamic Client - Restarting Kueue pod)
https://github.com/ChristianZaccaria/kueue/pull/4 (RESTMapper - Restarting Kueue pod)
https://github.com/ChristianZaccaria/kueue/pull/5 (RESTMapper - Starting controller/webhook of the respective framework on availability of the CRD - No restarts on Kueue pod)
A 4th idea is to use the apiextension clientset which queries for CRDs directly. 

Preference may be on the RESTMapper as it's the [current way Kueue is verifying](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/jobframework/setup.go#L70) if the APIs exist. - Minimal changes.

Thank you! @alculquicondor @trasc

**Comment by trasc** [comment]
If it works as expected, for me I think the 3rd option is the cleanest. 

The problem with the first one is that in my opinion we cannot assume that the plural of a kind is the lexical plural of that kind in lowercase,

**Comment by ChristianZaccaria** [comment]
@trasc the 3rd option is definitely the cleanest. I'll wait a few for @alculquicondor's opinion on this and will make a PR for further reviewing.

**Comment by alculquicondor** [comment]
sgtm

**Comment by mimowo** [comment]
As part of fixing this issue please update the documentation to amend or revert: https://github.com/kubernetes-sigs/kueue/pull/2685.

**Comment by mimowo** [comment]
/reopen
To update the documentation accordingly, or cherry-pick https://github.com/kubernetes-sigs/kueue/pull/2574

**Comment by ChristianZaccaria** [comment]
Hi @mimowo it looks like we'll be updating the documentation if this is considered as feature rather as a bug fix. Would like to have confirmation on this. Let me know if the consensus is to update the docs and I'll create a PR promptly. Thanks a lot!

https://github.com/kubernetes-sigs/kueue/pull/2685#issuecomment-2326102778

**Comment by mimowo** [comment]
I would suggest to reconsider this decision, as the fix does not introduce any API changes, and from the end user perspective this is a bug - at least this is the impression I was getting when investigating some of the users' issues. 

I posted also under the PR https://github.com/kubernetes-sigs/kueue/pull/2574.
