### ISSUE TITLE
Flaky e2e test for JobSet

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#2428]
/kind flake

**What happened**:
Flaky test for JobSet "JobSet when Creating a JobSet Should run a jobSet if admitted"

**What you expected to happen**:
No failure

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2408/pull-kueue-test-e2e-main-1-28/1802723422271180800

**Comment by mbobrovskyi** [comment]
Looks like duplicate of #2073
