### ISSUE TITLE
Flaky e2e test for MultiKueue

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#2446]
/kind flake

**What happened**:
E2e test for MultiKueue failed

**What you expected to happen**:
No failure

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2408/pull-kueue-test-multikueue-e2e-main/1803390960541896704

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mbobrovskyi** [comment]
I'm not sure that it's our error.

**Comment by mbobrovskyi** [comment]
Looks like it's limitation to running max count of parallel jobs.

**Comment by mimowo** [comment]
I'm not very familiar with this part of [test-infra](https://github.com/kubernetes/test-infra), but maybe we can use the occurrences like this as potential motivation to increase the number of nodes in the cluster? cc @alculquicondor

**Comment by alculquicondor** [comment]
Uhm.... this is about the number of nodes in the test-infra cluster, not our tests' kind clusters.

There isn't much we can do from our side.

/close
