### ISSUE TITLE
resourceFlavor can't be deleted unless no clusterQueue references it

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#249]
**What would you like to be added**:
When we deleting resourceFlavor, we should make sure there's no cluster queue references it.

Refer to discussion here: https://github.com/kubernetes-sigs/kueue/pull/230#discussion_r862497340

**Why is this needed**:
Prevent potential bug.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by cmssczy** [comment]
When we deleting resourceFlavor and find that there is a `ClusterQueue` referencing it, we should add a `finalizer` to it and then watch clusterqueue `Delete Event` until we can delete this `resourceFlavor` completely, is it right?

**Comment by kerthcet** [comment]
> When we deleting resourceFlavor and find that there is a `ClusterQueue` referencing it, we should add a `finalizer` to it and then watch clusterqueue `Delete Event` until we can delete this `resourceFlavor` completely, is it right?

yes and more details:
- [ ] add `finalizer` to resourceFlavor controller, flavors can only be deleted when there's no `ClusterQueue` referencing it
- [ ] only a ClusterQueue which references the flavor has no admitted workloads, then we can delete the flavor.

**Comment by cmssczy** [comment]
If you haven't started doing it, would you mind letting me try to work on it?
