### ISSUE TITLE
controller.kubernetes.io/queue-name annotation not registered

### ISSUE THREAD

**Issue by sftim** [kubernetes-sigs/kueue#25]
The code in this repo uses an annotation, `controller.kubernetes.io/queue-name`, that is not registered in https://kubernetes.io/docs/reference/labels-annotations-taints/

We should either:
- register and document the annotation
- avoid specifying `controller.kubernetes.io` as the namespace for that annotation, and instead require specifying it as a command line option to the app. That way, end-users wouldn't assume that any particular namespace is expected.
- use another namespace, that is appropriate for kueue.

**Comment by sftim** [comment]
I'm not 100% clear on the registration rules but it looks to me as if both `controller.kubernetes.io/queue-name` and `kueue.kubernetes.io/queue-name` are annotation keys that require registration. The Kubernetes Architecture SIG would be able to confirm what the exact requirements are for using namespaces connected with `kubernetes.io`.

**Comment by alculquicondor** [comment]
Let's use `kueue.x-k8s.io` for now. We will request an API review and register the annotation when we are ready for a beta API #23

We might just add queue to the Job spec instead :) https://github.com/kubernetes/kubernetes/issues/106886
