### ISSUE TITLE
cleanup manipulation of CQ/Cohort resource accounting in tests

### ISSUE THREAD

**Issue by gabesaba** [kubernetes-sigs/kueue#2502]
**What would you like to be cleaned**:
We sometimes manipulate the internal accounting of ClusterQueue and Cohort snapshots. This is brittle. Quota/Lending Limit/Borrowing Limit/Usage should be set by calling public api methods, or by defining the CQs/Cohorts via API objects, adding to cache, and creating snapshot (see #2486 for an example).

See this thread https://github.com/kubernetes-sigs/kueue/pull/2486#discussion_r1658747058

**Why is this needed**:
Tests are brittle, and make cache/snapshot hard to update

**Comment by alculquicondor** [comment]
Also https://github.com/kubernetes-sigs/kueue/pull/2486#discussion_r1658976669

**Comment by gabesaba** [comment]
We also test against internal state of usage/quotas/limits. I will link those cleanup PRs to this issue as well.

**Comment by gabesaba** [comment]
- [ ] [clusterqueue_test.go](https://github.com/kubernetes-sigs/kueue/blob/32e3c3313439091f9db58b55ec595a9925103abe/pkg/cache/clusterqueue_test.go#L97-L315)
- [ ] [flavorassigner_test.go](https://github.com/kubernetes-sigs/kueue/blob/32e3c3313439091f9db58b55ec595a9925103abe/pkg/scheduler/flavorassigner/flavorassigner_test.go#L1954-L1957)

These are the (hopefully) last two remaining. See https://github.com/kubernetes-sigs/kueue/pull/2583 for a complete example of refactoring test, changing ClusterQueueSnapshot to API type, and representing cohort capacity/usage via use of a 2nd cluster queue.

**Comment by gabesaba** [comment]
Thanks for helping with the cleanup, @highpon! Will you also be fixing flavorassigner_test.go?

**Comment by highpon** [comment]
Yes! I would love to work with you on `flavorassigner_test.go` as well!

**Comment by gabesaba** [comment]
Hi @highpon, will you still cleanup `flavorassigner_test.go`? If not, I will see if @vladikkuzn can work on it

**Comment by highpon** [comment]
@gabesaba 
Sorry for the delay in responding!
I have now refactored the file up to the halfway point.
Three tests are failing. After fixing them, I will change the [PR](https://github.com/kubernetes-sigs/kueue/pull/2749) from Draft to Open.

**Comment by gabesaba** [comment]
Discussed over Slack with @highpon. @vladikkuzn, could you complete the remaining cleanup please?

/assign @vladikkuzn

**Comment by mszadkow** [comment]
@gabesaba can we close this issue now?

**Comment by gabesaba** [comment]
> @gabesaba can we close this issue now?

Missed this message when OOO. Yes, we can close it. Thank you for the cleanup!

/close
