### ISSUE TITLE
ResourceFlavor tolerations should be included in ProvisioningRequest PodTemplate

### ISSUE THREAD

**Issue by sam-leitch-oxb** [kubernetes-sigs/kueue#2572]
**What happened**:
I created a ResourceFlavor with a nodeSelector and tolerations that are specific to my node pool, so that when a Job is admitted to a queue with that flavor, the tolerations and nodeSelector would be added.

The ClusterQueue I'm using also has an AdmissionCheck using the provisioning-request controllerName.

My Jobs are failing because the ProvisioningRequest expects to see the toleration and nodeSelector in the PodTemplate, but they are missing.

**What you expected to happen**:
PodTemplate created for ProvisionRequest should have the nodeSelector and toleration applied. 

**How to reproduce it (as minimally and precisely as possible)**:
* Create a ResourceFlavour with a nodeSelector and toleration.
* Create a ClusterQueue and LocalQueue targeting that flavor.
* Add an AdmissionCheck with controllerName kueue.x-k8s.io/provisioning-request to the ClusterQueue flavor.
* Create a Job that does not include the nodeSelector or tolerations.
* Note the Job -> Workload -> ProvisioningRequest -> PodTemplate **does not** contain the nodeSelector or toleration.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27.9
- Kueue version (use `git describe --tags --dirty --always`): 0.7.1
- Cloud provider or hardware configuration: GKE

**Comment by alculquicondor** [comment]
Just to double check the basics: Did you put resource requests in the Job template?

ResourceFlavor assignment is based on the resources requested by the job template. If there are no resource requests, then there are no flavors assigned, thus no labels/tolerations.

**Comment by sam-leitch-oxb** [comment]
My cluster has been updated to 1.30 and the issue appears to be resolved.
