### ISSUE TITLE
Flaky e2e: Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#2581]
**What happened**:
```
{Timed out after 5.001s.
The matcher passed to Eventually returned the following error:
    <*errors.errorString | 0xc000916e80>: 
    NotFoundError expects an error
    {
        s: "NotFoundError expects an error",
    } failed [FAILED] Timed out after 5.001s.
The matcher passed to Eventually returned the following error:
    <*errors.errorString | 0xc000916e80>: 
    NotFoundError expects an error
    {
        s: "NotFoundError expects an error",
    }
In [AfterEach] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/visibility_test.go:133 @ 07/10/24 20:52:49.276
}
```

**What you expected to happen**:
No issue

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2553/pull-kueue-test-e2e-main-1-27/1811140041414545408
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2579/pull-kueue-test-e2e-main-1-29/1811357227194257408

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
cc @PBundyra
