### ISSUE TITLE
SuspendJob feature gate is now removed

### ISSUE THREAD

**Issue by m-mamdouhi** [kubernetes-sigs/kueue#2582]
SuspendJob feature gate is now removed in kubernetes but it is still in the installation guide.

**Comment by m-mamdouhi** [comment]
I realise that when I create a job the runPolicy section is not added to it
do I need an upgrade? any help would be appreciated

**Comment by tenzen-y** [comment]
We still support older kubernetes version like v1.25.
So, keeping the mentioning of the featureGate name would be worth it.

/kind support
/remove-kind bug
/close
