### ISSUE TITLE
Flaky Test: Kueue visibility server when A subject is bound to kueue-batch-admin-role Should return an appropriate error

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#2586]
**What happened**:

The `End To End Suite: kindest/node:v1.30.0: [It] Kueue visibility server when A subject is bound to kueue-batch-admin-role Should return an appropriate error expand_less` failed.

```shell
{Expected
    <v1.StatusReason>: Forbidden
to equal
    <v1.StatusReason>: NotFound failed [FAILED] Expected
    <v1.StatusReason>: Forbidden
to equal
    <v1.StatusReason>: NotFound
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/visibility_test.go:506 @ 07/11/24 16:47:21.333
}
```

**What you expected to happen**:
Never seen these errors.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/mkubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2584/pull-kueue-test-e2e-main-1-30/1811439474740039680

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
cc @PBundyra

**Comment by alculquicondor** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kueue-test-e2e-main-1-27/1811394213485481984
