### ISSUE TITLE
Add number of AdmittedWorkloads to LocalQueue status

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#259]
**What would you like to be added**:

A field containing the number of active workloads.

We abandoned this idea earlier because the cache was not queue aware. But we already need to make it queue aware for the purpose of metrics #199 

**Why is this needed**:

Improve UX around observability

/kind ux

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by cmssczy** [comment]
The `active workloads` are the workloads which have been admitted by scheduler. Do I understand it correctly?
https://github.com/kubernetes-sigs/kueue/blob/afabae912eb3da09f810ca6bf0fd5fe5bf49874a/pkg/scheduler/scheduler.go#L304-L308

**Comment by alculquicondor** [comment]
I did some progress on this #259. After it merges, feel free to take over.

**Comment by ahg-g** [comment]
This would be similar to the AdmittedWorkloads in ClusterQueue

**Comment by kannon92** [comment]
I am getting up to speed in this repo.  

AdmittedWorkloads is the same as ActiveWorkloads?

**Comment by ahg-g** [comment]
yes, we are using the term admitted now.

**Comment by kannon92** [comment]
Hello.  So I made progress on this but I realize I'm unclear on the ask.  The issue reads very simple as add a new field.  

So here is my research:

1) Add a new field for AdmittedWorkloads in [Apis](https://github.com/kubernetes-sigs/kueue/blob/main/apis/kueue/v1alpha2/localqueue_types.go#L33)
2) Update the [CRD](https://github.com/kubernetes-sigs/kueue/blob/main/config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml) to reflect the new field

If I read the ticket exactly, then I believe my work is done?  

Is the intent that future features will update this API field?  Or should I also tackle this as part of the issue?

**Comment by ahg-g** [comment]
Not only add the field, we need to do populate it as well. Kueue is the one responsible for updating the status of both LocalQueue and ClusterQueue.  Take a look at the AdmittedWorkloads field in ClusterQueue and how we populate it as an example.

**Comment by alculquicondor** [comment]
No, we actually did that initially and reverted the change #293.

Just the status field should be good.

**Comment by kannon92** [comment]
Alright.  I think I have something for you all to review.  https://github.com/kubernetes-sigs/kueue/pull/382

Sorry about the spamming the repo with a few opens.
