### ISSUE TITLE
Please explain the reason why Priority is mutable but PriorityClassName is not mutable

### ISSUE THREAD

**Issue by sharanm** [kubernetes-sigs/kueue#2593]
https://kueue.sigs.k8s.io/docs/concepts/workload_priority_class/#workloads-priority-values-are-always-mutable

Does this mean that given a workload we would be able to change its priority by setting priority tag to any random integer ? 

Shouldn't we instead let user update priorityClassName tag in that speicific workload and fetch value of that className ?

In workload, did not quite follow the need to have an priority tag if we already have priorityClassName tag.

**Comment by alculquicondor** [comment]
You can read the design doc for some motivation https://github.com/kubernetes-sigs/kueue/tree/main/keps/973-workload-priority
