### ISSUE TITLE
Adding waitForPodsReady capability for all the jobs kueue supports

### ISSUE THREAD

**Issue by m-mamdouhi** [kubernetes-sigs/kueue#2594]
If my implementation is correct the waitForPodsReady capability is limited and not extended to the kubeflow jobs correct? it would be nice to have this "gangscheduling" capability with all of the jobs that kueue supports

**Comment by tenzen-y** [comment]
Actually, the `waitForPodsReady` is supported for all Jobs, including the kubeflow jobs.
/close

**Comment by FWCoder** [comment]
What is the behavior on "waitForPodsReady" that can help on "Gand Scheduling" use case?

**Comment by FWCoder** [comment]
> What is the behavior on "waitForPodsReady" that can help on "Gand Scheduling" use case?

I mean "Gang Scheduling".
