### ISSUE TITLE
Crash server on error in CreateAndStartVisibilityServer.

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#2634]
**What would you like to be added**:
Use `os.Exit(1)` on error in `CreateAndStartVisibilityServer`.

**Why is this needed**:
The current silencing of the error is not the best. 

https://github.com/kubernetes-sigs/kueue/blob/dac07e65a3be053dfac3d21a3fade4c4991a6995/pkg/visibility/server.go#L51-L53

Some users may need it, Kueue will start for them but not work as expected.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by mimowo** [comment]
+1 I like crashing (calling exit).

The only consideration from me is when users cannot configure visibility correctly, and they don't care about it, they would like to still be able to run Kueue. However, I expect we will get this kind of feedback before graduating to stable, and until then such users will have an option to disable by the feature gate.

cc @PBundyra

**Comment by alculquicondor** [comment]
Have you seen this error happening in the wild? I wonder what are common scenarios that could lead to it.

Nevertheless, I think it's safer to crash.

**Comment by mimowo** [comment]
I didn't see it
