### ISSUE TITLE
How to avoid configuring a quota in ClusterQueue that exceeds the physical node quota？

### ISSUE THREAD

**Issue by cho-chem** [kubernetes-sigs/kueue#2665]
When this situation occurs, Kueue will successfully schedule the Job, but the Pod executing the Job will remain in a pending state due to the lack of available nodes. I understand that this is not quite as expected.

**Comment by trasc** [comment]
Kueue is not implementing anything that checks the configuration at that level, so in case the available resources quota are static the administrator should make sure that the configured quota is not exceeding the resources that are physically available.

What can somehow use in this case is using the [Kubernetes cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) [Provisioning Requests integration](https://kueue.sigs.k8s.io/docs/admission-check-controllers/provisioning/).

**Comment by mimowo** [comment]
@cho-chem kueue generally aims to support autoscaling clusrers where the actual resources are provisioned. Even if you use a on-premise cluster without autoscaling you could still benefit by running ProvisioningRequest with the `check-capacity.autoscaling.x-k8s.io` mode, which would check the actual capacity before admitting. Would it work for you?

**Comment by cho-chem** [comment]
Hi @trasc @mimowo . Thank you for your reply. The information you provided is very helpful. I will do some research on it.

**Comment by dafu-wu** [comment]
@mimowo Hi,Has this function been implemented?

**Comment by mimowo** [comment]
Yes, the check-capacity is already supported in Kueue: https://kueue.sigs.k8s.io/docs/admission-check-controllers/provisioning/#provisioningrequestconfig. You will need to use ClusterAutoscaler which is new enough - probably 1.31 is enough, but let me cc @yaroslava-serdiuk who may know more precisely.
