### ISSUE TITLE
manager unclosed action

### ISSUE THREAD

**Issue by serhii-kuzniechykov** [kubernetes-sigs/kueue#2682]
Hello 
Sorry for reporting this small thing.

**What happened**: 
```
helm install kueue kueue/ --create-namespace --namespace kueue-system --set enableCertManager=true
Error: parse error at (kueue/templates/manager/manager.yaml:59): unclosed action
```

**What you expected to happen**:
```helm install kueue kueue/ --create-namespace --namespace kueue-system --set enableCertManager=true
NAME: kueue
LAST DEPLOYED: Tue Jul 23 23:20:02 2024
NAMESPACE: kueue-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Anything else we need to know?**:
```
    resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
```
```
resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10 }}
```
**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: v1.28.2
- Kueue version (use `git describe --tags --dirty --always`): v0.8.0-1-g78783a26-dirty
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`):
- Install tools: Helm
- Others:

**Comment by mbobrovskyi** [comment]
@serhii-kuzniechykov Could you check with last changes? If you still have an issue, please reopen it.
