### ISSUE TITLE
Use klog.KObj or klog.KRef for every log that involves a Queue or Capacity

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#27]
This should help filter logs by namespace.
Although less important for Capacity (because it's ClusterScoped), I prefer to have everything uniform.

/kind cleanup

**Comment by ahg-g** [comment]
Anything blocking this? if not, pls mark with help wanted

**Comment by aether-rootr** [comment]
I want try this issue, please tell me about Capacity.
And I think every code about queue in pkg/queue/
@alculquicondor

**Comment by alculquicondor** [comment]
Yes, let's do it for Capacity (now ClusterQueue) as well.

**Comment by utkarsh-singh1** [comment]
Hi @alculquicondor, I have an interest in this issue, can I get a small brief about this one so it can give a head start.

**Comment by alculquicondor** [comment]
/close

this was already completed
