### ISSUE TITLE
Make internal cert parameters configurable via component config

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#270]
**What would you like to be added**:
Make parameters configurable

**Why is this needed**:
refer to https://github.com/kubernetes-sigs/kueue/pull/265/files#r890449020
**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
I'm ok leaving this for 0.3.0 if you don't have time for this @kerthcet

Otherwise, we can open it up to other contributors?

**Comment by kerthcet** [comment]
Yes, I didn't assign to myself. 
/help

**Comment by tenzen-y** [comment]
@kerthcet @alculquicondor Hi.
I'm interested in this issue. Can I take this?

**Comment by kerthcet** [comment]
> @kerthcet @alculquicondor Hi.
> 
> I'm interested in this issue. Can I take this?
> 
> 

Thanks, plz go ahead.

**Comment by tenzen-y** [comment]
@kerthcet Thanks for your response.
I think that we can extend the `config.kueue.x-k8s.io` API such as the following patterns:

- A

```diff
type Configuration struct {
...
    EnableInternalCertManagement *bool `json:"enableInternalCertManagement,omitempty"`

+   InternalCertManagementServiceName string `json:"internalCertManagementServiceName"`

+   InternalCertManagementSecretName string `json:"internalCertManagementSecretName"`
}
```
- B

```diff
type Configuration struct {
...
    EnableInternalCertManagement *bool `json:"enableInternalCertManagement,omitempty"`

+   InternalCertManagementConfig InternalCertManagementConfig `json:"internalCertManagementConfig"`
}

+type InternalCertManagementConfig struct {
+    ServiceName string `json:"internalCertManagementServiceName"`

+    SecretName string `json:"internalCertManagementSecretName"`
}
```

- C

```diff
type Configuration struct {
...
-   EnableInternalCertManagement *bool `json:"enableInternalCertManagement,omitempty"`

+   InternalCertManagement InternalCertManagement `json:"internalCertManagement"`
}

+type InternalCertManagement struct {
+   Enable *bool `json:"enable"`

+   ServiceName string `json:"internalCertManagementServiceName"`

+   SecretName string `json:"internalCertManagementSecretName"`
}
```

What do you assume API structure?

**Comment by alculquicondor** [comment]
I like C.... although that means that we need to bump the API version to v1alpha2. That's fine. The API is alpha.

**Comment by kerthcet** [comment]
Agree, C is better.

**Comment by alculquicondor** [comment]
Remove it. But please add a release note in the CHANGELOG folder (in a new file for 0.3)

**Comment by tenzen-y** [comment]
> please add a release note in the CHANGELOG folder

It makes sense.

**Comment by ahg-g** [comment]
Late question, why do we need to make them configurable, do we really expect admins to change them?

**Comment by alculquicondor** [comment]
It's an extreme case, but some people might need to. For example, to install kueue in their own namespace, instead of asking an admin to install it. Although with cluster-scoped resources, they might still not have the permissions.

**Comment by alculquicondor** [comment]
But more generally, the container shouldn't make assumptions about in which namespace it is running.

**Comment by ahg-g** [comment]
The namespace is fine to make it configurable, I was mostly referring to the other parameters (service names and such). I am not against it in principle, I just hope we don't clutter the component config API.

**Comment by kerthcet** [comment]
I'm ok with this since we defined these fields in an embedded filed `InternalCertManagement`. If people is really interest with these configurations, he/she can visit this struct. Or just ignore it.

**Comment by ahg-g** [comment]
General suggestion: I would be more conservative moving forward and expose new configs mostly when there is an explicit ask and a valid use case to keep a lean and simple to configure controller. 

Assuming that admins can just ignore those extra configs is not a good UX, if it is exposed, then we are saying that admins should consider configuring it.

**Comment by kerthcet** [comment]
Sorry for that. We haven't release a new version yet, we can still do something. So do you mean configuring them via CLI flags? I mean `ServiceName` and `SecretName `

**Comment by ahg-g** [comment]
I wouldn't change anything now, just a general advise on how to look at CC moving forward.
