### ISSUE TITLE
Update Kubeflow image tag 

### ISSUE THREAD

**Issue by mszadkow** [kubernetes-sigs/kueue#2709]
**What would you like to be cleaned**:

Kubeflow image tag in the current form is based on the manual lookup, because the tag doesn't match semantic version.
``` shell
export KUBEFLOW_IMAGE=kubeflow/training-operator:v1-855e096
```
This requires a manual intervention in multiple places if Kubeflow version has changed.

**Why is this needed**:

That could be updated and automated whenever Kubeflow release process starts include the semantic versioning image tags - https://github.com/kubeflow/training-operator/issues/2155

**Comment by mszadkow** [comment]
Requested here: https://github.com/kubernetes-sigs/kueue/pull/2626#discussion_r1690920760
The PR is not merged yet

**Comment by mbobrovskyi** [comment]
/close 

Due to we already fixed it on https://github.com/kubernetes-sigs/kueue/pull/2880.
