### ISSUE TITLE
[scalability]  TestScalability/WorkloadClasses/large fails occasionally

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2723]
/kind flake

**What happened**:

The scalablity test fails occasionally. Example failed build: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2642/pull-kueue-test-scheduling-perf-main/1816858084459417600

If this is not a systematic regression (it does not seem so), then probably bumping the threshold is ok,

**What you expected to happen**:

No random failures.

**How to reproduce it (as minimally and precisely as possible)**:

Probably run a branch build on CI.

**Anything else we need to know?**:

failure message:
```
{Failed  === RUN   TestScalability/WorkloadClasses/large
    checker_test.go:117: Average wait for admission 11213ms is more then expected 11000ms
--- FAIL: TestScalability/WorkloadClasses/large (0.00s)
```

**Comment by trasc** [comment]
This is a duplicate of #2708

**Comment by mimowo** [comment]
Ah, I missed it, thanks
/close
