### ISSUE TITLE
[kueuectl] the kueuectl examples don't work as copy-paste

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2790]
**What happened**:

I create a CQ with the command according to help:
```
kubectl-kueue create clusterqueue my-cluster-queue --nominal-quota=alpha:cpu=9;memory=36Gi
```
but it ignores `memory=36Gi` without any warning / error.

This leads to subtle problems as users of `kueuectl` would often not inspect the yaml.

**What you expected to happen**:

I would expect the examples to work as copy-paste.

**How to reproduce it (as minimally and precisely as possible)**:

Run example from `kueuectl create cq --help`

**Anything else we need to know?**:

I think we could consider updating the examples to escape ";",  or consider other delimiter choices which don't require escaping.

**Comment by mbobrovskyi** [comment]
@mimowo Try to use quotes:

```bash
kubectl-kueue create clusterqueue my-cluster-queue --nominal-quota="alpha:cpu=9;memory=36Gi"
```

**Comment by mimowo** [comment]
> @mimowo Try to use quotes:

This works, it would be great to adjust the help examples accordingly
