### ISSUE TITLE
Make kueue statically linked

### ISSUE THREAD

**Issue by pspurlock** [kubernetes-sigs/kueue#2801]
**What would you like to be added**:

Make kueue binary statically linked

**Why is this needed**:

This ensures that no other dependencies would be needed when using on different OS like RHEL.

**Completion requirements**:

Currently this can be done building from source with `CGO_ENABLED=0 make kueuectl`

**Comment by pspurlock** [comment]
@ktarplee

**Comment by kannon92** [comment]
Are you asking that just kueuectl be made static?
