### ISSUE TITLE
Add the finalizer via webhook when creating resourceFlavor

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#283]
**What would you like to be added**:
In https://github.com/kubernetes-sigs/kueue/pull/263, we add the finalizer in `Reconcile`, there's still a time resourceFlavor doesn't have the finalizer, we'd like to avoid this by webhook mutation.

**Why is this needed**:

**Completion requirements**:
It's a follow up after https://github.com/kubernetes-sigs/kueue/pull/263

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by ahg-g** [comment]
I guess this is due now

**Comment by kerthcet** [comment]
I'll follow this ASAP.
