### ISSUE TITLE
Add a guide for deleting ClusterQueues

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2835]
**What would you like to be added**:

A task page for how to delete a ClusterQueue that has running workloads.

Alternatives include using the `kubectl kueue` plugin or directly using `kubectl edit`.

**Why is this needed**:

It's not immediately obvious what `kubectl delete clusterqueue` does. It currently just looks like the command is hanging.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by mbobrovskyi** [comment]
Ah, I see. Thanks for the explanation.
