### ISSUE TITLE
Flaky: Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job Should allow fetching information about pending workloads in ClusterQueue

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2924]
**What happened**:

Flaky test on `periodic-kueue-test-e2e-main-1-29`:
`Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job Should allow fetching information about pending workloads in ClusterQueue`

**What you expected to happen**:

To pass consistently

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-e2e-main-1-29/1828542136862117888

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mbobrovskyi** [comment]
Is it duplicate for https://github.com/kubernetes-sigs/kueue/issues/2920?

**Comment by alculquicondor** [comment]
Yes, thanks!

/close
