### ISSUE TITLE
deployment webhook is broken 

### ISSUE THREAD

**Issue by alaypatel07** [kubernetes-sigs/kueue#2987]
**What happened**:
1. Installed kueue using the following commands:
```
IMAGE_REGISTRY=<registry> make  image-local-push deploy
```
2. Ran patch command to try out the visibility api
```
 kubectl patch -n kueue-system deployment kueue-controller-manager --type='json' -p='[

  {
    "op": "add",
    "path": "/spec/template/spec/containers/0/args/-",
    "value": "--feature-gates=VisibilityOnDemand=true"
  }
]'
```

The error failed with 
```
Error from server (InternalError): Internal error occurred: failed calling webhook "vdeployment.kb.io": failed to call webhook: the server could not find the requested resource
```
3. Tried to create busybox deployment, failed with the same error

**What you expected to happen**:
Create and update calls to deployment should work.

**How to reproduce it (as minimally and precisely as possible)**:
1. checkout main
2. run `IMAGE_REGISTRY=<registry> make  image-local-push deploy`
3. create or update deployment as noted above

**Anything else we need to know?**:
This PR #2813 added a validating and mutating webhook for deployments, but it is not registered by default

**Environment**:
- Kubernetes version (use `kubectl version`): tested in 1.30.3 and 1.31.0
- Kueue version (use `git describe --tags --dirty --always`): main at commit  0bcde8c82e6a769bf75e3d195b65d18dbb6e2bf6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alaypatel07** [comment]
It seems like importing deployment https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/jobs/jobs.go#L28 should solve the issue.

Trying it out in local environment

**Comment by alaypatel07** [comment]
```
diff --git a/config/components/manager/controller_manager_config.yaml b/config/components/manager/controller_manager_config.yaml
index c0a9f597..9850c3fa 100644
--- a/config/components/manager/controller_manager_config.yaml
+++ b/config/components/manager/controller_manager_config.yaml
@@ -48,15 +48,16 @@ integrations:
   - "kubeflow.org/pytorchjob"
   - "kubeflow.org/tfjob"
   - "kubeflow.org/xgboostjob"
-#  - "pod"
+  - "pod"
+  - "deployment"
 #  externalFrameworks:
 #  - "Foo.v1.example.com"
-#  podOptions:
-#    namespaceSelector:
-#      matchExpressions:
-#        - key: kubernetes.io/metadata.name
-#          operator: NotIn
-#          values: [ kube-system, kueue-system ]
+  podOptions:
+    namespaceSelector:
+      matchExpressions:
+        - key: kubernetes.io/metadata.name
+          operator: NotIn
+          values: [ kube-system, kueue-system ]
```

enabling the above configuration made it work for me.

```
# kubectl patch -n kueue-system deployment kueue-controller-manager --type='json' -p='[
  {
    "op": "add",
    "path": "/spec/template/spec/containers/0/args/-",
    "value": "--feature-gates=VisibilityOnDemand=true"
  }
]'
deployment.apps/kueue-controller-manager patched
```

So either the pod framework should be enabled or webhook configuration should be disable, one or the other should solve this issue in main branch.

**Comment by mimowo** [comment]
The original intention was to enforce that the pod integration is enabled. From https://github.com/kubernetes-sigs/kueue/issues/2717#issue-2435374397: "introduce a dedicated Deployment integration, and validate that it can only be enabled when pod integration is enabled".

Here was the preparatory PR: https://github.com/kubernetes-sigs/kueue/pull/2768. However, I'm not sure if the mechanism was eventually used. Do you know @vladikkuzn @trasc ?

@alaypatel07 would enforcing the dependency solve this issue for you?
