### ISSUE TITLE
Visibility Test Flake

### ISSUE THREAD

**Issue by gabesaba** [kubernetes-sigs/kueue#2990]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2989/pull-kueue-test-e2e-main-1-31/1831630396710719488

```
Summarizing 1 Failure:
  [FAIL] Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job [It] Should allow fetching information about pending workloads in ClusterQueue
  /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/visibility_test.go:186
```

**Comment by mimowo** [comment]
/kind flake
/cc @PBundyra 
(as the feature owner)
/cc @mbobrovskyi @trasc 
in case you have capacity to look at it
