### ISSUE TITLE
Optimize waiting for API to poll REST mapper only when the CRD is installed

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3014]
**What would you like to be added**:

An optimization to the CRD tracker https://github.com/kubernetes-sigs/kueue/blob/7fed1235a645da375c332c470ecd4b9be6971322/pkg/controller/jobframework/setup.go#L123 to start the polling for REST mapper only when the CRD is installed.

**Why is this needed**:

- reduce the amount of logging for not installed CRDs
- shorten the time for the API to be ready - currently due to the exponential backoff the detection of API is likely to take 2min (max period). if we start active polling after the CRD is installed the REST mapper will be detected quickly.

**Comment by mimowo** [comment]
This is a follow up to https://github.com/kubernetes-sigs/kueue/pull/2574
/cc @varshaprasad96

**Comment by tenzen-y** [comment]
Once we migrate manually polling to reconcilers (https://github.com/kubernetes-sigs/kueue/issues/2837), this is not needed Isn't it?

**Comment by mimowo** [comment]
I would rather say this is a duplicate as I missed the other one. 
/close
