### ISSUE TITLE
Add integration tests for detecting CRD installed after Kueue started

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3015]
**What would you like to be cleaned**:

This is a follow up to https://github.com/kubernetes-sigs/kueue/pull/2574. 

**Why is this needed**:

To gain confidence the mechanism works as expected since there are pieces of the code which are hard to cover with unit tests.

**Comment by tenzen-y** [comment]
That makes sense. Since we implemented the watcher by hand, we should keep to prove that the watcher works fine.
