### ISSUE TITLE
PRs opened by dependabot for  /hack/internal/tools fail for non-breaking changes

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3062]
**What would you like to be cleaned**:

PRs opened by dependabot should not be failing, unless for breaking changes in the libraries. In our case they are failing for non-breaking changes. Examples:
- https://github.com/kubernetes-sigs/kueue/pull/3060
- https://github.com/kubernetes-sigs/kueue/pull/3061

Most often they fail on `pull-kueue-verify-main` because the bump is inconsitent. We bump in `/hack/internal/tools`, but not at the root.

A research of potential solutions is welcome. One idea is not to depend on the top-level dir in `/hack/internal/tools` by replace (which is not recognized by dependabot: https://github.com/kubernetes-sigs/kueue/blob/669d73d40e058c237c3ff3f8b820b75b1dc63a08/hack/internal/tools/go.mod#L25).

**Why is this needed**:

The PRs opened by dependabot still require manual chore, more than needed.

**Comment by mbobrovskyi** [comment]
The problematic part that we are using [cmd/kueuectl](https://github.com/kubernetes-sigs/kueue/tree/669d73d40e058c237c3ff3f8b820b75b1dc63a08/cmd/kueuectl) package on [hack/internal/tools/kueuectl-docs](https://github.com/kubernetes-sigs/kueue/tree/669d73d40e058c237c3ff3f8b820b75b1dc63a08/hack/internal/tools/kueuectl-docs). And here we are using another `go.mod` so we need to somehow add `cmd/kueuectl` as dependency.

We are using:

https://github.com/kubernetes-sigs/kueue/blob/669d73d40e058c237c3ff3f8b820b75b1dc63a08/hack/internal/tools/go.mod#L25

And when we are updating root go.mod we also should update it on hack/internal/tools/go.mod too. We can't configure dependabot to update it in both places.

So I would like to propose to move `hack/internal/tools/kueuectl-docs` to `cmd/kueuectl-docs`. It should resolve our problem.

**Comment by mbobrovskyi** [comment]
The https://github.com/kubernetes-sigs/kueue/blob/669d73d40e058c237c3ff3f8b820b75b1dc63a08/hack/internal/tools/go.mod#L25
depends only for `hack/internal/tools/kueuectl-docs`. So I think moving [kueuectl-docs](https://github.com/kubernetes-sigs/kueue/tree/main/hack/internal/tools/kueuectl-docs) to `cmd/kueuectl-docs` and using for it root `go.mod` dependencies should resolve this problem.

**Comment by tenzen-y** [comment]
As an alternative, I'm wondering if we can put all directories in a single dependabot directries field.

https://github.com/kubernetes-sigs/kueue/blob/ac77deaf14fab5955dab42f6c8196b860c9ebcbd/.github/dependabot.yml#L6-L9

**Comment by mbobrovskyi** [comment]
But we already have it.
