### ISSUE TITLE
[ClusterQueue] Provide more details about the mis-configuration in the message for Active=False

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3099]
**What would you like to be added**:

More details in the message for the "Active=False" condition for ClusterQueue in case of mis-configuration.

Currently we have the reason field determined here: https://github.com/kubernetes-sigs/kueue/blob/82b62260d6e12d4cd1dddbdc79af711da1b1dc73/pkg/cache/clusterqueue.go#L234, but the message remains generic "Can't admit new workloads."

**Why is this needed**:

- To phrase the configuration issue in a more human-readable way, I find "FlavorIndependentAdmissionCheckAppliedPerFlavor" is hard to understand
- To provide more details which AdmissionCheck or ResourceFlavor is mis-configured, which can be handy when there are more than one.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
+1

**Comment by tenzen-y** [comment]
+1

Granular messages would always be helpful for actual cluster operation.

**Comment by trasc** [comment]
The message can be made more human readable and maybe include the missing flavor name, AC name and so on. Trimming it should not be necessary since it can hold 32K.

**Comment by trasc** [comment]
/retitle [ClusterQueue] Provide more details about the mis-configuration in the message for Active=False
