### ISSUE TITLE
Place webhook files under a separate folder

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#311]
**What would you like to be added**:
Currently we have webhooks for each type of Kueue Objs, maybe it's better to place them under a separate folder like `apis/kueue/webhooks/`, which seems more clearly.

**Why is this needed**:
Make the project more clearly.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
cc @ahg-g @alculquicondor For advices.

**Comment by alculquicondor** [comment]
+1
