### ISSUE TITLE
Expose Flavors in LocalQueue Status

### ISSUE THREAD

**Issue by KPostOffice** [kubernetes-sigs/kueue#3122]
**What would you like to be added**:
Add a status field to LocalQueue which lists out available flavors

**Why is this needed**:
I would like to be able to see the resource flavors available in each LocalQueue that I have access to

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by mimowo** [comment]
Updating the flavors in status will eat QPS to update the information which is just one step away so I would prefer to understand what is the use-case.

Would it work for you composing these queries:
```sh
CQ_NAME=$(kubectl get lq/user-queue -ojson | jq -r .spec.clusterQueue)
kubectl get cq/$CQ_NAME -ojson | jq .spec.resourceGroups\[\].flavors\[\].name
```
If this works, maybe just need a docs update for "common tasks", or extend kueuectl?

/cc @mwielgus @alculquicondor

**Comment by alculquicondor** [comment]
> Updating the flavors in status will eat QPS to update the information which is just one step away so I would prefer to understand what is the use-case.

We already have API calls to populate the usage, so this wouldn't add additional calls.

> Would it work for you composing these queries

This might not work, depending on the RBAC rules, as users might not have read access to ClusterQueues.

**Comment by mimowo** [comment]
I see, sounds good

**Comment by tenzen-y** [comment]
> > Would it work for you composing these queries
> 
> This might not work, depending on the RBAC rules, as users might not have read access to ClusterQueues.

The RBAC permission deeply depends on the organization's policies. So, it might be better to add troubleshooting guide or any dedicated task document how to obtain the tied resourceFlavors.

**Comment by KPostOffice** [comment]
> This might not work, depending on the RBAC rules, as users might not have read access to ClusterQueues.

This is exactly the issue we are facing. Letting the users know the flavors is useful since it can give an idea of the capabilities provided by a LocalQueue. (i.e. one flavor may have newer GPUs)

**Comment by mimowo** [comment]
A small follow up for TAS: https://github.com/kubernetes-sigs/kueue/issues/4534

**Comment by mimowo** [comment]
cc @varshaprasad96 @KPostOffice this feature was introduced before we had the visibility API, which can expose some visibility information "on-demand" without duplicating the information (as currently the feature requires duplication of information). Thus, we are considering to deprecate and eventually drop this feature: https://github.com/kubernetes-sigs/kueue/issues/6777

Let us know if you still find this feature useful, or would like to work on replacing the feature as visibility on-demand endpoint.
