### ISSUE TITLE
Dedicated documentation folder for running Jobs in MultiKueue

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3134]
**What would you like to be added**:

A dedicated docs folder to group together sub-pages of running different Job CRDs on MultiKueue.

Sub-pages documenting Job and JobSet could be the starting point as supported in 0.8.1.

**Why is this needed**:

We already support JobSet, Job, MPIJob, Training Operator, but all the jobs have different level of support, so I think a dedicated page per CRD is justified. Running workloads on MultiKueue is complicated, so having the information in one place rather than scattered will be useful.

It would be a nice place to host the information for the content in https://github.com/kubernetes-sigs/kueue/pull/3126.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
That sounds good to me. Is there any recommendation for the directory structure?
I'm wondering if we can create 2 directories:

- /Tasks/Run Workloads/Single Cluster
- /Tasks/Run Workloads/Multiple Cluster

Any thoughts?

**Comment by mimowo** [comment]
>  Is there any recommendation for the directory structure?

I'm proposing in the PR review to just have "/Tasks/Run Workloads/Using MultiKueue" folder, and under it put: Job, JobSet, TrainingOperator/MPIJob.

> I'm wondering if we can create 2 directories:

This could work, but it will mean one more level of nesting (click) to get to the most typical places (single jobs). Also, the MultiKueue folder may not be needed in the long run if we have full support for managedBy across all CRDs (one day).

**Comment by tenzen-y** [comment]
> > Is there any recommendation for the directory structure?
> 
> I'm proposing in the PR review to just have "/Tasks/Run Workloads/Using MultiKueue" folder, and under it put: Job, JobSet, TrainingOperator/MPIJob.

In that case, I would propose using the "/Tasks/Run Workloads/Job Dispatching to MultiCluter" since the "MultiKueue" is no generic term. It would be helpful to look for the page for the MultiCluster support.

**Comment by mimowo** [comment]
"Job Dispatching to MultiCluster" is fine for me, but how about "Multi-cluster Job dispatching"?

**Comment by tenzen-y** [comment]
> "Job Dispatching to MultiCluster" is fine for me, but how about "Multi-cluster Job dispatching"?

SGTM I just wanted to say that using the generic term would be better.

**Comment by mszadkow** [comment]
@mimowo what do you think is needed to close this issue?

**Comment by mimowo** [comment]
/close
We can open another issue or directly a PR if something needs more care.
