### ISSUE TITLE
Remove webhook builder when controller-runtime allows overriding a mutation handler

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#3137]
**What would you like to be cleaned**:

Remove `pkg/controller/jobframework/webhook/builder.go` when https://github.com/kubernetes-sigs/controller-runtime/pull/2932 is merged and released.

**Why is this needed**:

We duplicated the file to be able to provide a fix in Kueue faster in #3132

**Comment by alculquicondor** [comment]
Do not assign this issue yet, because #3132 is not merged yet.

**Comment by mimowo** [comment]
Closing in favor of https://github.com/kubernetes-sigs/kueue/issues/3469, as with the controller-runtime fix we can drop also our defaulter altogether.
