### ISSUE TITLE
[Flaky integration test] SchedulerWithWaitForPodsReady Long PodsReady timeout Should block admission of one new workload if two are considered in the same scheduling cycle

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#3149]
**What happened**:
Scheduler with WaitForPodsReady Suite: [It] SchedulerWithWaitForPodsReady Long PodsReady timeout Should block admission of one new workload if two are considered in the same scheduling cycle

```
{Timed out after 5.001s.
Not enough workloads are pending
Expected
    <int>: 1
to equal
    <int>: 2 failed [FAILED] Timed out after 5.001s.
Not enough workloads are pending
Expected
    <int>: 1
to equal
    <int>: 2
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/scheduler/podsready/scheduler_test.go:177 @ 09/26/24 16:12:49.608
}
```

**What you expected to happen**:
No random failure.

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/3148/pull-kueue-test-integration-main/1839333717571538944

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mimowo** [comment]
Looks like another occurrence: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-integration-main/1840270117556981760
