### ISSUE TITLE
Make LossLessDefaulter selective to only prevent dropping fields outside of schema

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3174]
**What would you like to be added**:

Investigate making the LossLessDefaulter in Kueue to only prevent dropping fields outside of schema. 
This is a follow up from the discussion: https://github.com/kubernetes-sigs/kueue/pull/3132#discussion_r1782255326

And follow up to the issue: https://github.com/kubernetes-sigs/kueue/issues/2878

**Why is this needed**:

* Long term we may want to remove some fields in Kueue webhooks, and it would be hard with the current LossLessDefaulter
* Making LossLessDefaulter selective could possibly let us promote it as an opt-in defaulter in controller-runtime, allowing for:
  - reduced maintenance cost by moving from Kueue to controller-runtime
  - allow sharing the solution with other projects so that they don't need to reinvent the wheel

**Completion requirements**:

Investigate if this is feasible. and what is the implementation complexity, prototype.

**Comment by mimowo** [comment]
/assign @tenzen-y 
per comment https://github.com/kubernetes-sigs/kueue/pull/3132#discussion_r1783163941
/cc @alculquicondor

**Comment by tenzen-y** [comment]
Sorry. I did not want to indicate taking this issue.
/unassign

**Comment by mimowo** [comment]
Sorry, I misread your message which was clear. Thanks for clarifying!
Anyway, the issue is open for contributions.

**Comment by mimowo** [comment]
/close
we don't need this in Kueue as there is fix in controller-runtime to be released, issue to track using the fix: https://github.com/kubernetes-sigs/kueue/issues/3469
