### ISSUE TITLE
Release-0.8: Fix PartialAdmission bugs

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#3197]
**What happened**:
Recently, we have fixed some PartialAdmission bugs, but those PRs were not cherry picked to release-0.8.
So, after summarizing all PartialAdmission bugs here, we will cherry-pick those to release-0.8 branch.

candidates:
- [x] https://github.com/kubernetes-sigs/kueue/pull/3152
- [x] https://github.com/kubernetes-sigs/kueue/pull/2826
- [x] https://github.com/kubernetes-sigs/kueue/pull/3118
- [x] https://github.com/kubernetes-sigs/kueue/pull/3153

**What you expected to happen**:
Fixed PartialAdmission bugs in the release-0.8 branch as well.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mimowo** [comment]
I think we also need:
- https://github.com/kubernetes-sigs/kueue/pull/3118
- https://github.com/kubernetes-sigs/kueue/pull/3153

cc @trasc would you like to prepare the cherry-picks?

**Comment by tenzen-y** [comment]
> I think we also need:
> 
> * [[workload]Fix resource consumption computation for partially admitted workloads #3118](https://github.com/kubernetes-sigs/kueue/pull/3118)
> * [[batch/job] Fix parallelism restoration after partial admission. #3153](https://github.com/kubernetes-sigs/kueue/pull/3153)
> 
> cc @trasc would you like to prepare the cherry-picks?

Thank you for pointing those out. I updated the description.

**Comment by trasc** [comment]
> cc @trasc would you like to prepare the cherry-picks?

Sure
/assign

**Comment by tenzen-y** [comment]
@trasc Thanks!
/close
