### ISSUE TITLE
[Flaky integration test] SchedulerWithWaitForPodsReadyNonblockingMode Long PodsReady timeout Should not block admission

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3233]
/kind flake

**What happened**:

Test failed: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-main/1844256892138819584
testgring link: https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-integration-main

![image](https://github.com/user-attachments/assets/d6fce02c-d9b5-47ef-a3ab-14819378fe18)

**What you expected to happen**:

No random failures

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the build.

**Anything else we need to know?**:

```
{Timed out after 5.001s.
Not enough workloads are pending
Expected
    <int>: 1
to equal
    <int>: 2 failed [FAILED] Timed out after 5.001s.
Not enough workloads are pending
Expected
    <int>: 1
to equal
    <int>: 2
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/scheduler/podsready/scheduler_test.go:635 @ 10/10/24 06:15:45.64
}
```

**Comment by mimowo** [comment]
/assign @IrvingMg 
who is also looking at the similarly looking issue: https://github.com/kubernetes-sigs/kueue/issues/3212

**Comment by mimowo** [comment]
/cc @mbobrovskyi 
who may have useful knowledge about the tests

**Comment by mbobrovskyi** [comment]
> /assign @IrvingMg who is also looking at the similarly looking issue: #3212

I think it's a duplicate of https://github.com/kubernetes-sigs/kueue/issues/3212.

**Comment by mimowo** [comment]
I suspect the same, but I wasn't sure as these are 2 different tests. We can keep both open for now, and close as we fully understand the issue and confirm it is the same root cause.

**Comment by mbobrovskyi** [comment]
> In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/scheduler/podsready/scheduler_test.go:635 @ 10/10/24 06:15:45.64


Looks like the error in the same line. So I think it's duplicate.

**Comment by mbobrovskyi** [comment]
And the test name also the same.

**Comment by mimowo** [comment]
Ah, yes my mistake. I thought the names are different
/close
