### ISSUE TITLE
[kjobctl] Publish a dedicated image to run kjobctl slurm init container

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3243]
**What would you like to be added**:

To simplify the development of the slurm support in kjobctl. Also, not to use outdated images.
The new image could be generic for kjobctl , or specific for the slurm support (maybe `kjobctl-slurm`), to be discussed.

This is related also to https://github.com/kubernetes-sigs/kueue/issues/2778.

**Why is this needed**:

The discussion [here](https://github.com/kubernetes-sigs/kueue/pull/3072#discussion_r1800756917). 
The available images in registry.k8s.io (see https://explore.ggcr.dev/?repo=registry.k8s.io) are very limited in tooling, or old. We could not find a new image which would have: `bash` and `nslookup` (with `bind-tools`).

**Comment by mbobrovskyi** [comment]
/close

Due to moved to separate repo https://github.com/kubernetes-sigs/kjob/issues/6.
