### ISSUE TITLE
Support MPIJob managedBy feature for the MultiKueue

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#3257]
**What would you like to be added**:
If we want to use the current MPIJob MultiKueue feature, we need to uninstall the mpi-operator from the management cluster.
But, since the [mpi-operator v0.6.0](https://github.com/kubeflow/mpi-operator/releases/tag/v0.6.0), we started to support the managedBy feature similar to the batch/v1 Job.

Hence, we want to support it by implementing in the following:

1. Implement the `IsJobManagedByKueue`: https://github.com/kubernetes-sigs/kueue/blob/4199c9dd9ce89636eb4e72f5cebb3c9adfba3f0c/pkg/controller/jobs/mpijob/mpijob_multikueue_adapter.go#L89-L91
2. Implement the defaulting webhoooks similar to [Job](https://github.com/kubernetes-sigs/kueue/blob/4199c9dd9ce89636eb4e72f5cebb3c9adfba3f0c/pkg/controller/jobs/job/job_webhook.go#L84-L102) and [JobSet](https://github.com/kubernetes-sigs/kueue/blob/4199c9dd9ce89636eb4e72f5cebb3c9adfba3f0c/pkg/controller/jobs/jobset/jobset_webhook.go#L72-L91): 

And other needed implementations to support it if it exists.

**Why is this needed**:
The MPIJob with managed feature allows us to install the mpi-operator to management and worker clusters so that we can easily introduce multi-cluster MPIJob dispatching and give the possibility of running the MPIJob in the management cluster as well.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
cc: @mimowo @mszadkow

**Comment by mszadkow** [comment]
https://github.com/kubernetes-sigs/kueue/pull/3274

**Comment by tenzen-y** [comment]
/reopen 
For documentation.

**Comment by tenzen-y** [comment]
Closed by https://github.com/kubernetes-sigs/kueue/pull/3316
/close
