### ISSUE TITLE
Can the event type in insufficient resource wait situations be changed from `Normal` to `Warning`?

### ISSUE THREAD

**Issue by kebe7jun** [kubernetes-sigs/kueue#3263]
**What would you like to be added**:

Now, when resources are insufficient and cannot be scheduled, an event will be recorded in the Workload, but the event type is Normal.

```
Events:
  Type    Reason   Age   From             Message
  ----    ------   ----  ----             -------
  Normal  Pending  11s   kueue-admission  couldn't assign flavors to pod set worker: insufficient quota for cpu in flavor default-flavor in ClusterQueue
```

In our system, we will focus on `Warning` type events, so `Normal` is likely to be filtered out, but obviously, this is likely to be the culprit of the application being unable to start.

So, I was wondering if I could change the type here to Warning?

https://github.com/kubernetes-sigs/kueue/blob/9332a5a3d911f191de262e41fe0508e9bccc2d77/pkg/scheduler/scheduler.go#L695

**Why is this needed**:

Changing its type to `Warning` will increase our attention and help users more quickly troubleshoot the reason why the workload cannot be started.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kebe7jun** [comment]
I submitted a PR for this issue, feel free to discuss.

**Comment by alculquicondor** [comment]
Yeah, it sounds reasonable to match the same type as kube-scheduler.
