### ISSUE TITLE
Make kueue image multiarch

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#327]
**What would you like to be added**:

Make kueue image multiarch for x86 and arm

**Why is this needed**:

To be able to run in any environment.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@alculquicondor Hi.
I'm interested in this. Does this mean [multi-platform image](https://docs.docker.com/build/buildx/multiplatform-images/)?

**Comment by alculquicondor** [comment]
Yes :)

You need to find a way to do that from the Makefile and Dockerfile

**Comment by tenzen-y** [comment]
@alculquicondor Thanks for clarifying. Can I take this?

**Comment by alculquicondor** [comment]
Yes, just write `/assign` in a comment.
