### ISSUE TITLE
Validate Workload.spec.admission on webhook

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#328]
**What would you like to be added**:

The following validations should apply:

- The clusterQueue should be a valid object name.
- The list of podSetFlavors should match the podSets names.
- Each resourceName should be listed in the pod spec, although it might be too cumbersome to validate, so we could ignore it.
- Each flavorName should be a valid object name.

Also validate that, once set, the contents of the admission are immutable, except that it can be set to nil.

**Why is this needed**:

To prevent accidental misuse of this field by administrators.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
I wonder if we should allow parts of podsets to run first when out of resources, then we can release the resources for the left podsets to run. For podgroup pods, we should have a different set of logic.

**Comment by kerthcet** [comment]
And this can be configured.
