### ISSUE TITLE
Ensure the err is surfaced in e2e/integration tests to improve debuggability

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3300]
**What would you like to be cleaned**:

We use this pattern in many places :

```golang
if err := k8sClient.Get(ctx, wlLookupKey, createdWorkload); err != nil {
return false
}
```

We prefer to replace it with something like:
```golang
gomega.Eventually(func(g gomega.Gomega) {
	g.Expect(k8sClient.Get(ctx, wlLookupKey, createdWorkload)).Should(gomega.Succeed())
	...
}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
```

This is a follow up to the discussion here: https://github.com/kubernetes-sigs/kueue/pull/3284#discussion_r1814544537

**Why is this needed**:

To improve debuggability.

**Comment by mbobrovskyi** [comment]
/assign

I already started working on it before.
