### ISSUE TITLE
Use ResourceFlavor.metadata.labels instead of ResourceFlavor.labels

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#334]
**What would you like to be cleaned**:

Since we are already thinking of v1beta2, we could consider deleting the field `.labels` and use `.metadata.labels` instead.

**Why is this needed**:

Users could be confused trying to use `.metadata.labels` which wouldn't give the results they want.

I can't think of a use case where a user would want to use `metadata.labels` without wanting them to match workloads' node selectors.

**Comment by thisisprasad** [comment]
The ResourceFlavor struct field `.labels` is currently being referred/used by:
1. `cache`
2. `Snapshot` unit tests
3. `Job controller`
4. `Scheduler` and its unit tests
5. resourceFlavor `webhook validation`

The changes to `resourceFlavor` struct would require changes in the above places.

**Comment by thisisprasad** [comment]
I would like to work on this
/assign

**Comment by alculquicondor** [comment]
Thanks @thisisprasad

**Comment by alculquicondor** [comment]
Any progress on this?

**Comment by thisisprasad** [comment]
Working on the changes. Midway through. No blockers till now.

**Comment by thisisprasad** [comment]
I think we should also update the documentation related to resourceFlavors as the `labels` field is repositioned. Changes would be required in `/docs/concepts/` and `/docs/tasks/` directories.

Will it be fine to update the documentation in the same PR as of code?

**Comment by alculquicondor** [comment]
Yes, that's fine and I would encourage it :)

**Comment by alculquicondor** [comment]
Any progress? Since pretty much everything else is ready for 0.2.0 and this is low priority, we can leave it for 0.3.0

**Comment by thisisprasad** [comment]
I've raised PR for this.

Apologies for the delay.
