### ISSUE TITLE
[MultiKueue docs] Add a subpage for running a batch/Job

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3357]
**What would you like to be added**:

A sub-page here for batch/job. In particular mention the role of MultiKueueBatchJobWithManagedBy.

![image](https://github.com/user-attachments/assets/b6342c65-b1ae-472a-a2e3-e776fd1b23ee)

**Why is this needed**:

For guidance how to run batch/Jobs on MultiKueue depending on the configuration.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Docs update

**Comment by mimowo** [comment]
cc @tenzen-y

**Comment by tenzen-y** [comment]
> cc @tenzen-y

SGTM
