### ISSUE TITLE
Delete redundant retry logic in multikueue controller

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#3359]
**What would you like to be cleaned**:
Multikueue controller sets AdmissionCheck to Pending after it was set to Retry. Workload controller already does, after the #3323 

**Why is this needed**:
Cleanup

**Comment by tenzen-y** [comment]
@PBundyra Will you work on this part of https://github.com/kubernetes-sigs/kueue/issues/3231?
Or separately?

**Comment by PBundyra** [comment]
> @PBundyra Will you work on this part of #3231? Or separately?

I believe it should be approached separately

**Comment by tenzen-y** [comment]
> > @PBundyra Will you work on this part of #3231? Or separately?
> 
> I believe it should be approached separately

That makes sense. In that case, you can focus on #3231, and anyone can help with this issue.

**Comment by mimowo** [comment]
FYI I summarized the redundant code in the https://github.com/kubernetes-sigs/kueue/issues/3351#issuecomment-2444059575.
