### ISSUE TITLE
[kjobctl] Provide the name of the executed script in the "describe slurm"

### ISSUE THREAD

**Issue by BluValor** [kubernetes-sigs/kueue#3362]
**What would you like to be added**:
Add name of the source file of the script executed when creating a slurm job to the "describe slurm" output.

**Why is this needed**:
"describe slurm" currently prints out the content of the executed script, but not the name of the source file of the script.

**Completion requirements**:
The output of the "describe slurm" command should contain either:
- the name of the source file of the script
- the whole path to the source file of the script (aka the default argument of the "create slurm" command)

**Comment by mimowo** [comment]
Cc @mbobrovskyi

**Comment by mimowo** [comment]
Cc @mwysokin

**Comment by mwysokin** [comment]
@BluValor Could you give a bit more details about why you think it's needed or why this would provide an improved UX?

**Comment by BluValor** [comment]
The motivation is:
- it makes it easier for the user to identify the work the job does without reading the script itself
- use cases in scripts using the kjob - pulling the name - also for identification purposes

**Comment by mbobrovskyi** [comment]
Currently, we can't display this information because the Slurm builder only generates the script. Since we're using batch/Job for Slurm, I think we can use a label or annotation to provide the script name, like `kjobctl.x-k8s.io/slurm-script-name`.

@mwysokin WDYT?

**Comment by mwysokin** [comment]
SGTM 🖖 but... I'm not sure if `kjobctl.x-k8s.io/slurm-script-name` is the best name for the annotation. I think the best person to make that decision would be @mwielgus.
