### ISSUE TITLE
[kjobctl] Make the output of the "describe job" command a viable yaml

### ISSUE THREAD

**Issue by BluValor** [kubernetes-sigs/kueue#3363]
**What would you like to be added**:
Make the output of the "describe job" command a viable yaml (parsable while maintaining the same intended structure).

**Why is this needed**:
The output of this command is currently human readable but cannot be used with scripts easily. 

**Completion requirements**:
The output of the "describe job" command should be parsable by yaml. The listings should be parsed properly.
It would also be fine it this option is hidden under a flag (like "-o yaml").

**Comment by mbobrovskyi** [comment]
Did you try `kjobctl list slurm name -o yaml`?

**Comment by BluValor** [comment]
> Did you try `kjobctl list job name -o yaml`?

Haven't found this one, thank you. :)

It would still be nice to have this option for the "describe job", but it seems this will be enough for my use case.

Feel free to close this issue as resolved.

**Comment by mbobrovskyi** [comment]
We are aiming to make this as similar to `kubectl` as possible. Note that `kubectl describe` does not support the `-o yaml` option.

@mimowo @mwysokin WDYT?
