### ISSUE TITLE
Flaky E2E Test: Pod groups when Single CQ should admit group that fits

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#3368]
/kind flake

**What happened**:
Failed End To End Suite: kindest/node:v1.29.4: [It] Pod groups when Single CQ should admit group that fits.

```
{Timed out after 5.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:685 with:
Expected workload to be finalized
Expected
    <[]string | len:1, cap:4>: [
        "kueue.x-k8s.io/resource-in-use",
    ]
to be empty failed [FAILED] Timed out after 5.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:685 with:
Expected workload to be finalized
Expected
    <[]string | len:1, cap:4>: [
        "kueue.x-k8s.io/resource-in-use",
    ]
to be empty
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:130 @ 10/30/24 05:16:41.103
}
```

**What you expected to happen**:
No errors happened

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3367/pull-kueue-test-e2e-main-1-29/1851491513939267584

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mbobrovskyi** [comment]
/reopen

Due to https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3367/pull-kueue-test-e2e-main-1-29/1851518472048087040.

**Comment by tenzen-y** [comment]
Isn't this reoccurring, right?
/reopen

**Comment by mbobrovskyi** [comment]
> Isn't this reoccurring, right? /reopen

You mean here https://github.com/kubernetes-sigs/kueue/pull/3384? No, it happens before.

**Comment by tenzen-y** [comment]
> You mean here #3384? No, it happens before.

Oh, I see. Thank you for letting me know.
I was missed the PR.

/close
