### ISSUE TITLE
TAS: support all Job CRDs (including Pods)

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3372]
**What would you like to be added**:

Add support for all Job CRDs. Currently we have Job and JobSet covered.

This consists two parts:
- computation of the TopologyRequest as in [here](https://github.com/kubernetes-sigs/kueue/blob/1e6d6cc6ae5124bd0317adf34724656bdbe7a812/pkg/controller/jobs/jobset/jobset_controller.go#L124)
-  validation as in [here](https://github.com/kubernetes-sigs/kueue/blob/1e6d6cc6ae5124bd0317adf34724656bdbe7a812/pkg/controller/jobs/jobset/jobset_webhook.go#L135)

The above should be unit tested (new TestPodSets function per CRD).
I suggest one PR per CRD so that we can release at any point, even if not all are done.

**Why is this needed**:

This is part of https://github.com/kubernetes-sigs/kueue/issues/2724 which can be easily separated as another task.
To support TAS for all Job CRDs, it is a point of the plan in the [spreadsheet](https://docs.google.com/spreadsheets/d/1MXCjKZtAfqBTb61bJo46u7jIUqRIlu1NrYj1L8Xz-UU/)

**Comment by mimowo** [comment]
/assign @mbobrovskyi 
cc @PBundyra @tenzen-y

**Comment by tenzen-y** [comment]
> /assign @mbobrovskyi cc @PBundyra @tenzen-y

+1
We can just move all Job support to the Alpha stage in the KEP.

**Comment by mimowo** [comment]
I have also synced with @mbobrovskyi we will add a basic integration test per integration. From Job creation to create workload assignment

**Comment by mimowo** [comment]
/close
Up to my knowledge we have all CRDs covered
