### ISSUE TITLE
The roadmap in README.md would benefit from an update

### ISSUE THREAD

**Issue by dweineha** [kubernetes-sigs/kueue#3377]
The roadmap in README.md currently refers to "main priorities for 2023"; we're rapidly approaching the end of 2024. For users it might be confusing to know whether or not the items on the priority list have already been completed or not.

**Comment by mimowo** [comment]
cc @tenzen-y @mwysokin @mwielgus

**Comment by kannon92** [comment]
Good call out @dweineha.

Maybe Kueue should look to have a project board by milestone so we avoid keeping this up to date year over year.

**Comment by tenzen-y** [comment]
Yeah, that's right. The Roadmap looks like slightly outdated. Actually, we already supported most of the features.
Let us update the Roadmap after the release 0.9 in the next week.
