### ISSUE TITLE
[kjobctl] Add support for `kueue.x-k8s.io/max-exec-time-seconds` in other modes.

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#3387]
**What would you like to be added**:
As follow up for https://github.com/kubernetes-sigs/kueue/pull/3321, add support for `kueue.x-k8s.io/max-exec-time-seconds` in other kjobctl modes.

**Why is this needed**:
We already support `kueue.x-k8s.io/max-exec-time-seconds` in kjobctl's Slurm mode. It would be great to apply the same logic to other modes as well.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by mbobrovskyi** [comment]
We have `--time` flag for Slurm mode with very specific formats ("minutes", "minutes:seconds", "hours:minutes:seconds", "days-hours", "days-hours:minutes" and "days-hours:minutes:seconds"). But I'm not sure that it is good to use in another kjob modes.

@mimowo @mwysokin Should we create separate flag (e.g. --max-exec-time) with seconds or duration format? Or it's better to keep current and use for other modes the same? WDYT?

**Comment by mbobrovskyi** [comment]
Any thoughts?

**Comment by mimowo** [comment]
IIUC all other modes (can you list?) also support the same semantics of accounting for the max-exec-time? So, I think it could be a bit confusing to name the param differently. Also, the slurm format seems sensible, so I see no problem with reusing.

**Comment by mbobrovskyi** [comment]
> can you list?

Job, Interactive (Pod), Rayjob, Raycluster, Slurm
