### ISSUE TITLE
Add wrapper for ProvisioningRequestConfig to `util/testing` package

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#3472]
**What would you like to be added**:
Wrapper for ProvisioningRequestConfig similarly to e.g. [PriorityClassWrapper](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/util/testing/wrappers.go#L38-L61). Besides fundamental methods to create wrapper and actual object we also need methods to set:
- `.spec.provisioningClassName`
- `.spec.parameters`
- `.spec.managedResources`
- `.spec.retryStrategy`
- `.spec.retryStrategy.backoffLimitCount`
- `.spec.retryStrategy.backoffBaseSeconds`
- `.spec.retryStrategy.backoffMaxSeconds`

Wrapper should be used in all test files where `ProvisioningRequestConfig` is used, including:
- `pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler_test.go`
- `pkg/controller/admissionchecks/provisioning/controller_test.go`
- `pkg/util/admissioncheck/admissioncheck_test.go`
- `test/integration/controller/admissionchecks/provisioning/provisioning_test.go`

**Why is this needed**:
Improve code quality

**Completion requirements**:

**Comment by mimowo** [comment]
cc @mbobrovskyi @vladikkuzn @mszadkow

**Comment by mimowo** [comment]
Sure, please use '/assign' in that case
