### ISSUE TITLE
Imprecise log line: LocalQueue for workload didn't exist

### ISSUE THREAD

**Issue by gabesaba** [kubernetes-sigs/kueue#3527]
**What would you like to be cleaned**:
When [AddOrUpdateWorkloadWithoutLock](https://github.com/kubernetes-sigs/kueue/blob/2c8e7da1a23f2bc7218a2f08a2c9858a316fb053/pkg/queue/manager.go#L328) returns false, there are several lines which may log that a LocalQueue does not exist

e.g. 
https://github.com/kubernetes-sigs/kueue/blob/2c8e7da1a23f2bc7218a2f08a2c9858a316fb053/pkg/controller/core/workload_controller.go#L732-L734

Unfortunately, this function can also return false when the ClusterQueue is not located
https://github.com/kubernetes-sigs/kueue/blob/2c8e7da1a23f2bc7218a2f08a2c9858a316fb053/pkg/queue/manager.go#L336-L339

We should differentiate whether the ClusterQueue or LocalQueue is missing in the log lines which depend on (directly or indirectly) the return value of this function.

**Why is this needed**:
To assist with future debugging, and to make our logging more precise.

**Comment by mimowo** [comment]
it seems like
/good-first-issue

**Comment by 7h3-3mp7y-m4n** [comment]
I'll pick it up :)

**Comment by mimowo** [comment]
/kind bug
because the logs are not just not precise - they are misleading - as pointed out the message `LocalQueue for workload didn't exist or not active; ignored for now` can be logged when ClusterQueue does not exist.
