### ISSUE TITLE
Rename the reason for Evicted condition for deactivated workloads: WorkloadInactive -> Deactivated

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3530]
**What would you like to be added**:

Rename the reason InactiveWorkload -> Deactivated. 

[Here](https://github.com/kubernetes-sigs/kueue/blob/b6f39107bdb783c16c0bb17e54fba2f0831e2bbf/apis/kueue/v1beta1/workload_types.go#L517) is the definition.

Deprecate but continue supporting the old one for backwards- compatibility. We need a couple of releases or v1beta2 to drop the old one.

**Why is this needed**:

- the "Workload" is redundant. Other reasons don't contain it, see [here](https://github.com/kubernetes-sigs/kueue/blob/b6f39107bdb783c16c0bb17e54fba2f0831e2bbf/apis/kueue/v1beta1/workload_types.go#L519-L541).
- this is a reason for Evicted=True, so Deactivated reads better
- by analogy to Reactivated

**Comment by mimowo** [comment]
cc @PBundyra @mbobrovskyi @tenzen-y

**Comment by PBundyra** [comment]
SGTM
