### ISSUE TITLE
Add allocatePolicy to workload

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#363]
**What would you like to be added**:

Currently the workloads behave as all-or-nothing strategy in scheduling, but each podSet in workloads maybe independent, 
if we add a new allocatePolicy(the name is TBD) like bestEffort, we can schedule the podSets as much as possible rather than
block the whole workload.

**Why is this needed**:
Fine-gained scheduling.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
This maybe an immature proposal, for discussion.
/priority important-longterm

**Comment by alculquicondor** [comment]
Do you have any specific applications in mind that could benefit from this? Maybe Spark or Ray?

**Comment by alculquicondor** [comment]
Should we close this as a duplicate for elastic jobs?
