### ISSUE TITLE
TAS: Validate that the pod's index in the topology ungater falls within the expected range

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#3651]
**What would you like to be added**:
Add new or refactor existing functions to validate if the the pod index in topology ungater is within [0, maxIndex] range. This is the follow-up to [this comment](https://github.com/kubernetes-sigs/kueue/pull/3649#discussion_r1858267176) 

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Code change

The artifacts should be linked in subsequent comments.

**Comment by mimowo** [comment]
cc @mbobrovskyi 
maybe we could have a helper function like `ReadUIntFromLabelWithMax(pod, labelKey, maxValue)` so that other places can use it too.
