### ISSUE TITLE
TAS: respect node taints when the lowest hierarchy level is node

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3658]
**What would you like to be added**:

Respect node taints when scheduling by TAS when the lowest hierarchy level is `kubernetes.io/hostname`.

**Why is this needed**:

Some users may want to taint a node and exclude it from TAS. However, we still should include the tainted notes for which the workload has tolerations.

**Comment by mimowo** [comment]
cc @PBundyra @tenzen-y 
/assign

**Comment by tenzen-y** [comment]
I discussed this with @mimowo offline.
Technically, we can check taints at all levels.
But, in that case, we need to traverse all hierarchical taints. 
So, we support only the lowest hierarchy-level taints.

**Comment by mimowo** [comment]
A relatively simple approach I discussed with @PBundyra yesterday is to introduce a "virtual" level for nodes, even if not specified directly by the user in the Topology object. Still, it adds a bit of complexity, so I want to deliver this in two parts:
1. respect taints if the lowest level is kubernetes.io/hostname
2. respect taints for any topology by introducing the "virtual" level corresponding to kubernetes.io/hostname

The priority of (2.) is lower, but it should be simple so I will try to fit both into 0.10

**Comment by mimowo** [comment]
After consulting this with @mwielgus we decided to defer this decision / support for later. I open KEP update to capture the need to handle topologies without hostname better: https://github.com/kubernetes-sigs/kueue/pull/3681

**Comment by mimowo** [comment]
/close
The main issue is addressed, we will re-consider the options when there is no kubernetes.io/hostname the last level post 0.10, proposed KEP update: https://github.com/kubernetes-sigs/kueue/pull/3681
