### ISSUE TITLE
TAS: cleanup and introduce node wrapper for testing

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3661]
**What would you like to be cleaned**:

Introduce NodeWrapper for testing, similarly as we have a wrapper for creating pods.

**Why is this needed**:

Currently creating nodes for testing is quite verbose, [example](https://github.com/kubernetes-sigs/kueue/blob/560e4340b746aa811cec06b7a072a1a3faedc80f/pkg/cache/tas_cache_test.go#L48-L114).
For comparison, pods can be created much more compactly, [example](https://github.com/kubernetes-sigs/kueue/blob/560e4340b746aa811cec06b7a072a1a3faedc80f/pkg/controller/tas/topology_ungater_test.go#L143C17-L147)

**Comment by mimowo** [comment]
cc @mbobrovskyi @tenzen-y @kaisoz

**Comment by kaisoz** [comment]
/assign

I can take care of this one if this is ok for you 😊

**Comment by mimowo** [comment]
sure, thanks!
