### ISSUE TITLE
TAS: Use ResourceFlavorWrapper and TopologyWrapper for testing

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3662]
**What would you like to be cleaned**:

Use the wrappers to setup objects for TAS testing.

**Why is this needed**:

To make the code more consistent (as we use this strategy for other tests), and the shorter.

Example lengthy code: [here](https://github.com/kubernetes-sigs/kueue/blob/560e4340b746aa811cec06b7a072a1a3faedc80f/pkg/scheduler/scheduler_test.go#L4060-L4114).
See below the code for setting up ClusterQueue [here](https://github.com/kubernetes-sigs/kueue/blob/560e4340b746aa811cec06b7a072a1a3faedc80f/pkg/scheduler/scheduler_test.go#L4115-L4119)

**Comment by mimowo** [comment]
cc @mbobrovskyi @kaisoz @tenzen-y

**Comment by PBundyra** [comment]
Can we add a default Topologies to be used in tests? E.g.
- `oneLevelTopology` - contains block label
- `twoLevelsTopology` - contains block and rack lables
- `threeLevelsTopology` - contains block, rack and hostname labels

And use it across the whole codebase as this is something that is often repeated?

**Comment by mimowo** [comment]
I'm good with that, but we can follow up on this separately.

**Comment by mimowo** [comment]
One small idea to improve the verbosity of creating topology: https://github.com/kubernetes-sigs/kueue/pull/3719#issuecomment-2516596274.

**Comment by mimowo** [comment]
@PBundyra where would you declare the topologies? would they be created maybe by functions like "MakeThreeLevelTopology", or new functions say "MakeTopology().ThreeLevels"?

**Comment by mbobrovskyi** [comment]
/reopen

For follow ups
