### ISSUE TITLE
[Multikueue] Fail e2e-test due to expected empty strings on Creating a multikueue admission check Should run a job on worker if admitted

### ISSUE THREAD

**Issue by IrvingMg** [kubernetes-sigs/kueue#3664]
**What happened**:

In addition to #3600, it was found this issue while running `Creating a multikueue admission check Should run a job on worker if admitted` test. This error is returned **every time** the tests is ran:

```
MultiKueue when Creating a multikueue admission check [It] Should run a job on worker if admitted
/Users/Irving_Mondragon/Documents/git/kueue/test/e2e/multikueue/e2e_test.go:190

  [FAILED] Expected
      <[]v1.JobCondition | len:3, cap:4>: [
          {
              Type: "Suspended",
              Status: "False",
              LastProbeTime: {
                  Time: 2024-11-27T10:12:44+01:00,
              },
              LastTransitionTime: {
                  Time: 2024-11-27T10:12:44+01:00,
              },
              Reason: "JobResumed",
              Message: "Job resumed",
          },
          {
              Type: "SuccessCriteriaMet",
              Status: "True",
              LastProbeTime: {
                  Time: 2024-11-27T10:12:53+01:00,
              },
              LastTransitionTime: {
                  Time: 2024-11-27T10:12:53+01:00,
              },
              Reason: "CompletionsReached",
              Message: "Reached expected number of succeeded pods",
          },
          {
              Type: "Complete",
              Status: "True",
              LastProbeTime: {
                  Time: 2024-11-27T10:12:53+01:00,
              },
              LastTransitionTime: {
                  Time: 2024-11-27T10:12:53+01:00,
              },
              Reason: "CompletionsReached",
              Message: "Reached expected number of succeeded pods",
          },
      ]
  to contain element matching
      <*matchers.BeComparableToMatcher | 0x14000a920f0>: {
          Expected: <v1.JobCondition>{
              Type: "Complete",
              Status: "True",
              LastProbeTime: {
                  Time: 0001-01-01T00:00:00Z,
              },
              LastTransitionTime: {
                  Time: 0001-01-01T00:00:00Z,
              },
              Reason: "",
              Message: "",
          },
          Options: [
              <*cmp.pathFilter | 0x14000a90048>{
                  core: {},
                  fnc: 0x1009c58c0,
                  opt: <cmp.ignore>{core: {}},
              },
          ],
      }
  In [It] at: /Users/Irving_Mondragon/Documents/git/kueue/test/e2e/multikueue/e2e_test.go:267 @ 11/27/24 10:12:53.521
```

**What you expected to happen**:
Not to happen

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): macOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mimowo** [comment]
cc @tenzen-y as the reason is changed after the SuccessPolicy graduated to Beta in 1.31. I think it is safe to ignore the reason from asserts.

**Comment by IrvingMg** [comment]
> You say the test fails every time, but the board is green recently: https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-multikueue-e2e-main. Ah, I see, the `SuccessCriteriaMet` condition is added by k8s 1.31+, while we run the periodic tests on 1.30. I think we could update the test to only check the presence of the `Complete` condition.
> 
> EDIT: ah we already use ContainElement to check only the Complete condition, the issue is that the "Reason" is changed between the versions.

Yes, I'm also planning to open a PR in kubernetes/test-infra to use 1.31 on tests.
