### ISSUE TITLE
Documentation: Link to Admission points to concepts folder.

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#367]
**What would you like to be cleaned**:

https://github.com/kubernetes-sigs/kueue/blob/main/docs/concepts/cluster_queue.md

In cluster_queue concepts:

```
In a process called [admission](https://github.com/kubernetes-sigs/kueue/blob/main/docs/concepts/#admission), Kueue assigns to the [Workload pod sets](https://github.com/kubernetes-sigs/kueue/blob/main/docs/concepts/workload.md#pod-sets) a flavor for each resource the pod set requests.
```

Admission is linked to a nonexistent section in the repo.  I'd be willing to open a PR but I'm unsure where it is supposed to point or if that was removed.

**Comment by kannon92** [comment]
Looking at the README.md in concepts, there is a section about Admission.  I assume this is where the doc was meant to point?

**Comment by kerthcet** [comment]
I think so. It should be fixed.

**Comment by kannon92** [comment]
@kerthcet Thank you for pointing that out.  I have a PR to fix this now.
