### ISSUE TITLE
Flaky scheduler integration test

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#3679]
**What happened**:
Scheduler integration test failed

**What you expected to happen**:
No failure

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3677/pull-kueue-test-integration-main/1862134281669709824

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gabesaba** [comment]
/close
duplicate of #3633
