### ISSUE TITLE
Add Job interface to restrain the behaviors of different Job implementations

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#369]
**What would you like to be added**:

Currently, we have a default integrated implementation of batchv1 job, we achieve the expected behaviors by the experiences of kubernetes, and most importantly, we know the project well.  

But for people who wants to implement a special controller in kueue, they have little knowledges and they may don't know where to start. Documents are great and always needed, but they're not binding. 

So we should make a contract known as interface in golang, which defines the behaviors of the various jobs. E.g.:

```
type Job interface {
	Suspend()
	UnSuspend()
	QueueName()
	IsSuspend() bool
	Start() error
	Stop() error
	ConstructWorkload() (*kueue.Workload, error)
}
````

And we can wrap batch job like below, `BatchJob` is an  implement of kueue.Job

```
type BatchJob struct {
	job batchv1.Job
}
```      

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
That sounds great!
The job interface helps support Kueue Workload with custom jobs such as TFJob, PytorchJob, and MPIJob in `kubeflow/training-operator` and `kubeflow/mpi-operator/v2`.

**Comment by tenzen-y** [comment]
> I would also add some form of `InjectNodeAffinity`

Does this mean the following?

https://github.com/kubernetes-sigs/kueue/blob/6e403b517b8a3bfcc71b7ded10be9ca9d8634c5b/pkg/controller/workload/job/job_controller.go#L263-L278

**Comment by alculquicondor** [comment]
yes

**Comment by tenzen-y** [comment]
SGTM

**Comment by kerthcet** [comment]
We have a plan to integrate with other workloads, also see https://github.com/kubernetes-sigs/kueue/issues/499, I'd like to write a design doc at first.
/assign

**Comment by tenzen-y** [comment]
I'm also working on the kubeflow project.

So I'm thinking of giving feedback on the design doc since I'd like to support Kueue with training-operator and mpi-operator v2.

**Comment by kerthcet** [comment]
Thanks @tenzen-y , when you're ready, plz also cc me, thanks.

**Comment by alculquicondor** [comment]
From the messages above, I'm not sure who is writing the design doc. It sounds like @kerthcet, is that correct?

**Comment by tenzen-y** [comment]
> From the messages above, I'm not sure who is writing the design doc. It sounds like @kerthcet, is that correct?

Probably, @kerthcet is writing the doc.

**Comment by tenzen-y** [comment]
If @kerthcet doesn't have enough time, I can write it.

**Comment by kerthcet** [comment]
Yes, I'm writing now, almost finished.

**Comment by tenzen-y** [comment]
Sounds great.

**Comment by alculquicondor** [comment]
@kerthcet do you have a draft to share? It might be beneficial to provide you feedback already.

**Comment by alculquicondor** [comment]
Oh, from slack, it seems that Kante is OOO until the end of the month

**Comment by tenzen-y** [comment]
Thank you for letting us know.

**Comment by alculquicondor** [comment]
This is completed

/close
