### ISSUE TITLE
Node has `node.kubernetes.io/not-ready` taint in integration tests even if the Node is ready

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#3709]
**What happened**:
In the integration tests nodes have `node.kubernetes.io/not-ready` taint even if in their status `Ready` condition is set to `true` 

**What you expected to happen**:
Nodes didn't have the taint

**How to reproduce it (as minimally and precisely as possible)**:
Run newly added integration test from this [PR](https://github.com/kubernetes-sigs/kueue/pull/3708/files#diff-f24b50c55e86bbae151e985e718b4280d2585110e1b692c579a4a0c6c191036d) with toleration deleted 

**Anything else we need to know?**:
I believe we should add util function that removes the taint based on `Ready` condition

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mimowo** [comment]
> I believe we should add util function that removes the taint based on Ready condition

Or a function `createNode` which does 3 things: (1) creates the node, (2) updates status based on the object, (3) removes the taint if the node is Ready
