### ISSUE TITLE
Roadmap update

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#3713]
**What would you like to be cleaned**:

Update the Roadmap in the README.md, it's stale, e.g. we already supported multi-cluster. Maybe, refresh other parts as well, like the new introduced features.

**Why is this needed**:

Provide a high level overview and vision about the project.

**Comment by mimowo** [comment]
Good point
cc @tenzen-y @mwielgus @mwysokin @dgrove-oss

**Comment by tenzen-y** [comment]
This is a duplicated issue: https://github.com/kubernetes-sigs/kueue/issues/3377
/close
