### ISSUE TITLE
MultiKueue tests fail on the release branches

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3741]
**What happened**:

The e2e tests for MultiKueue fail on the release branches: https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-multikueue-e2e-release-0-9, and https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-multikueue-e2e-release-0-8

**What you expected to happen**:

No failures on the release branches

**How to reproduce it (as minimally and precisely as possible)**:

CI

**Anything else we need to know?**:

The release-blocking tests have been recently added.

**Comment by mimowo** [comment]
/assign @mbobrovskyi 
cc @kannon92

**Comment by mbobrovskyi** [comment]
@mszadkow PTAL https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-multikueue-e2e-release-0-8/1864585975003353088

**Comment by mimowo** [comment]
is this already fixed with https://github.com/kubernetes-sigs/kueue/pull/3743 and https://github.com/kubernetes-sigs/kueue/pull/3742? I so, then we can close

**Comment by mbobrovskyi** [comment]
I think https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-multikueue-e2e-release-0-8/1864585975003353088 another issue.

**Comment by mimowo** [comment]
ok, please investigate then

**Comment by mimowo** [comment]
The JobManagedBy was disabled on 1.31, so we have two choices: enable it in the kind config, and enable `MultiKueueBatchJobWithManagedBy`. Or keep it disabled, and also disable `MultiKueueBatchJobWithManagedBy`. These features (in k8s and kueue) need to be enabled in sync basically.

**Comment by mimowo** [comment]
but if there is no quick fix I don't think we need to worry too much, once we release 0.10 we can drop that testing suite I believe. cc @kannon92

**Comment by mbobrovskyi** [comment]
/close

Due to https://github.com/kubernetes-sigs/kueue/pull/3745 merged.
