### ISSUE TITLE
Set up documentation on kueue.sigs.k8s.io

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#377]
**What would you like to be added**:

Port the documentation from markdown into Netlify, as documented here: https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md

**Why is this needed**:

For easier access to documentation for end users. And for eye candy :)

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by moficodes** [comment]
I would like to take a stab at it.
