### ISSUE TITLE
Allow for feature gates to be configured via the configuration API

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#3804]
**What would you like to be added**:

Feature gates should also be configurable via configuration API.

**Why is this needed**:

I am working on an operator to manage upgrades/configuring of Kueue. Since Kueue deployment uses a configmap I am able to "configure" kueue via changing values in the config map for other personas. 

My hope is to avoid changing the deployment spec of Kueue so I can keep the configuring and upgrades of kueue separate from having to change the deployment.

If users would like to enable feature gates, they would have to modify the CLI arguments of Kueue.

It would be ideal to have a corresponding API for feature gates in the configuration so one can specify either the CLI or the component config.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
This is the generic K8s way. For example, the kubeadm [ClusterConfiguration](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/#kubeadm-k8s-io-v1beta4-ClusterConfiguration) has similar field.
So, we can accept this feature request.

**Comment by mimowo** [comment]
I can also see this useful. Currently adding the feature-gates to the Kueue Deployment is a bit hacky, because it requires editing the command line "feature-gates" argument, which is not structured - so tricky to do with jq or yq.

**Comment by mimowo** [comment]
This change can also be used to adjust e2e configuration between suites, which can be helpful to finally e2e test manageJobsWithoutQueueName. cc @mbobrovskyi @dgrove-oss . In reference to https://github.com/kubernetes-sigs/kueue/issues/3767.
