### ISSUE TITLE
Add NamespaceSelector to ClusterQueue

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#4]
NamespaceSelector in capacity allows controlling which namespaces are allowed to use the capacity.

/kind feature

**Comment by ahg-g** [comment]
> Does is mean we need a validating webhook?

No not a webhook, kueue itself should not consider assigning capacity to queued in not selected namespcaes. We also need to produce events and perhaps update queue status to indicate whether the capacity a queue is pointing to is allowed.

**Comment by ahg-g** [comment]
/unassign @jiwq 
/assign

we need to do this soon, @jiwq please feel free to pick other issues when you have time.

**Comment by jiwq** [comment]
@ahg-g Sorry to the late response. I'll continue other work when I have time and submit ASAP. Thanks for your help!
