### ISSUE TITLE
Expand testgrids per test

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#402]
**What would you like to be cleaned**:

Currently, the testgrids for unit and integration tests only mark whether the entire suite passed or not.

- https://testgrid.k8s.io/sig-scheduling#pull-kueue-test-unit-main
- https://testgrid.k8s.io/sig-scheduling#pull-kueue-test-integration-main

It would useful to have rows for each test.

**Why is this needed**:

To be able to track flakiness of specific tests.

**Notes**:

I don't know how to achieve this, but here is where the presubmits are defined:

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kueue/kueue-presubmits.yaml

**Comment by alculquicondor** [comment]
It probably has to do with using the kubekins image https://github.com/kubernetes/test-infra/blob/0aef7a83d0f5d74467667e4d13eef2589c5d740d/config/jobs/kubernetes/sig-testing/make-test.yaml#L18

**Comment by alculquicondor** [comment]
Or producing a junit XML report 🤷

**Comment by BenTheElder** [comment]
junit xml, not kubekins

see for example https://github.com/kubernetes-sigs/kind/blob/b6bc112522651d98c81823df56b7afa511459a3b/hack/make-rules/test.sh / https://github.com/kubernetes/registry.k8s.io/blob/main/hack/make-rules/test.sh

**Comment by kannon92** [comment]
So if I'm reading this right, we need to generate junit-xml reports for our tests.  How exactly do these artifacts get uploaded to testgrid?  

@alculquicondor Since I will be opening a PR to testgrid once I get https://github.com/kubernetes-sigs/kueue/pull/421 merged, I'll experiment with junit for that and then apply these findings to the other tests?

**Comment by BenTheElder** [comment]
> So if I'm reading this right, we need to generate junit-xml reports for our tests. How exactly do these artifacts get uploaded to testgrid?

Testgrid reads junit.xml artifacts from what the CI uploads ($ARTIFACTS directory).

**Comment by kannon92** [comment]
Hello @BenTheElder, thank you for your help.  I believe I figured out how to add testgrid per test.  

https://github.com/kubernetes-sigs/kueue/pull/423
