### ISSUE TITLE
Automate adoption of jobs that didn't start via Kueue

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#419]
**What would you like to be added**:

Automate the adoption of jobs that didn't start via Kueue, this means creating the Workload object for those jobs. Admins will need an API to specify which CQ those jobs should be counted against.

**Why is this needed**:
 This can help transition existing clusters to use Kueue

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
You mean adopt running jobs with kueue? Does it worth, job is run-to-complete, we can adopt them next time when they're ready to start again.

**Comment by alculquicondor** [comment]
IHAC which is interested in this. Their setup looks like the following:
- One flavor (so this could be a constant in the script arguments)
- Each Pod has a label for which the value can be passed through a map to derive a ClusterQueue name.

Does anyone have other mappings that we would need to account for?

**Comment by nstogner** [comment]
One possible implementation: https://github.com/kubernetes-sigs/kueue/pull/1742 ... thoughts?

**Comment by alculquicondor** [comment]
https://github.com/kubernetes-sigs/kueue/tree/main/cmd/importer

/assign @trasc 

/close
