### ISSUE TITLE
Don't misappropriate ResourceFlavor labels for nodeSelector

### ISSUE THREAD

**Issue by SammyA** [kubernetes-sigs/kueue#425]
**What happened**:
Kueue was deployed via ArgoCD. Jobs that were ready to run produced Pods that stayed "Pending" because k8s could not find any nodes to satisfy the nodeSelector restriction. The nodeSelectors were put there by Kueue and taken from the ResourceFlavor labels.

Systems like ArgoCD and Helm add labels to objects under their control to select all objects belonging to a certain app/chart. This makes ResourceFlavors incompatible with any system that add their own labels.

**What you expected to happen**:
Don't use the ResourceFlavor labels for node selection. Define an explicit field in the ResourceFlavor definition for nodeSelector.

**How to reproduce it (as minimally and precisely as possible)**:
Add a label like `app.kubernetes.io/managed-by: Helm` to a ResourceFlavor. This is one of several labels Helm adds to every object it controls. ArgoCd works in a similar fashion. Jobs using this ResourceFlavor wil have the same label added as a nodeSelector. If you don't have nodes with this label (you probably won't), this job can never run, and will stay pending indefinately.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25.3
- Kueue version (use `git describe --tags --dirty --always`): v0.2.1
- Cloud provider or hardware configuration: on-premise 
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 11 (bullseye)
- Kernel (e.g. `uname -a`): 5.10.0-19-amd64
- Install tools: kubeadm
- Others:

**Comment by alculquicondor** [comment]
We used to have a separate labels field, but we removed it because it caused confusion #334.

But your use case seems like a good justification to revert. Although it's probably better to have a different name for the field, like `matchingLabels`.

**Comment by alculquicondor** [comment]
cc @ahg-g

**Comment by inossidabile** [comment]
Just hit exactly the same issue. Apparently there's no workaround? Helm states having such label there is a must. So there seem to be no way to create ResourceFlavors via helm as of now?

**Comment by alculquicondor** [comment]
I don't think there is a workaround, besides downgrading to kueue 0.1.1

I agree with the `nodeSelector` name. Can someone work on it? We can have it for the 0.3.0 release.

**Comment by ahg-g** [comment]
Sounds good, too bad we went ahead and removed the explicit parameter in the first place! But, the good thing is that we can add it back without needing to bump the api version.

**Comment by kerthcet** [comment]
Also meet this problem in our cluster, we use argocd. I'd like to fix this.
/assign

**Comment by kerthcet** [comment]
And also, maybe we should provide a helm chart for installation besides kustomize, we depends a lot on helm charts in CI/CD, I guess it's true for other uses as well.

**Comment by maaft** [comment]
Just hit the same issue. Are there any workarounds currently?

**Comment by alculquicondor** [comment]
You can use a development version. We didn't backport this to 0.2 as it's not a backwards compatible change.

**Comment by alculquicondor** [comment]
https://github.com/kubernetes-sigs/kueue/blob/main/docs/setup/install.md#install-the-latest-development-version

**Comment by kerthcet** [comment]
Is the advice helpful and solved your problem? @maaft
