### ISSUE TITLE
[E2E Tests] - We should allow users to test the e2e code against existing clusters that aren't kind.

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#431]
**What would you like to be added**:

Our e2e tests currently do the following:

1. Build Kind Cluster
2. Build a local image
3. Load that image to kind
4. Run our tests

It would be nice to allow users to use an existing cluster where the images are existing in a repo.  This could be useful for release testing on cloud vendors kubernetes clusters.  

**Why is this needed**:

Developers use a wide range of Kubernetes clusters for development and we should not assume that everyone wants to run on Kind.  

**Completion requirements**:

A developer can run the e2e tests on an existing cluster without assuming kind.

**Comment by shubhbapna** [comment]
Hey @kannon92 would love to take a shot at this issue! Can I take it?

**Comment by kannon92** [comment]
> Hey @kannon92 would love to take a shot at this issue! Can I take it?

Yep!

/assign @shubhbapna

**Comment by alculquicondor** [comment]
You can assume that the existing cluster has access to the registry that `make image-local-push` pushes to.

**Comment by shubhbapna** [comment]
Should I add another target or can I simply edit the existing target to behave like this:
```
# run using kind
make test-e2e

# run using existing cluster
make test-e2e USE_EXISTING_CLUSTER=true IMAGE_TAG=tag
```

**Comment by alculquicondor** [comment]
Not having an extra target would be nice
