### ISSUE TITLE
helm charts support in installation

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#436]
**What would you like to be added**:

Helm chart is now a normal artifact, widely used in CI/CD systems or displayed in application market, it seems charming if we can support this besides kustomize.

**Why is this needed**:

- A standard artifact to end-users.
- Better integration with CI/CD systems.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by maaft** [comment]
yes, please

**Comment by alculquicondor** [comment]
I don't think there is anyone looking at this now. Feel free to take it if you have some experience with helm.

**Comment by Gekko0114** [comment]
Hi @alculquicondor, 
It seems interesting to me.
Can I work on this issue?

**Comment by alculquicondor** [comment]
For sure. Don't expect much guidance from my part, as I'm not familiar with helm.

**Comment by Gekko0114** [comment]
Sure. I will try it by myself. Thanks!
/assign
