### ISSUE TITLE
Add scalability tests

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#45]
This is critical to better understand kueue's limits and where its bottlenecks. We should check if there is a way to use clusterloader for this

**Comment by ArangoGutierrez** [comment]
I think the first we can do for this issue is to lay down what we want to test/bench for Kueue.
I think I good first approach is to get a baseline of resource utilization vs scale.

- [ ] How many sample queues can kueue hold when running on 1 cpu and 200MB mem. 
- [ ] On an empty cluster with "infinite" resources, how long does it take to Kueue to fully `admit` all the jobs into a ClusterQueue

those are init test ideas

**Comment by alculquicondor** [comment]
I think we should test "infinite" resources but also "limited" (say, the ClusterQueues have 20% of the total required requests for all jobs)

**Comment by ArangoGutierrez** [comment]
Can't get more on Minikube :( , will have to move to something else. will report more later

**Comment by ArangoGutierrez** [comment]
empty queues, staging Kueue, after 15 mins of inactivity  (bootstrap stabilization) 

> Base line

![Screenshot from 2022-03-15 19-33-30](https://user-images.githubusercontent.com/15933089/158489160-c043e7ae-e9e7-439a-98e4-f4d1ff4a919e.png)

**Comment by ArangoGutierrez** [comment]
We need to create a list of target features to stress test to move forward with this issue

**Comment by ArangoGutierrez** [comment]
Do we want to do resource utilization testing? 
e.g :
- How many CPU and MEM is used by Kueue while processing X number of Workloads
- CPU and MEM on a system with "infinite" resources vs a system with no resources, to see how a high traffic moment can affect resource consumption by Kueue.

**Comment by ArangoGutierrez** [comment]
- In a system with "infinite" resources, how long does it take to Queue to *admit* X number of workloads

**Comment by ahg-g** [comment]
We need to run tests that measure:
1. Workload admission latency
2. Workload admission throughput
3. cpu/memory (we don't set the limits, so it can compete with whatever available resources on the master)

The scale test should measure that while varying 
1. The number of Namespaces/Queues; tens to hundreds.
1. The number of ClusterQueues; few to as many as Namespaces
4. The number workloads; hundreds, thousands, to few tens of thousands

As for CPU and memory, we can use settings similar to kube-scheduler;

**Comment by alculquicondor** [comment]
A first load test was added in #462.

We can create separate issues for follow ups and to improve performance.

/close
