### ISSUE TITLE
remove the webhooks in favor of CEL once 1.24 reaches EoL

### ISSUE THREAD

**Issue by nayihz** [kubernetes-sigs/kueue#463]
**What would you like to be cleaned**:
we can remove the webhooks in favor of CEL once 1.24 reaches EoL https://kubernetes.io/releases/

**Why is this needed**:
Since Kubernetes 1.25, we can use CEL validation rules to implement a few common immutability patterns directly in the manifest for a CRD.
ref: https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/

**Comment by alculquicondor** [comment]
Maybe we cannot fully replace defaulting, but at least we can replace validation.

/assign trasc

**Comment by alculquicondor** [comment]
/retitle Migrate some validations to CEL

Since we couldn't delete the webhooks entirely due to some limitations of CEL.

We requested some improvements upstream https://github.com/kubernetes/kubernetes/issues/124490
