### ISSUE TITLE
Validate using open API where possible

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#465]
**What would you like to be cleaned**:

We do validation through webhooks. Some validations could be translated to openAPI using this documentation https://book.kubebuilder.io/reference/markers/crd-validation.html

When doing so, we should remove the go code that does the same validation, to avoid duplication. And we need to make sure the validation is covered in integration tests, as opposed to unit tests. Maybe we should be running the integrations tests in 1.23, the oldest k8s supported version.

**Why is this needed**:

We eventually want to get rid of webhooks #463. Before CEL support is widespread, we can at least start migrating some logic.

**Comment by alculquicondor** [comment]
cc @cmssczy, would you like to work on this?

**Comment by cmssczy** [comment]
Yes.
/assign

**Comment by cmssczy** [comment]
closed this as completed in https://github.com/kubernetes-sigs/kueue/pull/466
/close
