### ISSUE TITLE
Handle changing Job parallelism

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#467]
**What would you like to be added**:

Handle the change in parallelism. Before admission, this is simple: we need to update the workload.

What if the workload is already admitted? If there is enough quota, we could directly update the workload, even though that might violate FIFO semantics. Perhaps we will need to use scheduling gates to hold pods. 

**Why is this needed**:

Parallelism is a mutable field. 

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
We could have a short term solution: handle scale down properly and disallow scale up via webhook.

**Comment by ahg-g** [comment]
Note that in the job controller, if parallelism changes, the job gets suspended and the workload object gets deleted, and so forcing re-queueing the job.

https://github.com/kubernetes-sigs/kueue/blob/705915169f5045c91e033acc1fa59af77bec4e72/pkg/controller/workload/job/job_controller.go#L523

**Comment by ahg-g** [comment]
This is already handled, what else do we want to do with this one?

**Comment by ahg-g** [comment]
I think we want to think of this in the context of https://github.com/kubernetes-sigs/kueue/issues/77, not as a separate issue.

**Comment by alculquicondor** [comment]
I had an offline discussion with @mwielgus and we agreed that it's probably not worth doing anything in this space until scheduling readiness gates are GA.

So yes, closing in favor of #77.
