### ISSUE TITLE
Enhance Makefile arguments for img building and pushing

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/kueue#47]
Current Makefile doesn't provide flexible ways to modify how I want to build and push the image

```bash
VERSION := $(shell git describe --tags --dirty --always)
# Image URL to use all building/pushing image targets
IMAGE_BUILD_CMD ?= docker build
IMAGE_PUSH_CMD ?= docker push
IMAGE_BUILD_EXTRA_OPTS ?=
IMAGE_REGISTRY ?= k8s.gcr.io/kueue
IMAGE_NAME := controller
IMAGE_TAG_NAME ?= $(VERSION)
IMAGE_EXTRA_TAG_NAMES ?=
IMAGE_REPO ?= $(IMAGE_REGISTRY)/$(IMAGE_NAME)
IMAGE_TAG ?= $(IMAGE_REPO):$(IMAGE_TAG_NAME)
BASE_IMAGE_FULL ?= golang:1.17
```

Also in order to be more generic, rename
`docker-image` to simply `image` or `image-build` 
`docker-push` to simply `push`  or `image-push`

This provides more flexibility when developing in a non docker environment, like `buildah` , `podman` or even building the image with CI tool on `kubernetes` it self.

/kind feature

**Comment by ArangoGutierrez** [comment]
Waiting for feedback
/assign

**Comment by ArangoGutierrez** [comment]
Example implementation : https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/Makefile

**Comment by alculquicondor** [comment]
Agree, not everyone uses docker :)

Do you really need the registry? The existing `IMG` parameter already allows you to use a full path.

**Comment by ArangoGutierrez** [comment]
it works nice for use in NFD< bc we can set it to push to staging or other registries by simply editing an ENV VAR :) , but I am open to suggestion, once we agree here, I'll submit a patch

**Comment by alculquicondor** [comment]
sounds good.

Since you have `BASE_IMAGE_FULL`, do you want to add the end image that is currently one of the distroless variants?
