### ISSUE TITLE
Add pprof endpoint

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#486]
**What would you like to be added**:

Add an endpoint that allows to capture a profile.

Core Kuberentes components have this:
https://github.com/kubernetes/kubernetes/blob/407bd6a4afa5f7d7cb2a596dda09cacc30828f09/cmd/kube-scheduler/app/server.go#L282

Not sure if there is a way to do this via controller runtime https://github.com/kubernetes-sigs/controller-runtime/issues/1779

**Why is this needed**:

To inform performance improvements

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
There is WIP https://github.com/kubernetes-sigs/controller-runtime/pull/1943

**Comment by alculquicondor** [comment]
The next release of controller-runtime should include this https://github.com/kubernetes-sigs/controller-runtime/pull/1943

**Comment by trasc** [comment]
It should be doable with kubernetes-sigs/controller-runtime#1779 , we just need to add support for this in the config.
