### ISSUE TITLE
Kubectl plugin for listing objects

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#487]
**What would you like to be added**:

A [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) that allows to list Jobs and ClusterQueues with comprehensive information.

And a `kubectl describe` equivalent for Jobs that includes Workload information.

Other useful helpers:
- Manually admit a workload.

**Why is this needed**:

The basic view of `kubectl get` can't include details such as whether a workload is admitted or why it's pending, because the information is present in compound objects. Similarly, it can't tell the status of a ClusterQueue if it's misconfigured.

Furthermore, when listing Jobs, you wouldn't see the details of the accompanying Workload.

**Completion requirements**:

This enhancement requires the following artifacts:

- [X] Design doc
- [X] API change: the command line interface is an API.
- [X] Docs update

The artifacts should be linked in subsequent comments.

**Comment by vsoch** [comment]
Here is a design document for what I am thinking: https://gist.github.com/vsoch/954d8c95bdb71bcca92b438bbc879eca. Let me know if you'd like that as a Google document instead. Some notes:

- It will be more advantageous to have this scoped to be a command line tool for kueue, and one that folds into being a plugin if desired. I actually think the first use case (where someone could essentially interact with kueue via the command line and not with kubectl) would be hugely great for the converged computing use case - folks are used to command line tools to interact with / manage jobs, and we could provide similar interactions to it.
- I've proposed a set of subcommands to start, and additional ones I think would be useful.

And it's assumed that the implementation would be in Go.

**Comment by alculquicondor** [comment]
oh, we actually have a place for this in the repo itself :)
https://github.com/kubernetes-sigs/kueue/tree/main/keps

Either a PR or a google doc works better as we can comment on specific sections of the design.

I like the idea of a tool that works both standalone and as a plugin. To be fair, a plugin is not much more than a CLI that happens to start with `kubectl-` :)

**Comment by vsoch** [comment]
All set! https://github.com/kubernetes-sigs/kueue/pull/977

**Comment by vsoch** [comment]
Hey is there a status update here? I made my first plugin last weekend and it was fairly simple so I could jump in to help if the current assignee is low on bandwidth.

**Comment by tenzen-y** [comment]
> Hey is there a status update here? I made my first plugin last weekend and it was fairly simple so I could jump in to help if the current assignee is low on bandwidth.

@vsoch Thank you for offering help. @yaroslava-serdiuk is working on the KEP.

/remove-lifecycle stale

**Comment by vsoch** [comment]
Checking in again - this is still a WIP?

**Comment by yaroslava-serdiuk** [comment]
I'm currently not working on it, but AFAIK this should be picked up soon. 
@mwielgus do you have any update on it?

**Comment by vsoch** [comment]
I originally couldn't do it because we didn't have a proper CLA, but we do now, in case help is still wanted. Let me know!

**Comment by alculquicondor** [comment]
/close

I see that @mwielgus created an updated issue.
