### ISSUE TITLE
Flaky test for WaitForPodsReady if two workloads are considered in the same scheduling cycle

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#488]
**What happened**:

/kind flake

Failing test:

```
Scheduler with WaitForPodsReady Suite: [It] SchedulerWithWaitForPodsReady when Scheduling workloads on clusterQueues Should block admission of one new workload if two are considered in the same scheduling cycle
```

**What you expected to happen**:

The test to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/415/pull-kueue-test-integration-main/1605630317664669696

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): main branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
Thanks for creating this! I faced this issue on #415.

**Comment by mimowo** [comment]
@alculquicondor please review the fix: https://github.com/kubernetes-sigs/kueue/pull/491
