### ISSUE TITLE
Use SSA (Server-Side Apply) for setting the workload conditions

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#493]
With the use of SSA we will be able to avoid conflicts when different controllers set or add the conditions. For example, when a workload is admitted, the `WorkloadAdmitted` condition is set in a separate request to setting the workloads `.spec.admission` field. On the other hand, the `PodsReady` condition is added by the job controller, which may result in a conflict and a need to retry the request. This issue is exposed by the need to retry in the integration test (without the retry the test occasionally fails): https://github.com/kubernetes-sigs/kueue/blob/e688dccea0c3683a35bd51e9d67dba40a3997d83/test/integration/scheduler/podsready/scheduler_test.go#L100.
We can avoid the conflicts by using SSA with a pair of dedicated field managers - one for `PodsReady` (job controller) and `WorkloadAdmitted` (scheduler and workload controller).

**Comment by tenzen-y** [comment]
> Just curious what is SSA?

Probably, SSA is Server-Side-Apply.

**Comment by mimowo** [comment]
> > Just curious what is SSA?
> 
> Probably, SSA is Server-Side-Apply.

Yes, we already use it in Kueue for admission (https://github.com/kubernetes-sigs/kueue/blob/e688dccea0c3683a35bd51e9d67dba40a3997d83/pkg/scheduler/scheduler.go#L286), but not for conditions.

**Comment by alculquicondor** [comment]
Do we always have to send all the conditions that we want to handle? Or can we send them in separate patches?

Although in the case of Workload, one condition is set by the Workload reconciler and the other by the Job reconciler, so they can use different managers.
