### ISSUE TITLE
Use a fake clock to avoid sleep in the podsready integration tests

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#494]
In the `podsready` integration test we sleep for a second to ensure the two created workloads have different creation timestamps: https://github.com/kubernetes-sigs/kueue/blob/e688dccea0c3683a35bd51e9d67dba40a3997d83/test/integration/scheduler/podsready/scheduler_test.go#L131. This can be avoided if the test could use a fake clock. This will require refactoring of some controllers to enable injecting the fake clock.

**Comment by tenzen-y** [comment]
/remove-lifecycle rotten

@mimowo Are there any leaving tasks to complete this issue?

**Comment by tenzen-y** [comment]
> Given that there are only 2s to gain, and the integration tests which use real clocks are more valuable, we can defer the refactoring. 

It makes sense.

> So, I suggest to close it for now and reopen when we see a need, or bigger benefit.

To avoid forgetting this issue, adding a `lifecycle/frozen` label might be better instead of closing the issue although I'm also ok with closing this.

**Comment by mimowo** [comment]
/close 
Let me close as this will probably not be needed for a while and can make the backlog if issues look cleaner. We will reassess the need in the future.
