### ISSUE TITLE
custom workload

### ISSUE THREAD

**Issue by talcoh2x** [kubernetes-sigs/kueue#499]
Hi, we are looking for exactly such solution for managing and utilize large scale cluster with "batch" workload.
As i understand (and correct me if I'm wrong ) kueue still not fully integrated with kubeflow(training operator)/MpiJob.
what I'm try to understand first is:
- if there is support of kueue  with kubeflow(training operator)/MpiJob 
- if not, what can we do from our side (not from kubeflow(training operator)/MpiJob ) to make it work. to make kueue work with those 
CRD.
- we have resources name habana.ai/<xx> . as I saw you have supports for any compute resource name right ?
- we have the option to configure "kueue" in some way to control on the priority of the queue or the order inside the queue ?

we are working with PodGroup so what really interesting us is "queue  control" step before the workload get into the scheduler ( I think that exactly what your doing here). my concern is how to do the integration with other CRD and how can I "extend" our reqirments into kueue.
for example in k8 scheduler we extended preFilter/Filter and score with plugins that related to our clusters requirement wondering how it will work here

**Comment by alculquicondor** [comment]
This was suggested in #10, but there is no progress. We probably should gather more feedback before committing to such thing.

In your examples, could you add priorities to the job templates in a webhook or something like that?

**Comment by talcoh2x** [comment]
Yes, we set different priority (we have around 3 4 different priority) for different use cases, that will work i believe. I just checking how we can "extend" and modify the queue as we want without to changed the code only by adding as "extender"/"plugin".
it will give us the flexibility we need. 

I'll continue follow https://github.com/kubernetes-sigs/kueue/issues/10

thank you! hope also we will join to the effort here

**Comment by alculquicondor** [comment]
Let's close this issue and continue discussions in the already opened issues.

Feel free to open more if you have other feedback.

/close
