### ISSUE TITLE
Add info to Queue status

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#5]
Suggestions:
- Number of pending jobs
- Number of started jobs
- Resources currently used by the queue.

/kind feature

**Comment by ArangoGutierrez** [comment]
I think after https://github.com/kubernetes-sigs/kueue/pull/114, we can close this

**Comment by ArangoGutierrez** [comment]
Now that #114 is merged, I think we can close this issue

Thoughts otherwise? (@alculquicondor @ahg-g )
