### ISSUE TITLE
Add a condition to LocalQueue when it points to a ClusterQueue that doesn't exist

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#545]
**What would you like to be added**:

A conditions field in the LocalQueueStatus and add one condition through the LocalQueue that reports if a ClusterQueue doesn't exist.

**Why is this needed**:

Better observability

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@alculquicondor Will you take this issue? If not, I'd like to take this one :)

**Comment by alculquicondor** [comment]
Sure, go ahead

**Comment by tenzen-y** [comment]
> Sure, go ahead

Thanks. First, I will propose the API changes in this issue.

**Comment by tenzen-y** [comment]
> A conditions field in the LocalQueueStatus and add one condition through the LocalQueue that reports if a ClusterQueue doesn't exist.

I was misunderstanding the above comment. That means just adding a `[]metav1.condition` field to LocalQueue similar to ClusterQueue. So we may not need a proposal for API changes in this issue :)

/assign
