### ISSUE TITLE
Provide client-go libraries

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#555]
**What would you like to be added**:
Auto-generate and provide the client-go codes.

**Why is this needed**:
It is useful for the CustomJob operator of implementation based on client-go (e.g., MPIJob).

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@alculquicondor WDYT?

**Comment by alculquicondor** [comment]
yes, it's useful, but let's wait after #532

**Comment by tenzen-y** [comment]
> yes, it's useful, but let's wait after #532

I agree.

**Comment by maaft** [comment]
In the meantime, are there any examples on how to query/create queues and jobs via `client-go`?

**Comment by tenzen-y** [comment]
> In the meantime, are there any examples on how to query/create queues and jobs via `client-go`?
> 
> I want to provide a "simple" frontend GraphQL API for my cluster-users to start and stop jobs.

Maybe, you can use a client of controller-runtime.

**Comment by maaft** [comment]
Could you please elaborate a bit on required steps or provide links? That would be greatly appreciated!

I'm fairly new to writing controllers / interacting with k8s through non-kubectl ways.

**Comment by alculquicondor** [comment]
The documentation for controller runtime can be found here: https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html

Although you seem to be in the right path already. You can simplify to:

```golang
err = kueue.AddToScheme(scheme)
```

If you have some time, it would be greatly useful to have instructions in this folder https://github.com/kubernetes-sigs/kueue/tree/main/docs/tasks
