### ISSUE TITLE
[Website] Display problem at kueue homepage

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#574]
We should fix this logo
![image](https://user-images.githubusercontent.com/18364341/219258569-cddea53f-c5b7-4f40-9a98-9c34267fca5d.png)

Also I'm not an expert at frontend, but this looks unclear, is this intended? 
![image](https://user-images.githubusercontent.com/18364341/219258657-4f62e190-4d53-4e82-b471-07070c820dcb.png)

**Comment by alculquicondor** [comment]
logo request https://github.com/kubernetes/steering/issues/264

> this looks unclear

Do you mean it's hard to see? Maybe we can put a darker background.

cc @moficodes

**Comment by kerthcet** [comment]
> Do you mean it's hard to see? Maybe we can put a darker background.

yeah

**Comment by alculquicondor** [comment]
ah, we never fixed this
@moficodes could you add a darker tone?

**Comment by moficodes** [comment]
That background was always a placeholder. Once we have our logo finalized. (Saw the email today looks like its ready) We probably will change it anyway. 

I will look into it. Thanks for reminding me!
