### ISSUE TITLE
Support for MPIJob scheduling

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#577]
**What would you like to be added**:

Support for scheduling of MPIJob, controller by the MPI-operator (https://github.com/kubeflow/mpi-operator).

The decision for the integration to be part of the Kueue project was discussed here: https://github.com/kubeflow/mpi-operator/issues/505 and here: https://github.com/kubeflow/mpi-operator/pull/521#discussion_r1101481114.

**Why is this needed**:

Users of the MPI operator would like to use Kueue without a need for refactoring. Also, the integration with MPI operator will be the first for Kueue so will pave the way for integrations with other frameworks.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@mimowo Should we use #65?

**Comment by mimowo** [comment]
Deduplicating as there is already https://github.com/kubernetes-sigs/kueue/issues/65, @tenzen-y thanks for pointing this out.
