### ISSUE TITLE
Use logo in website

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#584]
CNCF sent us some logo options

https://github.com/kubernetes/steering/files/10769068/kubernetes-kueue-logo_v1.pdf

https://github.com/kubernetes/steering/issues/264

Voting form: https://forms.gle/dXMjtJB37VaBwDeb8 (join https://groups.google.com/a/kubernetes.io/g/wg-batch to be able to vote)

**Comment by kerthcet** [comment]
Voted +1

**Comment by kerthcet** [comment]
We do have a logo now.
/close

**Comment by kerthcet** [comment]
/reopen
We should update it to the website.

**Comment by alculquicondor** [comment]
I'm waiting for a csv from CNCF
