### ISSUE TITLE
WaitForPodsReady: a mode where jobs don't block the queue head

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#610]
**What would you like to be added**:
A mode of operation for WaitForPodsReady where jobs don't block the head of the queue, but still get suspended if they aren't ready after a while.

**Why is this needed**:
Blocking the queue until a Job is ready guarantees all-or-nothing scheduling, but it is slow at scale. Consider the case where a large number of jobs are awaiting to be scheduled and suddenly lots of resources become available (e.g., a large job finishes, releasing significant amount of resources).

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
We probably would start optimistically admitting every workload and then setting some kind of backoff when resources are unavailable.

Should the backoff be per flavor?

**Comment by KunWuLuan** [comment]
Hi, I think we can do two more things to help solve the problem:
1. continue admitting more workloads until there is no more resources in cohort
2. requeue the current workload if it wait too long for pods ready

How do you think? @alculquicondor @ahg-g

**Comment by trasc** [comment]
Hi @KunWuLuan,

> 2\. requeue the current workload if it wait too long for pods ready

is done in #599 / #689 .

I think, what we need to, is to investigate the effect of dropping the `s.cache.WaitForPodsReady(ctx) ` in 
https://github.com/kubernetes-sigs/kueue/blob/9ca57c86cf06c11a94a2d5b7badf60233a51a2f2/pkg/scheduler/scheduler.go#L179-L189 

and continue from there.

**Comment by KunWuLuan** [comment]
Hi, @trasc  I think you are right. 💯 

Moreover, maybe we can add a switch to let user choose whether to block the admission while still waiting for pods ready.
If false, we just skip all these checking in 
https://github.com/kubernetes-sigs/kueue/blob/9ca57c86cf06c11a94a2d5b7badf60233a51a2f2/pkg/scheduler/scheduler.go#L178-L189
. Then the other jobs can continue being admitted until resources are exhausted. WDYT?

@alculquicondor If you have time, you can also participate in the discussion, which will be of great help. Thank you very much. 😆 👍

**Comment by alculquicondor** [comment]
@KunWuLuan thanks for your feedback. I'm currently with limited availability as I'm attending kubecon. I'll get back to this thread next week.
If you have some time, feel free to review the open PRs listed above.

But in general, this feature should be optional.
