### ISSUE TITLE
Will the CRD’s v1beta1 of the master branch change before release-0.3.0 is released?

### ISSUE THREAD

**Issue by fjding** [kubernetes-sigs/kueue#621]
Hi, I found that there is a big difference between v1alpha2 and v1beta1. I want to know whether the crd of v1beta1 has been confirmed? Will there be changes before release-0.3.0?

**Comment by fjding** [comment]
We plan to use kueue as the batch scheduling component, but found that v1alpha2 is outdated, so we want to use the master branch as the online version.

**Comment by fjding** [comment]
> > I want to know whether the crd of v1beta1 has been confirmed?
> 
> Does that mean you want to know that v1beta1 is tested? If so, we confirmed v1beta1 using the KinD cluster.
> 
> #604
I means whether the structure of the CRD will have any  change before release 0.3.0?

**Comment by tenzen-y** [comment]
We will not release any patch versions for v0.2. So you can deploy v1beta1 using the main branch or v0.3.0.

cc: @alculquicondor @kerthcet
