### ISSUE TITLE
Add a new page for the troubleshooting to the documentation

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#630]
**What would you like to be added**:
Add a "Troubleshooting" page to the documentation.

**Why is this needed**:
We have two different active conditions:

1. `clusterQueueStatus.conditions.type==active` means that all flavors exist in the cluster, and the CQ can admit new workloads. 
2. `localQueueStatus.conditions.type==active`  means that a related CQ exists in the cluster, and the Q can submit new workloads to CQs.

Maybe, those conditions are confusing to users. So it might be better to add a guide about the two different "active" conditions.

Followup: https://github.com/kubernetes-sigs/kueue/pull/623#discussion_r1135563814

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
And in general: we need to give some guidance of what to check when a workload is not admitted

**Comment by tenzen-y** [comment]
> And in general: we need to give some guidance of what to check when a workload is not admitted

agree.

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

cc @moficodes

**Comment by alculquicondor** [comment]
/close

I implemented most of this in #2185 and #1889
