### ISSUE TITLE
Hybrid mode in a single cluster: services + batch

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#635]
**What would you like to be added**:

The ability to account for quota usage coming from service pods (Deployment, Daemonset, Statefulset, etc).

**Why is this needed**:

In on-prem clusters or cloud clusters with reservations, organizations want to schedule jobs on the valleys of usage by services.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kannon92** [comment]
So currently we assume that queuing is only valid for finite jobs but is there a consideration that we would want Kueue to work for services also?

ie have other apps objects have a suspend field?

I know that yunikorn/MCAD allow for queuing/scheduling of services in addition to batch workloads

**Comment by alculquicondor** [comment]
Not necessarily queuing, but accounting for their usage.

The use case is hybrid clusters where you are running most services during the day, and there are valleys at night that can be used by jobs.

This is useful in fixed size clusters. But on the cloud, you could just have 2 separate clusters (one for services and one for jobs) and have autoscaling in both.
