### ISSUE TITLE
Graduate ComponentConfig API version to beta

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#639]
**What would you like to be added**:
I would like to graduate the `config.kueue.x-k8s.io` to `v1beta1`.

**Why is this needed**:
Currently, we use v1beta1 API for `kueue.x-k8s.io` (e.g., clusterQueue), and the API is production ready.
So it is better to graduate also `config.kueue.x-k8s.io` to beta API so that we declare the whole of Kueue is production ready. 

Maybe, there is no need to make any breaking changes to the `config.kueue.x-k8s.io`, unlike when we migrated `kueue.x-k8s.io` from v1alpha2 to v1beta1.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
cc: @kerthcet @alculquicondor

**Comment by kerthcet** [comment]
I think the config version has no strong correlation with the api version, but graduate to beta to mark it not in experiment seems necessary before we release v0.3?

**Comment by tenzen-y** [comment]
> I think the config version has no strong correlation with the api version,

I guess it's ok just to change the API version to v1beta1.

> graduate to beta to mark it not in experiment seems necessary

Yes, it is worth it.

> before we release v0.3?

I think it is better before we release v0.3.

**Comment by alculquicondor** [comment]
We haven't had any changes, so it should be good to graduate.

**Comment by tenzen-y** [comment]
Let me tackle this issue.

/assign
