### ISSUE TITLE
Add user guide

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#64]
/kind feature
/size M

Something more comprehensive that the existing README. Some of the use cases in bit.ly/kueue-apis can be dumped into samples/guides.

If possible, generate some documentation out of the APIs, similar to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/

Contents (not necessarily each one will be a page, but they could be sections on existing pages).
- [x] Single CQ setup
- [x] Multiple flavors
- [x] Multiple CQ setup (cohorts)
- [x] Namespace selectors
- [ ] Cohorts
- [x] Running a Job
- [ ] Configuring RBAC
- [ ] Monitoring usage (kubectl describe)

**Comment by ArangoGutierrez** [comment]
Could we use github pages? or just a folder with markdown is ok for now? 
GitHub pages is easy to manage using prow automation

**Comment by alculquicondor** [comment]
We can probably start with markdown and move it to github pages when there is some useful content :)

**Comment by alculquicondor** [comment]
I just added in the description a list of things I would like to cover. Anything else?

**Comment by ArangoGutierrez** [comment]
for a v0.0.1 , we are ok i Think

**Comment by ahg-g** [comment]
one more thing to add to CQ concept is queueing strategy
