### ISSUE TITLE
[Question] why we only consider workload's request when judging whether Flavor.Min is satisfied

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes-sigs/kueue#642]
we consider val instead of used+val when judging whether Flavor.Min is satisfied

https://github.com/kubernetes-sigs/kueue/blob/main/pkg/scheduler/flavorassigner/flavorassigner.go#L435
```
	if val <= flavor.Min {
		// The request can be satisfied by the min quota, assuming quota is
		// reclaimed from the cohort or assuming all active workloads in the
		// ClusterQueue are preempted.
		mode = Preempt
	}
```

**Comment by alculquicondor** [comment]
This doesn't mean that the workload fits right away. It just means that it might fit if we preempt (remove) all the workloads that are currently running. That's why `used` doesn't matter.

/close
