### ISSUE TITLE
Support kubeflow's MPIJob

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#65]
That is kubeflow's mpi-operator. We could have started with other custom jobs, but this one seems important enough for our audience.

They currently don't have a suspend field, so we need to add it. Then, we program the controller based on the existing kueue job-controller.

/label feature
/size L
/priority important-longterm

**Comment by zvonkok** [comment]
Just out of curiosity how many ranks are you going to test? Are you also looking into different distributions frameworks besides Horovod?

**Comment by denkensk** [comment]
> Just out of curiosity how many ranks are you going to test? 
Any suggestions? I think our first step is to choose a small number of ranks (for example 3 ) to ensure that the whole process is feasible.

> Are you also looking into different distributions frameworks besides Horovod?

I think Kueue is agnostic about the framework. Whether it is Horovrd or pytorch, as long as it can be launched by MPI through mpi-operator, it is fine.

**Comment by zvonkok** [comment]
@ArangoGutierrez Help me out, what was the critical amount of ranks aka nodes where we have seen bad scaling for the MPI operator?

**Comment by alculquicondor** [comment]
Sorry, we are not planning to implement an MPIJob. We are planning to support queuing for the existing kubeflow mpi-operator https://github.com/kubeflow/mpi-operator/tree/master/v2

I think your questions fit better in that repository.

**Comment by alculquicondor** [comment]
Work on mpi-operator will initiate soon https://github.com/kubeflow/mpi-operator/issues/504

The kueue size of things is currently blocked on #369

**Comment by mimowo** [comment]
Starting the work under https://github.com/kubernetes-sigs/kueue/pull/578.

IIUC the work isn't strictly blocked on https://github.com/kubernetes-sigs/kueue/issues/369. Moreover, the working initial implementation of the MPI integration may help us to better abstract out the interfaces, which could happen as a follow up. Adding the interfaces prior to the MPI integration also makes sense, but we then may need to adapt them, but this may anyway happen with future framework integrations, so maybe there is no point block over another, but just try to align in the process.

**Comment by tenzen-y** [comment]
> Starting the work under #578.
> 
> IIUC the work isn't strictly blocked on #369. Moreover, the working initial implementation of the MPI integration may help us to better abstract out the interfaces, which could happen as a follow up. Adding the interfaces prior to the MPI integration also makes sense, but we then may need to adapt them, but this may anyway happen with future framework integrations, so maybe there is no point block over another, but just try to align in the process.

I'm ok with either using the job interface or not since releasing v0.3 isn't blocked by this feature.
cc: @kerthcet @alculquicondor

**Comment by kerthcet** [comment]
Either, just hope to avoid repetitive work.

**Comment by alculquicondor** [comment]
I think @kerthcet and @mimowo can make progress in parallel. Please stay in touch.
