### ISSUE TITLE
Restrict scaling out MPIJob

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#658]
**What would you like to be added**:
I would like to restrict scaling out MPIJob in admission webhooks when clusterQueue lacks resources.

**Why is this needed**:
MPIJob supports scaling out workers by updating replicas.
Currently, if we scale out MPIJob that uses under-resourced clusterQueue, kueue sets suspend=true to MPIJob, and then the mpi-operator kills all MPIJob replicas.

However, I don't think that users want to kill all MPI replicas in that case.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
We discussed this before in the context of Job #467

I think it makes sense to just restrict this via webhooks while we don't have the support.

@mwielgus do you think this is still not worth since we will eventually remove this piece of code?

**Comment by tenzen-y** [comment]
> We discussed this before in the context of Job #467
> 
> I think it makes sense to just restrict this via webhooks while we don't have the support.
> 
> @mwielgus do you think this is still not worth since we will eventually remove this piece of code?

It's reasonable. For the first step, we can introduce webhooks for both batch/job and mpijob.

**Comment by tenzen-y** [comment]
I think this still could be possible although we can close this once https://github.com/kubernetes-sigs/kueue/issues/77 is realized.


/remove-lifecycle stale

**Comment by tenzen-y** [comment]
This would be resolved by https://github.com/kubernetes-sigs/kueue/issues/77.
Considering the current effort for #77, we can close this issue for now.
/close
