### ISSUE TITLE
Introduce possibility to disable protection on /metrics endpoint

### ISSUE THREAD

**Issue by mikouaj** [kubernetes-sigs/kueue#663]
**What would you like to be added**:

Make it possible to disable protection on `/metrics` endpoint via configuration.

**Why is this needed**:

This is needed for Google Cloud Managed Service for Prometheus managed data collection.
As for now, GMP scraping does not support authentication on metrics endpoints. Thus, it is not possible to use GMP managed data collection on kueue metrics.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
Do we, I think we didn't enable the authentication I think.

**Comment by kerthcet** [comment]
Any feedbacks? @mikouaj
