### ISSUE TITLE
Support for RayJob

### ISSUE THREAD

**Issue by mwielgus** [kubernetes-sigs/kueue#666]
**What would you like to be added**:

Kueue support for RayJob - https://ray-project.github.io/kuberay/guidance/rayjob/

**Why is this needed**:

Ray is one of the most popular AI/ML frameworks out there and with RayJob it fits nicely into Kueue model.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
ref https://github.com/ray-project/kuberay/pull/926
It looks like it's almost ready to merge

**Comment by trasc** [comment]
> ref [ray-project/kuberay#926](https://github.com/ray-project/kuberay/pull/926) It looks like it's almost ready to merge

I'll rebase and rework #667 as soon as it is.
