### ISSUE TITLE
Example needed for borrowing limit

### ISSUE THREAD

**Issue by moficodes** [kubernetes-sigs/kueue#672]
**What would you like to be added**:

An example of borrowing limit being used.

**Why is this needed**:

There is a bit of confusion about what borrowing limit actually do in a cohort. A concrete example of borrowing limit being used in a cohort and show what the numbers look like with the limit in place would help clarify this topic.

**Completion requirements**:

A yaml example added in this section. https://kueue.sigs.k8s.io/docs/concepts/cluster_queue/#borrowinglimit

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by KunWuLuan** [comment]
@moficodes hi, I have added a sample in site and config/samples. It will be appreciated if you have time to review the sample and give me your suggestions. Thanks

**Comment by KunWuLuan** [comment]
@moficodes Hi, I think this issue can be closed cause pr #709 has been merged

**Comment by alculquicondor** [comment]
yes, thanks!

/close
