### ISSUE TITLE
Flaky test:  Scheduler when Queueing with StrictFIFO Should schedule workloads by their priority strictly

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#678]
**What happened**:

Flaky integration test: `Scheduler when Queueing with StrictFIFO Should schedule workloads by their priority strictly`

```
{Timed out after 30.000s.
Expected
    <int>: 2
to equal
    <int>: 1 failed [FAILED] Timed out after 30.000s.
Expected
    <int>: 2
to equal
    <int>: 1
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/scheduler/scheduler_test.go:894 @ 04/05/23 17:36:19.251
}
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/667/pull-kueue-test-integration-main/1643666314289483776

**Comment by tenzen-y** [comment]
I talked with @mcariatm. And I agreed @mcariatm will work on this issue.

/unassign

**Comment by tenzen-y** [comment]
I'm investigating.

**Comment by alculquicondor** [comment]
I have a theory:
It's a `WorkloadReconciler.Reconcile` routine that runs super slow and still has old information about the world (or maybe the API call takes too long to reach the apiserver). This call sets Admitted=false via SSA, possibly overriding the admission by scheduler in a different routine.

I think the fix is just to add the `resourceVersion` into the SSA patch when setting `Admitted=false`. Although this is almost the same as doing a regular Update. This should be fine as Workload reconciliation is best effort and doesn't need to be performant.

**Comment by tenzen-y** [comment]
Umm. It's a distributed system :(
It sounds reasonable.
