### ISSUE TITLE
Add integration tests for core controllers independent of the scheduler

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#68]
Just to focus on the event handlers and status updates.
Keeping them independent of the scheduler should allow us to not depend on a specific queuing policy.
The test itself can do the assignments.

/kind cleanup

**Comment by ahg-g** [comment]
I assume this is done as a high-level issue to create integration test suites for each controller. If we want more tests, we should have specific issues describing what is missing to test.
