### ISSUE TITLE
Update Kueue installation version to 0.3.0

### ISSUE THREAD

**Issue by moficodes** [kubernetes-sigs/kueue#686]
**What would you like to be added**:

Change version to 0.3.0 in installation instruction.

**Why is this needed**:

Match the latest version of Kueue

**Completion requirements**:

Update all mention of v0.2.1 to v0.3.0

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
This is already covered by #687

**Comment by alculquicondor** [comment]
I meant #685
