### ISSUE TITLE
Set up milestone automatically for new PRs

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#690]
**What would you like to be added**:

Set the milestone v0.4 automatically for PRs in the main branch and v0.3 for the release-0.3 branch.

**Why is this needed**:

Having a milestone has two purposes:
- historical record: being able to tell when a PR was introduced.
- (potentially): block a PR from merging unless it has a milestone, to implement code-freezes later on.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
Rough instructions https://kubernetes.slack.com/archives/C1TU9EB9S/p1679586290890489

**Comment by alculquicondor** [comment]
@ArangoGutierrez it looks like something is missing. New PRs aren't getting the tag automatically

**Comment by ArangoGutierrez** [comment]
I enabled the PROW side, I guess more is needed on this. let me check what's left, I'll be back here

**Comment by alculquicondor** [comment]
It seems to be adding a milestone correctly for the `release-0.3` branch, but not `main`.
