### ISSUE TITLE
MVP Multi-cluster support

### ISSUE THREAD

**Issue by mwielgus** [kubernetes-sigs/kueue#693]
**What would you like to be added**:

Define and implement multi-cluster story for Kueue.

**Why is this needed**:

Many customers are asking how to configure and run Kueue with multiple batch clusters.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@trasc Which PRs do we need to merge by v0.6?

@alculquicondor @mimowo Did you discuss which MultiKueue features we should include in the v0.6?

**Comment by alculquicondor** [comment]
I would just focus on #1643 at this point.

**Comment by tenzen-y** [comment]
I'm ok with only #1643.

**Comment by mimowo** [comment]
AFIAK there is nothing pending, so we can close.
