### ISSUE TITLE
Add info to ClusterQueue status

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#7]
Suggestions:
- [x] admitted workloads
- [x] pending workloads
- [x] Capacity allocated
- [x] Capacity borrowed

/kind feature

**Comment by ahg-g** [comment]
Should we add pending workloads to capacity as well?

**Comment by alculquicondor** [comment]
Aggregating the sizes of all the queues pointing to it? We should be able to implement that efficiently, but could it be confusing?

**Comment by ahg-g** [comment]
Why would it be confusing? The pending workloads at a queue level isn't really that useful i would say for an admin to look at compared to an aggregated view at the capacity level

**Comment by alculquicondor** [comment]
/reopen

Sounds good. Although I will tackle this after https://github.com/kubernetes-sigs/kueue/pull/80#issuecomment-1057113242

**Comment by ArangoGutierrez** [comment]
I strongly disagree with 

>The pending workloads at a queue level isn't really that useful 

For users, is the most important after deploying, if queues are going to be a user managed object, we need to provide as much valuable information to them at the namespace lvl.

As an admin all I care is big numbers and usage. I think we are looking at this with an admin/cloud provider point of view and not from the end user. 

we need to think as a cascade here 

CQ -> Q -> QW

**Comment by ArangoGutierrez** [comment]
`pending workloads at a queue level` are one of THE most important reasons why people want to have a queuing mechanism in kubernetes.

**Comment by ahg-g** [comment]
sg, I already proposed a way to track the number of admitted workloads at Q level

**Comment by ahg-g** [comment]
oh, you are referring to the count of pending workloads; I guess I agree in general the the more info we can surface the better

**Comment by xieydd** [comment]
I agree with the  comment from @ArangoGutierrez . 
Considering the cascade of CQ, Q and QW, we need the more info we can of workload , we can aggregate some info for Q and CQ.

**Comment by ahg-g** [comment]
sg, then with regards to this issue we need two things in CQ status:

- [ ] Rename AssignedWorkloads to AdmittedWorkloads
- [ ] Pending workloads

/help
/unassign @alculquicondor

**Comment by ArangoGutierrez** [comment]
> sg, then with regards to this issue we need two things in CQ status:
> 
> * [ ]  Rename AssignedWorkloads to AdmittedWorkloads
> * [ ]  Pending workloads
> 
> /help /unassign @alculquicondor

Check first one #110

**Comment by ArangoGutierrez** [comment]
For `Pending workloads` do we still want to track that on kueue.clusterqueue.Status? 
as it is right now, a workload has to be admitted into a clusterqueue, so to the eyes of clusterqueue it is never pending, pending feels better at the kueue.queue lvl, tracking workloads that have not yet been admitted, right? 
if yes we can close this issue as done, and focus on #5 only

**Comment by alculquicondor** [comment]
Pending workloads are the workloads that are still in the heap, so they haven't been admitted.

Yes, we should add that field to clusterQueue.status
