### ISSUE TITLE
Make the GPU a prime citizen in kueue

### ISSUE THREAD

**Issue by zvonkok** [kubernetes-sigs/kueue#70]
Hello fellow HPC and batch enthusiasts, I have read your public doc with much interest and I have seen that the GPU is mentioned a couple of times. To make kueue and GPUs a success story I think we need to align the requirements that kueue needs for scheduling with our k8s stack which should expose the right information that you need to make the right scheduling decisions. 

There are dedicated GPUs, MIG slices, vGPU either time shared or MIG backed, those are all features that need to be taken into consideration. Going further if we're doing multi-node with MPI and such, we need to think also about network topologies and node interconnects. You may rather use nodes that have GPUDirect enabled than nodes that have "only" a GPU with a slow ethernet connection. 

I am one of the tech-leads for accelerator enablement on Kubernetes at NVIDIA and I am happy to help to move this forward.

**Comment by denkensk** [comment]
Thanks. We are glad that you are interested in this project.  I'm also doing some work on managing and scheduling accelerator (like GPU/MIG/vGPU/NPU) in Kubernetes. These are very import in Batch System. I'm looking forward to working together in the future to move Kueue forward.

> Going further if we're doing multi-node with MPI and such, we need to think also about network topologies and node interconnects.

Kueue is currently not node-aware. I'm not sure it's possible to do some things like topologies and node interconnects. This feels more like the work to do in the scheduler. Can you share more details of your idea? Thanks

**Comment by alculquicondor** [comment]
Correct, this discussion fits more in kube-scheduler and kubelet.

The perfect venue to discuss these ideas is the wg-batch https://github.com/kubernetes/community/tree/master/wg-batch

Hopefully we will set up a meeting today.

In the meantime, better open an issue in github.com/kubernetes/kubernetes

/close
