### ISSUE TITLE
[Flaky] ResourceFlavor controller when one clusterQueue references resourceFlavors Should delete the resourceFlavor when the corresponding clusterQueue no longer uses the resourceFlavor

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#704]
**What happened**:

Flaky test:

```
ResourceFlavor controller when one clusterQueue references resourceFlavors Should delete the resourceFlavor when the corresponding clusterQueue no longer uses the resourceFlavor
```

```
{Timed out after 30.001s.
Expected success, but got an error:
    <*errors.StatusError | 0xc00062ca00>: 
    resourceflavors.kueue.x-k8s.io "flavor" not found
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "resourceflavors.kueue.x-k8s.io \"flavor\" not found",
            Reason: "NotFound",
            Details: {
                Name: "flavor",
                Group: "kueue.x-k8s.io",
                Kind: "resourceflavors",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    } failed [FAILED] Timed out after 30.001s.
Expected success, but got an error:
    <*errors.StatusError | 0xc00062ca00>: 
    resourceflavors.kueue.x-k8s.io "flavor" not found
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "resourceflavors.kueue.x-k8s.io \"flavor\" not found",
            Reason: "NotFound",
            Details: {
                Name: "flavor",
                Group: "kueue.x-k8s.io",
                Kind: "resourceflavors",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/controller/core/resourceflavor_controller_test.go:85 @ 04/17/23 19:11:13.438
}
```

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/703/pull-kueue-test-integration-main/1648040056281108480

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
We discussed this offline.
We only saw this fail once and we can't reproduce. It also doesn't show in the periodic testgrid https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-integration-main&width=20

/close

**Comment by mcariatm** [comment]
/reopen
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/742/pull-kueue-test-integration-main/1654022279161450496

**Comment by mcariatm** [comment]
@alculquicondor please reopen this isssue

**Comment by mcariatm** [comment]
Is not the same issue. I think the old one's gone. Now we received:
Message: "Operation cannot be fulfilled on clusterqueues.kueue.x-k8s.io \"foo\": the object has been modified; please apply your changes to the latest version and try again",
Code: 409

**Comment by tenzen-y** [comment]
> Is not the same issue. I think the old one's gone. Now we received: Message: "Operation cannot be fulfilled on clusterqueues.kueue.x-k8s.io "foo": the object has been modified; please apply your changes to the latest version and try again", Code: 409

@macaptain Can you share the full error log, like the description of this issue?

**Comment by mcariatm** [comment]
> > Is not the same issue. I think the old one's gone. Now we received: Message: "Operation cannot be fulfilled on clusterqueues.kueue.x-k8s.io "foo": the object has been modified; please apply your changes to the latest version and try again", Code: 409
> 
> @mcariatm Can you share the full error log, like the description of this issue?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/742/pull-kueue-test-integration-main/1654022279161450496

I fixed it here :
https://github.com/kubernetes-sigs/kueue/pull/748
