### ISSUE TITLE
Ensure test cases are independent

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#72]
In an effort to get a binary that "works", we wrote some tests where a test case depends on the state left by previous test cases.

This is problematic for debugging problems and it tends to lead to a lot of test changes when there is a behavior change or you want to insert a case in the middle of the existing ones.

Places that I'm aware of:

- [ ] TestCacheCapacityOperations in https://github.com/kubernetes-sigs/kueue/blob/main/pkg/capacity/capacity_test.go
- [ ] TestCacheWorkloadOperations in https://github.com/kubernetes-sigs/kueue/blob/main/pkg/capacity/capacity_test.go
- [ ] Scheduler suite https://github.com/kubernetes-sigs/kueue/blob/main/test/integration/scheduler/scheduler_test.go

And there are similar situations in the following, but it's more like a single complex test case in each:
- [ ] TestSnapshot in https://github.com/kubernetes-sigs/kueue/blob/main/pkg/capacity/snapshot_test.go
- [ ] TestFIFOQueue in https://github.com/kubernetes-sigs/kueue/blob/main/pkg/queue/queue_test.go

/priority backlog

**Comment by shuheiktgw** [comment]
Let me work on this issue!
/assign

**Comment by shuheiktgw** [comment]
Seems like TestCacheCapacityOperations does not exist anyomre?

**Comment by shuheiktgw** [comment]
Looks like the issue with TestCacheCapacityOperations (TestCacheClusterQueueOperations) was already resolved in https://github.com/kubernetes-sigs/kueue/pull/133 🙂

**Comment by shuheiktgw** [comment]
I found the problem with the scheduler integration tests was resolved in https://github.com/kubernetes-sigs/kueue/pull/90
