### ISSUE TITLE
Error in run the `sample-job.yaml` in Readme

### ISSUE THREAD

**Issue by yankay** [kubernetes-sigs/kueue#724]
**What happened**:

Error in run the `sample-job.yaml` in Readme at https://github.com/kubernetes-sigs/kueue/blame/main/README.md#L51

```
[root@kay171 ~]# kubectl apply -f sample-job.yaml
error: from sample-job-: cannot use generate name with apply
```

**What you expected to happen**:

It can be run successful

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
The documentation is accurate, but maybe we should clarify that `apply` wouldn't work?
