### ISSUE TITLE
Replace component-config with our implemntation

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#725]
**What would you like to be added**:
We should migrate the component-config to another logic.

**Why is this needed**:
The controller-runtime community announces that the component-config (https://github.com/kubernetes-sigs/controller-runtime/tree/dca0be70fd22d5200f37d986ec83450a80295e59/pkg/config) is deprecated and will be removed in the future.

Ref:
- https://github.com/kubernetes-sigs/controller-runtime/pull/2149
- https://github.com/kubernetes-sigs/controller-runtime/issues/895

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@alculquicondor We need to work on this before bumping k8s module to v1.27 because controller-runtime v.0.15 doesn't populate parameters to `ctrl.Option`, and many lint errors have occurred.

ref: https://github.com/kubernetes-sigs/kueue/pull/880

If we put ` component-config` in the kueue repository, do we need to upgrade componentConfig's apiVersion to v1beta2?

**Comment by alculquicondor** [comment]
No, we only need to bump the version if we need to remove fields from the schema (in the CustomResourceDefinition itself)

**Comment by tenzen-y** [comment]
> No, we only need to bump the version if we need to remove fields from the schema (in the CustomResourceDefinition itself)

I see. Thanks!

**Comment by tenzen-y** [comment]
> /assign

Thanks for taking this!
