### ISSUE TITLE
Support JobSet in Kueue

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#738]
**What would you like to be added**:

The ability to control JobSet startup through Kueue.

**Why is this needed**:

To support a wide variety of workloads

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
The first release of jobset came up https://github.com/kubernetes-sigs/jobset/releases/tag/v0.1.0

**Comment by kannon92** [comment]
I helped write the suspend code in Jobset so feel free to tag if you find issues.

**Comment by mcariatm** [comment]
For initially unsuspend, setting NodeAffinity foreach  ReplicatedJob Template should be enough.
But if the jobs are already created the node selectors should be updated on each of them.
I propose to do that in jobset_contolled in resumeJobSetIfNecessary function on Jobset Operator.

**Comment by tenzen-y** [comment]
@mcariatm is working on this at the jobset side.

https://github.com/kubernetes-sigs/jobset/issues/134

**Comment by tenzen-y** [comment]
So it will take a bit of time.

**Comment by mcariatm** [comment]
Yes, I'm still working on it. On both sides kueue and jobset. I think tomorrow I will put all changes for kueue. Working on tests now.
