### ISSUE TITLE
Document: Manage number of pods in ClusterQueues 

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#741]
**What would you like to be cleaned**:

Document the semantics when managing number of pods in a ClusterQueue quota.

It should go in https://kueue.sigs.k8s.io/docs/concepts/cluster_queue/

Since this is a new feature for a version that wasn't released, we shouldn't merge the documentation into the main branch, otherwise it will immediately go live. You can open PRs against the `website-release-0.4` branch.

**Why is this needed**:

**Comment by trasc** [comment]
@alculquicondor I think we should manually close, #743 is closed.

**Comment by tenzen-y** [comment]
@trasc Thanks!
/close
