### ISSUE TITLE
[DOC] add helm chart support to installation

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#753]
We can install kueue via helm chart https://github.com/kubernetes-sigs/kueue/pull/664 now.
/kind documentation
cc @Gekko0114

**Comment by alculquicondor** [comment]
/reopen

We are still missing the documentation for the website.
Although we might have to wait until we have the release?

**Comment by Gekko0114** [comment]
After releasing, we might need to change README.md again.
Also we have to check whether charts are released correctly

**Comment by alculquicondor** [comment]
We included a helm chart in the release.
Let's document how to install from there in the website.

Any volunteers?

**Comment by kerthcet** [comment]
Seems we didn't upload our helm charts to artifact hub, do we have any plan?

**Comment by alculquicondor** [comment]
We only included the chart in the release https://github.com/kubernetes-sigs/kueue/releases/tag/v0.4.0

Other than that, we should look into uploading the chart to registry.k8s.io. I think it might just work if we follow the same process as for images https://github.com/kubernetes/k8s.io/tree/main/registry.k8s.io

**Comment by alculquicondor** [comment]
Opened #990 for that
