### ISSUE TITLE
The suspend=true added to the job by the default job webhook has not taken effect.

### ISSUE THREAD

**Issue by fjding** [kubernetes-sigs/kueue#757]
**What happened**:
When I create a job that contains one pod, occasionally the following situation will occur. Two pods will be created at the same time. The status of one pod is Terminating, and the status of the other pod is Pending. I think the Terminating pod should not be created
![image](https://github.com/kubernetes-sigs/kueue/assets/21192363/a97bdc58-798d-4d3f-a777-307a93f0a8d1)
**What you expected to happen**:
I think the suspend=true added to the job by the default job webhook has not taken effect.
![image](https://github.com/kubernetes-sigs/kueue/assets/21192363/19d58291-7391-4f17-b9b7-e10707cda99c)

The address of the job object is different from the address of &Job{*job}. I added a test case for testing, and it is true, so the suspend=true added here will not take effect.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kannon92** [comment]
Seems like there are two things going on:

1) suspend field is not set for webhook.

2) https://github.com/kubernetes/enhancements/issues/3939 - Is a KEP to fix the terminating/pending issue

**Comment by alculquicondor** [comment]
Would either of you mind sending a fix for 1?

This needs to be backported.

**Comment by tenzen-y** [comment]
@alculquicondor I think this bug is critical. Should we create a patch release?

**Comment by alculquicondor** [comment]
I think so. Let's get the PR merged and cherry-picked.
