### ISSUE TITLE
Document how to integrate a custom Job with Kueue

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#777]
We have successfully integrated Kueue with MPIJob and we are in the process of integrating JobSet and RayJob.
It would be useful to document what needs to be done in user docs.

cc @trasc @mcariatm @kerthcet

**Comment by tenzen-y** [comment]
As a next step, creating a separate controller to integrate frameworks would be good.

**Comment by kerthcet** [comment]
I think this is still valid, so /assign @BinL233
