### ISSUE TITLE
Dynamically reclaiming resources

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#78]
Currently a job's resources are reclaimed by Kueue only when the whole job finishes; for jobs with multiple pods, this entails waiting until the last pod finishes. This is not efficient as the pods of a parallel job may have laggards consuming little resources compared to the overall job.

One solution is to continuously update the Workload object with the number of completed pods so that Kueue can gradually reclaim the resources of those pods.

**Comment by thisisprasad** [comment]
@ahg-g I think we should add a new field in the status of workload, to track the count of completed pods.
What do you think?

Is there a way to get all pods belonging to a workload?

**Comment by alculquicondor** [comment]
This is not something that kueue core controllers should do. It's specific to the kind of workload. In the case of Job, it should be done in `pkg/controller/workload/job`. And this controller doesn't need to look at Pods, just at the Job status.

> I think we should add a new field in the status of workload, to track the count of completed pods.

Yes, we need that, but I would rather see a more complete design before adding the API fields. We can probably do this for the 0.3.0 release.

**Comment by alculquicondor** [comment]
If you are willing to write a design, please feel free to take this issue.

**Comment by thisisprasad** [comment]
@alculquicondor thanks for the information!

**Comment by thisisprasad** [comment]
I would like to work on this task.
/assign

**Comment by thisisprasad** [comment]
API field changes design here:
```
// WorkloadStatus defines the observed state of Workload
type WorkloadStatus struct {
	// conditions hold the latest available observations of the Workload
	// current state.
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []WorkloadCondition `json:"conditions,omitempty"`

	// The number of pods which reached phase Succeeded or Failed.
	// +optional
	CompletedPods int32 `json:"completedPods"`
}
```

**Comment by thisisprasad** [comment]
High-level flow:
1. The completed pods in a job is sum of Succeeded+failed pods => sum(succeeded, failed)
2. We update the workload status object if job.sum(succeded, failed) > wl.CompletedPods
3. Handle the update event of workload in its reconciler.
4. Update clusterqueue quota for resource flavor for requests of pod workload in cache.

Currently I don't see any scenario where `CompletedPods`  field will used in the reconciliation routine of workload.

**Comment by thisisprasad** [comment]
Please validate the above approach.

**Comment by alculquicondor** [comment]
Why would failed pods matter? The job controller would create a replacement pod, which should be taking quota.

Not sure if a github issue is the best avenue to provide feedback on a design. Could you start a google doc? Alternatively, we could start an enhancements folder where we can add design proposals with a format similar to https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md

**Comment by thisisprasad** [comment]
Will start with enhancements folder and add design proposal.

**Comment by alculquicondor** [comment]
/reopen

@thisisprasad is currently working on the proposal

**Comment by kerthcet** [comment]
reopen for tracking.
/reopen

**Comment by alculquicondor** [comment]
/unassign @thisisprasad 
/assign @mwielgus

Thanks for the progress so far @thisisprasad

**Comment by alculquicondor** [comment]
@kerthcet
