### ISSUE TITLE
[dep] Use a released version of Ray operator

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#781]
**What would you like to be cleaned**:
A released version of `github.com/ray-project/kuberay/ray-operator` should be used instead of `v0.0.0-20230516192117-9bc5d854bd31` once https://github.com/ray-project/kuberay/commit/9bc5d854bd316c46a79920bbd7b2887fb0c6d0af is part of one, probably v0.6.0.

**Why is this needed**:

**Comment by alculquicondor** [comment]
was there a release?
