### ISSUE TITLE
[RayJob] Add support for partial admission.

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#783]
**What would you like to be added**:

Add support for partial admission for RayJobs. Check #420 and https://github.com/kubernetes-sigs/kueue/pull/667/files#r1198519116 for detail.

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
FYI, we don't need a new KEP, but you can add the details to the existing one.

**Comment by kerthcet** [comment]
Hi all, what's left here, our team is interested with the integration with rayJob ?

**Comment by tenzen-y** [comment]
IIRC, we don't support partial admission on RayJob, now.
So, we need to implement `minPodsCount` and then modify functions for RayJob  based on `minPodCount` like this:

https://github.com/kubernetes-sigs/kueue/blob/f215a43a7be9b3c2788e00ec03c130b8fbc053b5/pkg/controller/jobs/job/job_controller.go#L279-L286

https://github.com/kubernetes-sigs/kueue/blob/f215a43a7be9b3c2788e00ec03c130b8fbc053b5/pkg/controller/jobs/job/job_controller.go#L199-L208

**Comment by alculquicondor** [comment]
@kerthcet can you share how heterogeneous your Ray jobs are?

I wonder if we can simplify support for partial admission by restricting it to one podset. Otherwise it's an NP problem.

**Comment by kerthcet** [comment]
We're still exploring this, but we found the rayCluster's autoscaling is complex, and maybe that's out of the scope of kueue but related to cluster-autoscaler. It's recommended by the ray community as 1 pod(raynode) : 1 node. 

Some phenomenons like when we don't have enough resources for autoscaling, the rayjob will hang forever, although part of its tasks finished, the resources will not be reclaimed. Then I think kueue can do little here ..

**Comment by alculquicondor** [comment]
cc @astefanutti @vicentefb @andrewsykim in case you have interest on this.

Partial admission is different from elastic in that, during admission, Kueue decides to give a smaller size to the RayJob and the job runs like this until it completes.
