### ISSUE TITLE
Support for hierarchical ClusterQueues

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#79]
Systems like Yarn allow creating a hierarchy of fair sharing, which allows modeling deeper organizational structures with fair-sharing. 

Kueue currently supports three organizational levels: Cohort (models a business unit), ClusterQueue (models divisions within a business unit), namespace (models teams within a division). However fair-sharing is only supported at one level, within a cohort.

We opted-out of supporting hierarchy from the beginning for two reasons: (1) it adds complexity to both the API and implementation; (2) it is also not clear that in practice customers need more than two levels of sharing which is what the current model enables and seems to work for other frameworks like Slurm and HTCondor.

As Kueue evolves we likely need to revisit this decision.

**Comment by gabesaba** [comment]
/close

Hierarchical Cohorts will be available as part of the 0.9 release.
