### ISSUE TITLE
Failed to run sleep image in arm64 machine

### ISSUE THREAD

**Issue by hwdef** [kubernetes-sigs/kueue#790]
**What happened**:

I created sample-job for test, but it returns an error, I think `gcr.io/k8s-staging-perf-tests/sleep:v0.0.3` image does not support arm64 platform

<img width="434" alt="image" src="https://github.com/kubernetes-sigs/kueue/assets/13084946/d721996b-6c87-4148-9880-584c670cbc24">

**What you expected to happen**:

Successfully run the test job

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl create -f config/samples/sample-job.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
@hwdef Thank you for creating this report!

Yes, the image doesn't support arm64.
However, the image isn't maintained by this repository.

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1756,
      "digest": "sha256:99c52edc38d9087e4af9cc6f2093209835b82d2ab6b95edb4210e366d3f4d08f"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 803833,
         "digest": "sha256:2df365faf0e3007f983fadd7a65ba51d41b488eb2ed8fc70f4bf97043cfea560"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1124619,
         "digest": "sha256:87f257c18949b274e781d7c05d3977426633cfd0f0d7f7dbdf32ddacae5675b1"
      }
   ]
}
```

https://console.cloud.google.com/gcr/images/k8s-staging-perf-tests/global/sleep@sha256:00ae8e01dd4439edfb7eb9f1960ac28eba16e952956320cce7f2ac08e3446e6b/details?tab=pull

@kerthcet @alculquicondor @ahg-g @denkensk Do you know where this image is maintained?

**Comment by kerthcet** [comment]
You can refer to https://github.com/kubernetes/perf-tests/blob/master/util-images/sleep/Dockerfile

**Comment by kerthcet** [comment]
Feel free to close this.
/remove-kind bug
/kind support

**Comment by hwdef** [comment]
I think the solution is to upload an arm64 version of the image to this image registry. I don’t know who has this permission

**Comment by hwdef** [comment]
> @hwdef Can you create an issue at https://github.com/kubernetes/perf-tests/issues, as this repo doesn't maintain that image?

sure
