### ISSUE TITLE
support match expressions in resource flavor

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes-sigs/kueue#809]
**What would you like to be added**:
support match expressions in resource flavor

**Why is this needed**:
maybe some high priority job don't want to run on spot nodes, now we have to add all 
nodes except for spot nodes to the one or multiple resource flavors, which is difficult 
if we have a large cluster

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by KunWuLuan** [comment]
/assign 
This will involve API changes, scheduling logic changes, and test case changes. If necessary, I will submit a KEP for discussion.

**Comment by tenzen-y** [comment]
> support match expressions in resource flavor

Do you assume to add a new member to the following?

https://github.com/kubernetes-sigs/kueue/blob/64434d0ca4c9ecca24494e779d4dc63523ff1496/apis/kueue/v1beta1/resourceflavor_types.go#L36C40-L37

**Comment by KunWuLuan** [comment]
@tenzen-y yes, we can either add a property of v1.matchexpression type in ResourceFlavorSpec or change map[string]string to v1.labelSelector type

**Comment by tenzen-y** [comment]
> change map[string]string to v1.labelSelector type

I think we can not add changes without backward compatibility to API since our API version is beta.

So, as you say, I think we can `add a property of v1.matchexpression type in ResourceFlavorSpec` .

However, I'm not sure the reason why we should support v1.matchExpressions in resourceFlavor since I think we should add Toleration to Node and create resourceFlavor with Taints in your case.

**Comment by tenzen-y** [comment]
Also, users can directly add nodeAffinity batch/job. So the workload will be scheduled to Node matched nodeSelector injected by kueue and nodeAffinity specified by users.

**Comment by tenzen-y** [comment]
cc: @kerthcet

**Comment by alculquicondor** [comment]
Are `nodeTaints` in the ResourceFlavor not enough to express this semantics?
