### ISSUE TITLE
Samples folder is hard to find and not a common place to look for examples.

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#812]
**What would you like to be cleaned**:

We should move config/samples/* to a top level directory.  I'm unclear if we have code/docs that reference this so I want this as a separate issue from where it was brought up.  

**Why is this needed**:

https://github.com/kubernetes-sigs/kueue/pull/778#discussion_r1195871208

As this project matures I think we should start putting example integrations in an examples directory so people can glance quickly and see how to use other workloads.

**Comment by alculquicondor** [comment]
+1

**Comment by alculquicondor** [comment]
We can update the links where needed, but I don't think the docs link to them. They have their own inline examples.
