### ISSUE TITLE
Add workload priority

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#82]
This is a placeholder to discuss priority semantics.

We can have it at the workload level or queue level.

**Comment by ArangoGutierrez** [comment]
Agree, queues should re-shuffle to reflect job priority 
maybe "weight" is a better descriptor, as done in HPC (Slurm, HTCondor) 
```
Weight:
from 1 to 100
1 being very important
100 being opportunistic compute run
```
(or we can do 100 important and 1 not, as we like)

**Comment by ahg-g** [comment]
Given that we converged on the concept of ClusterQueue being the practical place where queueing is actually happening, then I think it is safe to say that priority should be at the workload level (not a priority of the namedspaced queue for example as it was proposed in the initial proposal).

I think we could rely on k8s priority classes and semantics. If the user doesn't wish for priority to have an impact on kube-scheduler preemption, they can create the class with `preemptionPolicy: Never`.

/assign

**Comment by denkensk** [comment]
I will take it because Priority is also related to the ClusterQueue QueueingStrategy.
/assign
/remove help
