### ISSUE TITLE
[JobSet] Support partial admission

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#820]
**What would you like to be added**:

Support for partial admission in JobSet https://github.com/kubernetes-sigs/kueue/tree/main/keps/420-partial-admission

The open questions are:
- How to support resizing of multiple PodSets? Maximizing the size of one podset might imply reducing the size of another. Even if we have some priority to maximize the size of specific podsets, the problem is generally NP, so we might need to reduce the search space, or just limit the support to one PodSet.
- What to do if a Job is replicated? In this case, there are multiple options for sizing. But perhaps a replicated Job always has full size.

**Why is this needed**:

To be able to admit jobs of smaller size if this is acceptable to the application.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
@ahg-g @mwielgus for comment

**Comment by mwielgus** [comment]
I would opt for trying to keep things as simple as possible until we hear a strong push from the users. I'm worried that with couple of such features stacked together (say partial admission with resource-flavor-ordered preemption), it will be extremely hard to predict what should/would exactly happen. So maybe let's start with a single-dimension partial admission for one podset/replicatedjob and wait for user feedback?

**Comment by ahg-g** [comment]
I agree with @mwielgus, so I guess we validate that only one PodSet sets MinCount?

**Comment by alculquicondor** [comment]
Yes, that would be my preference.

**Comment by trasc** [comment]
@alculquicondor @mwielgus @ahg-g  #1001  describes what I believe we'll need in order to support this. 

Since the actual pod-set count for a jobset is `parallelism * replicas`  we can only decrement one of them, I think `replicas` should be the one changed.
