### ISSUE TITLE
Missing rbac role for RayJob

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#825]
**What happened**:

Job and MPIJob have roles in https://github.com/kubernetes-sigs/kueue/blob/main/config/components/rbac,
RayJobs don't have one

**What you expected to happen**:

RayJob should have roles

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

IIRC, these roles were manually created. Perhaps as output from kubebuilder, but they are not recreated with codegen.
Please double check.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment]
@alculquicondor , they look to be created manually. I, personally,  don't find the added value of having them to be significant. The important part, in my opinion, is to have the manager able to work with the job types which is done by kubebuilder. 

If we insist to have them, I could do it for rayJobs as well.

(also a more clean approach wold be to have `mpijob_editor_role.yaml` defined as an aggregate on `rbac.authorization.kubeflow.org/aggregate-to-kubeflow-mpijobs-admin: "true"`)

**Comment by alculquicondor** [comment]
we do aggregate user roles using labels https://github.com/kubernetes-sigs/kueue/blob/6e3852c9c5eec15d3454f6b37c54d952e989248f/config/components/rbac/job_editor_role.yaml#L6-L8

**Comment by trasc** [comment]
> we do aggregate user roles using labels
> 
> https://github.com/kubernetes-sigs/kueue/blob/6e3852c9c5eec15d3454f6b37c54d952e989248f/config/components/rbac/job_editor_role.yaml#L6-L8

What I meant to say was that in something like `mpijob_editor_role.yaml` intead of writing Kinds and verbes, write an aggregator rule that selects the "official" (defined in kubeflow) mpijob-editor role.

**Comment by alculquicondor** [comment]
Ah, I see what you mean.

yeah, I would be ok dropping the individual roles from the frameworks that provide them and add the selector to the aggregated role.
