### ISSUE TITLE
Rename Capacity to ClusterQueue

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#85]
Capacity not only defines usage limits for a set of tenants, but it is the level at which ordering will be done for workloads submitted to queues sharing a capacity.

Renaming Capacity to ClusterQueue could provide clarify, with Queue being the namespaced equivalent serving two purposes:

1. discoverability: tenants can simply list the queues that exist in their namespace to find which ones they can submit their workloads to, so it is simply a pointer to the cluster-scoped ClusterQueue.
2. address the use case where a tenant is running an experiment and want to define usage limits for that experiment; in this use case an experiment is modeled as a queue; which means tenants should be able to create/delete queues as they see fit.

**Comment by denkensk** [comment]
1. Are we thinking of creating a default Queue after the ClusterQueue created?  It may be difficult because we don't know the namespace, maybe in default? 

2. We need a more precise and detailed description so that users can distinguish between Queue and ClusterQueue when they first try to use Kueue.

**Comment by alculquicondor** [comment]
1. I don't think we should
2. For the most part, end users should only care about Queue. But yes, we need to make it clear in the documentation for admins to understand the difference.

+1 on renaming.

FYI @ArangoGutierrez for extra input.

**Comment by ArangoGutierrez** [comment]
In HPC/Academia this is known as "Partitions" (see: https://slurm.schedmd.com/scontrol.html#lbAN) 

+1 renaming, just not to `ClusterQueue`

**Comment by ahg-g** [comment]
But Partition is just limited to Slurm, I wouldn't say it is a common term.

What is the concern to ClusterQueue?

**Comment by ArangoGutierrez** [comment]
I am thinking that this will look similar to RBAC role/ClusterRole implementation, and by doing so, I like the idea.

**Comment by ahg-g** [comment]
yeah, we also have ResourceQuota and ClusterResourceQuota (from openshift)

**Comment by ArangoGutierrez** [comment]
but that got me thinking, should they look similar? or at least share some fields in the API, similar to role/ClusterRole and the likes

**Comment by ArangoGutierrez** [comment]
right now capacity and queue have a master-worker relation
- E.g like a ServiceAccount get's added to a Role

But planning the name be `ClusterQueue` , is based on the ClusterScoped/Namespaced point of view, so we should address that as well. 

- E.g you can not assign a Role to a ClusterRole

**Comment by alculquicondor** [comment]
> but that got me thinking, should they look similar?

I think they will look more similar when we implement Queue limits and budgets. However, maybe we wouldn't have all the flavor options, just total resources.

**Comment by ArangoGutierrez** [comment]
not to derail the conversation but, `QueuedWorkloads` could be just `Workloads` that you assign to a Q (TODO conversation)

**Comment by ahg-g** [comment]
We discussed this before and are planning to change it; I didn't do it yet because Workload is quite an overloaded term. QW is still easy to understand what we are referring to and replace in the code once we decide on a proper name. Any suggestions?

**Comment by alculquicondor** [comment]
If we rename to `ClusterQueue`, does it still make sense for a QW to be "assigned to a ClusterQueue"? Maybe the `QueuedWorkloadSpec` field could be renamed to `AssignedByClusterQueue`?

It makes a lot of sense for the field to be a boolean to signal whether the QW is "assigned", but we need to keep the name of the ClusterQ in case the Queue is deleted.

**Comment by alculquicondor** [comment]
Here is my proposal:
1. Rename `Capacity` to `ClusterQueue`
2. Introduce a field `assignment` in `QueuedWorkload`

```go
type QueuedWorkloadSpec struct {
  assignment *Assignment
}

type Assignment struct {
  ClusterQueue string
  PodFlavors []PodFlavor
}

type PodFlavor struct {
  Name string
  ResourceFlavors map[corev1.ResourceName]string
}
```

**Comment by ahg-g** [comment]
sounds good to me, I like the grouping of assignment into one place.

**Comment by ArangoGutierrez** [comment]
if a queue is to a namespace, what a job is to a QW, why do we want to store the CQ in the WQ? 
I think we should be OK, with assuming that if a Q is deleted, it's WQ will be gone as well, no? as how jobs in a NS get deleted when the NS is deleted

**Comment by alculquicondor** [comment]
/assign
People can still comment while I'm on it, but I think I rather address this and #87 as part of the same effort.

**Comment by alculquicondor** [comment]
> I think we should be OK, with assuming that if a Q is deleted, it's WQ will be gone as well, no? as how jobs in a NS get deleted when the NS is deleted

Yes, I think they should be "gone" (more accurately, they are not considered in scheduling). But "assigned" workloads should continue running and being accounted for the CQ.

**Comment by ArangoGutierrez** [comment]
oh running ones, sure, agree 
+1

**Comment by alculquicondor** [comment]
actually, should we rename `assignment`/`assigned` by `admission`/`admited`?

**Comment by ArangoGutierrez** [comment]
I have no complains about it
