### ISSUE TITLE
Brainstorm enhancing UX 

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#86]
We are adding more information to statuses of the various APIs we have (https://github.com/kubernetes-sigs/kueue/issues/7 and https://github.com/kubernetes-sigs/kueue/issues/5); but I am wondering what other UX-related enhancements we should pursue for the two personas: batch admin and batch user.

UX gets users excited about the system and I think should be a focal point as Kueue evolves.

**Comment by ArangoGutierrez** [comment]
- [ ] Prometheus integration for resource consumption of QueuedWorkloads / Queues

**Comment by ahg-g** [comment]
A kubectl plugin will be quite useful here for both admins and users.

**Comment by alculquicondor** [comment]
I think we should update the QueuedWorkloadAdmitted condition to True in a best-effort basis.

This means that we don't need to do it in the scheduling cycle. But we can do it in the controller (we will get an event for the addition of the .spec.admission field).

**Comment by ahg-g** [comment]
Created https://github.com/kubernetes-sigs/kueue/issues/201 and https://github.com/kubernetes-sigs/kueue/issues/199 to track updating the workload condition and adding metrics. Closing this one.
