### ISSUE TITLE
Chart misses settings for securitycontext

### ISSUE THREAD

**Issue by bh-tt** [kubernetes-sigs/kueue#874]
**What would you like to be added**:
The chart has a fixed securityContext for the manager, which only sets allowPrivilegeEscalation to false. There are several more hardening settings to apply, like running as a specific user and enforcing a readOnlyRootFilesystem.
**Why is this needed**:
It is best practice to harden pods as much as possible, especially when it comes to controllers
**Completion requirements**:
Support a `.controllerManager.manager.podSecurityContext` and `.controllerManager.manager.securityContext` field whose value is simply inserted into the pod spec. The default can stay the same as now but will be defined in the chart values instead of the template. This allows compatibility with any future additions as well.

**Comment by alculquicondor** [comment]
Thanks, feel free to assign it to yourself and send a PR

**Comment by bh-tt** [comment]
See #878
