### ISSUE TITLE
Add nodeSelectors when ClusterQueue has quota for Pods

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#891]
**What would you like to be added**:

If a ClusterQueue defines quota for pods, and the ResourceFlavor has nodeLabels, the nodeSelectors should be applied to the Job.

**Why is this needed**:

It is already surprising that we don't add nodeSelectors if a Job doesn't define requests. But this is semantically correct, because flavors are ssociated to specific resources.

But if the ClusterQueue is managing quota for pods explicitly, then we should apply the nodeSelectors because the Pod itself is a resource.

**Completion requirements**:

Add an integration test for this.

And documentation.

**Comment by trasc** [comment]
#895 adds some tests (e2e and integration) to check this, it works as expected.

The bigger problem in my opinion is 
> It is already surprising that we don't add nodeSelectors if a Job doesn't define requests. But this is semantically correct, because flavors are ssociated to specific resources.

case in which, for me is more logical to have  kueue admit the workload in the first available flavor and propagate the node selectors instead of letting the job "run wild" in the cluster.

**Comment by alculquicondor** [comment]
Yes, but flavors are associated to resource requests. We don't have any flavors to assign if the Job doesn't require any requests.

Hence why we added support for pod quota.

**Comment by alculquicondor** [comment]
But where should we deduce the flavors from?

**Comment by trasc** [comment]
Just get the first one  (for start).

**Comment by alculquicondor** [comment]
I'm not a fan of such an implicit behavior. Users should be setting pod quota if they really don't care about requests.

**Comment by trasc** [comment]
The problem in this scenario is the the lack of configuration by `A` can have runtime side effects for `B`.
