### ISSUE TITLE
hardcoded string for leaderElection resourceName

### ISSUE THREAD

**Issue by rptaylor** [kubernetes-sigs/kueue#893]
The YAML and chart appear to have a hardcoded string:
```
    leaderElection:
      leaderElect: true
      resourceName: c1f6bfd2.kueue.x-k8s.io
```
My supposition which could be completely wrong, is that this is for scaling the controller-manager deployment to > 1 replicas, so that the members can elect a leader among themselves? If the resourceName is used as a shared key for the election, there could be a security implication where a malicious user knowing the key could create imposter pods which hijack the controller-manager cluster, possibly rendering it non-functional.  Maybe the use of TLS certs among the members mitigates this so it would only be applicable if neither external certManager nor the internal certManagement are used. What is also unclear to me is how multiple members would be aware of each other and accept connections from each other, which would determine whether this is possible in a deployment of default size 1.  
Anyway that is a lot of suppositions, I am just looking for clarification on the nature of this hard-coded string, perhaps to add documentation so users can be aware of the implications and potential need to secure their deployment by overwriting the default value.

**Comment by alculquicondor** [comment]
This string was autogenerated by kubebuilder.
It is perfectly feasible to make it configurable via helm variables.

Note that the leader election object is namespaced. As long as the namespace where kueue is running is properly secured via RBAC, this shouldn't be much of a problem.

The TLS certs are for protecting the endpoints, such as metrics.

As for how an high-availability deployment of Kueue works, the pods don't need to be aware of each other. Only one pod is the leader and is the only one processing requests. The rest of the pods are there to take over if the first pod dies.

**Comment by rptaylor** [comment]
Oh okay, that sounds more like a sort of public ID then rather than a shared secret key.
I found some info about it [here](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1#ControllerManagerConfigurationSpec)

```
$ kubectl -n kueue-system get leases.coordination.k8s.io 
NAME                      HOLDER                                                                           AGE
c1f6bfd2.kueue.x-k8s.io   kueue-controller-manager-86bc4fd75d-6gkpn_534c590c-430a-49af-a018-9b15e68c5e73   21h
```
