### ISSUE TITLE
Add events that tracks a workload's status

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#9]
Two possible locations to issue events:
- when it is assigned a capacity in the scheduling loop.
- in the job-controller when a corresponding workload is created.

/kind feature

**Comment by denkensk** [comment]
I think we can start by providing the assigned event. 
Scheduling Failed is easy to add after we have a backoff policy. Step by step.

**Comment by denkensk** [comment]
> in the job-controller when a corresponding workload is created.

 Is the created event patched to `job`, right? @ahg-g

**Comment by denkensk** [comment]
1. when it is assigned a capacity in the scheduling loop #26 
2. in the job-controller when a corresponding workload is created. #36
