### ISSUE TITLE
Create an event and update workload status when failing to schedule a workload

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#91]
Probably for the workloads that wasn't returned in this loop: https://github.com/kubernetes-sigs/kueue/blob/9912f26234f40a9b43f48b5f2cf3abfde15c55bf/pkg/scheduler/scheduler.go#L142

**Comment by alculquicondor** [comment]
Let's block this on #87

**Comment by alculquicondor** [comment]
Actually, it shouldn't conflict much.

Related: #102

**Comment by uroy-personal** [comment]
Hi @ahg-g,

I am interested on working on this issue if it is not being worked upon at the moment.  Please let me know if I can assign this issue to myself.
Thanks,
Have a nice Day..

**Comment by ahg-g** [comment]
@ArangoGutierrez for this one, I guess we could simply create an event in the same place where you are updating the conditions, right?

**Comment by ahg-g** [comment]
@ArangoGutierrez I assume you will be working on this, correct?
