### ISSUE TITLE
Flaky E2E test: when Creating a Job With Queueing Should unsuspend a job and set nodeSelectors

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#911]
**What happened**:

Flaky test https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/903/pull-kueue-test-e2e-main-1-24/1673404497516302336

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24
- Kueue version (use `git describe --tags --dirty --always`): main
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alculquicondor** [comment]
cc @tenzen-y

**Comment by tenzen-y** [comment]
We need to check which verification failed. `workload.IsAdmitted(createdWorkload)` vs `apimeta.IsStatusConditionTrue(createdWorkload.Status.Conditions, kueue.WorkloadFinished)`.

**Comment by alculquicondor** [comment]
kueue logs:
```
{"level":"Level(-2)","ts":"2023-06-26T19:00:31.304074482Z","logger":"scheduler","caller":"scheduler/scheduler.go:400","msg":"Workload successfully admitted and assigned flavors","workload":{"name":"job-test-job-11501","namespace":"e2e-rh7w4"},"clusterQueue":{"name":"cluster-queue"},"assignments":[{"name":"main","flavors":{"cpu":"on-demand","memory":"on-demand"},"resourceUsage":{"cpu":"1","memory":"20Mi"},"count":1}]}
```

k8s job controller logs:

```
I0626 19:01:13.242968       1 event.go:294] "Event occurred" object="e2e-rh7w4/test-job" fieldPath="" kind="Job" apiVersion="batch/v1" type="Normal" reason="Completed" message="Job completed"
```

That's more than 30s later. I think the test just timed out.

**Comment by tenzen-y** [comment]
> kueue logs:
> 
> ```
> {"level":"Level(-2)","ts":"2023-06-26T19:00:31.304074482Z","logger":"scheduler","caller":"scheduler/scheduler.go:400","msg":"Workload successfully admitted and assigned flavors","workload":{"name":"job-test-job-11501","namespace":"e2e-rh7w4"},"clusterQueue":{"name":"cluster-queue"},"assignments":[{"name":"main","flavors":{"cpu":"on-demand","memory":"on-demand"},"resourceUsage":{"cpu":"1","memory":"20Mi"},"count":1}]}
> ```
> 
> k8s job controller logs:
> 
> ```
> I0626 19:01:13.242968       1 event.go:294] "Event occurred" object="e2e-rh7w4/test-job" fieldPath="" kind="Job" apiVersion="batch/v1" type="Normal" reason="Completed" message="Job completed"
> ```
> 
> That's more than 30s later. I think the test just timed out.

I see. Maybe the kube-apiserver's load is heavy.

**Comment by tenzen-y** [comment]
Ah, we didn't increase resource requests in https://github.com/kubernetes/test-infra/blob/1c382cce4cc1d6970d19294d13d9294cb999c9d6/config/jobs/kubernetes-sigs/kueue/kueue-presubmits-main.yaml#L162-L168 although we increase kind nodes from 1 to 3.

**Comment by tenzen-y** [comment]
Previously, we had only a control-plan. But we have 3 nodes, a control-plan, and two workers.

**Comment by alculquicondor** [comment]
Yes, I was going to say the same thing :)
Let's increase that
/assign @tenzen-y 
/unassign @trasc

**Comment by tenzen-y** [comment]
I created: https://github.com/kubernetes/test-infra/pull/29948
