### ISSUE TITLE
Make sure assumed workloads are deleted when the object is deleted

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#92]
Since the scheduler works on a snapshot, it's possible that a workload is deleted between the time we get it from a queue and when we assume it.

We should check the client cache before Assuming a workload to make sure it still exists.

Also, when a workload is deleted, we should clear the cache even if the workload API object is not assigned (regardless of DeleteStateUnknown). This is because the workload could be deleted between the time the scheduler Assumes a workload and it updates the assignment in the API.

/kind bug

**Comment by denkensk** [comment]
Is it still needed ?
