### ISSUE TITLE
Extend the unit-test coverage for jobframework,

### ISSUE THREAD

**Issue by trasc** [kubernetes-sigs/kueue#922]
**What would you like to be cleaned**:
Extend the unit-test coverage for jobframework,
ref: https://github.com/kubernetes-sigs/kueue/pull/762/files#r1245444318
**Why is this needed**:

**Comment by trasc** [comment]
> There are two alternatives:
> 
> * Create a FakeJob implementation to test the jobframework package itself.
> * Test each of the job packages (job, mpijob, jobset) using a fake client and the reconciler code.
> 
> I have a preference for the second.

going with the second one we will have a lot of duplicate tests.

**Comment by alculquicondor** [comment]
It's not really duplicate, as some jobs might behave differently and implement optional extensions.
