### ISSUE TITLE
E2E tests: Use kindest/node image from ecr

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#933]
**What would you like to be cleaned**:

The E2E test configurations use the kindest/node image. They should point to ecr.

Example:

https://github.com/kubernetes/test-infra/blob/0f79649617bb7d8035849a6e88b61a2dcb460ed8/config/jobs/kubernetes-sigs/kueue/kueue-presubmits-main.yaml#L78-L79

**Why is this needed**:

To avoid hitting the rate limit from dockerhub.

**Comment by liangyuanpeng** [comment]
> KIND v0.18.0 Comes with a big shoutout to [Docker, Inc.](https://www.docker.com/company/) for accepting us into the updated [Docker Sponsored OSS Program](https://www.docker.com/community/open-source/application/). Thanks Docker! 🎉
> Images should no longer have pull rate limits as a result.
> The project will still consider mirroring on or switching primarily to [registry.k8s.io](https://registry.k8s.io/) in the future, after determining an updated immutable tagging scheme to comply with requirements there.

The image of kind should no longer have pull rate limits as a result.

https://github.com/kubernetes-sigs/kind/releases/tag/v0.18.0

**Comment by alculquicondor** [comment]
Oh, so this hasn't been a problem for us for a while. Thank you @liangyuanpeng 

Still, worth upgrading kind.

**Comment by trasc** [comment]
#953 will change the kind version

The builder image used ware changed in kubernetes/test-infra#29960
