### ISSUE TITLE
Default support for MPI jobs causes a crashloop in the controller if the CRD is not installed

### ISSUE THREAD

**Issue by bh-tt** [kubernetes-sigs/kueue#946]
**What happened**:
After upgrading to the newest helm chart version, the controller ended up in a crashloop as we do have the MPI job installed but support for it is enabled by default.
**What you expected to happen**:
I expected the same configuration to continue working after an update, not a breaking change without even a Chart.yaml version increment. Using an actual helm repository instead of cloning this repository means the chart version can be incremented in a meaningful way.

I expect the chart to work by default on a standard kubeadm cluster without additional (except kueue's own) CRDs installed.

**How to reproduce it (as minimally and precisely as possible)**:
Install the controller on a cluster without MPIJob CRD installed. The crash only happens after approximately 2 minutes 20 seconds, which might mean the current unit tests do not catch it?

**Anything else we need to know?**:
Initially it logs some errors saying that for kind CRD they should be installed before the controller is started, after a while the controller crashes as it spends too long waiting for the MPI job cache to be initialized.

Commit 4599a19484070f0a239a66cc02b3fc3bccae68e0 introduces these changes to the chart and kustomize files.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27.3
- Kueue version (use `git describe --tags --dirty --always`): v0.3.2 controller, chart version 
- Cloud provider or hardware configuration: kubeadm 1.27.3
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools: helm
- Others:

**Comment by alculquicondor** [comment]
@stuton PTAL

**Comment by alculquicondor** [comment]
Oh I understand what is going on.

You are using a 0.3.2 controller with a chart from the main branch.

We haven't officially released helm charts yet, so you should treat the charts in the main branch as experimental and, in particular, no guaranteed to work with an older release of kueue.

We hope to have a 0.4 release of Kueue this week. We are also investigating how best to serve the helm charts given our infrastructure and the domain we have #745.
Feel free to leave some suggestions if you have any.

As it stands, this is not actionable for us.

/close

**Comment by Borrelhapje** [comment]
Thanks for the quick response, for now the problem is fixable by simply overriding the integrations.
