### ISSUE TITLE
Feature Request: Python Examples

### ISSUE THREAD

**Issue by vsoch** [kubernetes-sigs/kueue#947]
**What would you like to be added**:

A handle to interact with Kueue from Python.

**Why is this needed**:

Kueue is a nice interface for multi-tenancy running of jobs (and CRDs that implement them) but for extending it easily to workflow tools, we would ideally be able to programmatically control it one level up, meaning the workflow tool with a DAG would generate and submit jobs in a logical way on behalf of the user.

**Completion requirements**:

I would say completion requirements should include:

- [ ] An automated generation of the Python SDK (with tests)
- [ ] Basic examples for usage

This enhancement requires the following artifacts:

I'm not sure about the below - likely we don't need a design doc if we use an automated tool, nor do we need an API change. Docs would make sense!

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@vsoch Does that mean that you would like to manage ClusterQueue, LocalQueue, ResourceFlavor, and Workload by workflows?

**Comment by tenzen-y** [comment]
I'm not sure of use cases in which batch-users want to operate ClusterQueue, LocalQueue, ResourceFlavor, and Workload by workflows.

**Comment by vsoch** [comment]
Perhaps the need is even easier then - we just need examples of using the Kubernetes Python SDK to submit labeled jobs / MiniCluster, etc. that will be given to batch. Yes, I do think it would be nice to have a handle to the different queues / resource flavors (because this could be useful in the context of running workflows)  but it sounds like you do not agree.

**Comment by vsoch** [comment]
Yep I like that idea too - will get in some examples hopefully this week. Thanks to you both!
