### ISSUE TITLE
☂️ Requirements for v0.5

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#974]
```[tasklist]
### Accepted
- [ ] #970
- [ ] #922
- [ ] #972
- [ ] #973
- [ ] https://github.com/kubernetes-sigs/kueue/issues/297
- [ ] #168
- [ ] https://github.com/kubernetes-sigs/kueue/issues/976
- [ ] https://github.com/kubernetes-sigs/kueue/issues/582
- [ ] https://github.com/kubernetes-sigs/kueue/issues/993
```

**Comment by alculquicondor** [comment]
This is very much work-in-progress.

Ideally, we should aim for a release in mid September.

I also acknowledge that there are a few feature requests an open KEPs for more policies. I want to discuss with folks which of those policies are most important and can be implemented in a maintainable way. Alternatively, we could look into interfaces that would allow folks to implement their own policies.

cc @tenzen-y @Gekko0114 @KunWuLuan @vsoch @ahg-g for feedback

**Comment by tenzen-y** [comment]
@alculquicondor Thanks for creating this issue. I would like to add https://github.com/kubernetes-sigs/kueue/issues/297.

> I also acknowledge that there are a few feature requests an open KEPs for more policies. I want to discuss with folks which of those policies are most important and can be implemented in a maintainable way. Alternatively, we could look into interfaces that would allow folks to implement their own policies.

I agree. It would be nice to define interfaces for queueing and expose extensible points like the kube-scheduler scheduling framework.

**Comment by vsoch** [comment]
I was planning on starting the plugin soon, although I can't give a proper ETA until I dig in a bit. I will try to post an update on that soon.

**Comment by ahg-g** [comment]
A couple of features to consider:
1) https://github.com/kubernetes-sigs/kueue/issues/976
2) https://github.com/kubernetes-sigs/kueue/issues/975

**Comment by ahg-g** [comment]
I agree that #976 is the higher priority

**Comment by KunWuLuan** [comment]
#963 can be a candidate I think
#849 I will work on this, try to complete before August

**Comment by alculquicondor** [comment]
I'm currently hesitant about #963 unless we answer the question about arbitrary hierarchies.

I think we can add #849 as a non-blocking feature for the release.

**Comment by alculquicondor** [comment]
See updated list. I'm leaving out #963 for now, as we already have a lot in our plates.
I think we can consider it for release 0.6

**Comment by tenzen-y** [comment]
LGTM

**Comment by tenzen-y** [comment]
@alculquicondor What are the remaining tasks? I guess it's only https://github.com/kubernetes-sigs/kueue/issues/297?

**Comment by alculquicondor** [comment]
I'm hoping we can also get https://github.com/kubernetes-sigs/kueue/issues/1136, as proof that two-stage admission works. But there are some delays in the cluster-autoscaler side.

Which APIs are we missing in #297?

**Comment by tenzen-y** [comment]
> I'm hoping we can also get https://github.com/kubernetes-sigs/kueue/issues/1136, as proof that two-stage admission works. But there are some delays in the cluster-autoscaler side.

I see. I'm ok with including #1136 in this release. However, it might be better to cut a new release by KubeCon.

> Which APIs are we missing in https://github.com/kubernetes-sigs/kueue/issues/297?

All APIs had been done.

**Comment by alculquicondor** [comment]
I agree, kubecon is an important deadline. Let's take it out if it's not done by the end of this week.

**Comment by tenzen-y** [comment]
> I agree, kubecon is an important deadline. Let's take it out if it's not done by the end of this week.

SGTM

**Comment by alculquicondor** [comment]
The last 2 (documentation) could be merge afterwards.
But yes, the list is accurate.

**Comment by alculquicondor** [comment]
I think they can all merge by Monday.

**Comment by tenzen-y** [comment]
SGTM

**Comment by kerthcet** [comment]
cc @B1F030

**Comment by alculquicondor** [comment]
:rocket: 

/close
