### ISSUE TITLE
Managing raw pods 

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#976]
**What would you like to be added**:
Management of raw pods. 

kube-scheduler added support for a feature named scheduling gates, which allows an external controller to control when kube-scheduler should consider the pod for scheduling, so in a sense providing pod-level pause capability. This can be used by Kueue to manage raw pods.

**Why is this needed**:
Some workloads are better managed at the pod level, like Spark. This will also make it easier to support any job type without explicit integration.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
/assign

I want to take a stab at the design first.

**Comment by alculquicondor** [comment]
Also related to #77

**Comment by tenzen-y** [comment]
@alculquicondor @achernevskii Do we try to implement all features designed in KEP by release v0.5?

**Comment by alculquicondor** [comment]
No, we'll just go with single pod support in 0.5 and follow up on 0.6 with the rest.

**Comment by tenzen-y** [comment]
> No, we'll just go with single pod support in 0.5 and follow up on 0.6 with the rest.

SGTM
I was concerned that this feature blocks the v0.5 release.

**Comment by kerthcet** [comment]
I guess this is completed, right?

**Comment by tenzen-y** [comment]
> I guess this is completed, right?

This is not completed. The kueue doesn't support https://github.com/kubernetes-sigs/kueue/blob/main/keps/976-plain-pods/README.md#groups-of-pods-created-beforehand yet.

**Comment by kerthcet** [comment]
One potential issue here is pod is both watched by kueue and scheduler, and scheduler may complete the scheduling cycle in prior than kueue, then patching gates to pod will be failed.

**Comment by tenzen-y** [comment]
> One potential issue here is pod is both watched by kueue and scheduler, and scheduler may complete the scheduling cycle in prior than kueue, then patching gates to pod will be failed.

@kerthcet IIUC, there isn't such a potential issue since the webhook will work before the kube-scheduler will do anything to the pod, right?

https://github.com/kubernetes-sigs/kueue/blob/1579d75e5a35bdb4ab24c64b2da4e4effa98bbc8/pkg/controller/jobs/pod/pod_webhook.go#L186

**Comment by alculquicondor** [comment]
Keep in mind that it's not possible to add scheduling gates. They always have to be set on creation or in webhooks.

**Comment by kerthcet** [comment]
> there isn't such a potential issue since the webhook will work before the kube-scheduler will do anything to the pod

Yes, I found it, I'm in an environment with kubernetes 1.24 which doesn't support scheduling gates. sorry for that.

**Comment by alculquicondor** [comment]
/close

Splitting remaining use case into a different issue: https://github.com/kubernetes-sigs/kueue/issues/1656
