### ISSUE TITLE
Release helm chart through registry.kubernetes.io

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#990]
**What would you like to be added**:

Upload OCI versions of the charts to https://github.com/kubernetes/k8s.io/tree/main/registry.k8s.io

I don't know if this would work, as no other subproject has tried it, but it's worth a try.

**Why is this needed**:

It's a standard way of publishing charts.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
Another choice would be https://artifacthub.io/, I know descheduler also uploaded here.

**Comment by liangyuanpeng** [comment]
> Another choice would be https://artifacthub.io/, I know descheduler also uploaded here.

Artifacthub have not save anything, it just show something.

It can not be a helm oci registry.

**Comment by kerthcet** [comment]
Oh, I see.

**Comment by alculquicondor** [comment]
I'll try to create a page for kueue and see what are the requirements.

**Comment by alculquicondor** [comment]
I didn't have a chance to look at this. If anyone knows and can summarize what we need to do, please do.
