### ISSUE TITLE
Add labels to the Workload object matching the job details

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#992]
**What would you like to be added**:

The name of a Workload doesn't match the name of the Job, to avoid collisions among different CRDs.

As a result, it's hard to quickly obtain the Workload for a particular job. A pair of labels (for name and GVK) would make it feasible to query.

**Why is this needed**:

For general usability and also to efficiently implement a CLI that gives you all relevant information for a job #487 

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by trasc** [comment]
isn't the owner reference sufficient?
