### ISSUE TITLE
Introduce a plugin mechanism for arbitrary checks during workload admission.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes-sigs/kueue#993]
**What would you like to be added**:

A mechanism to admit workloads based on both ClusterQueue quota and checks made by an external controller. 

**Why is this needed**:

The current admission process only checks queue resources and doesn't allow to use some cloud provider API or prometheus database query.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
/reopen
Implementation is still ongoing

**Comment by alculquicondor** [comment]
/close

This was implemented in 0.5

**Comment by tenzen-y** [comment]
@alculquicondor IIRC, we're still working on #1178. Or, we should open a separate issue?

**Comment by alculquicondor** [comment]
Good point, opened #1677.
