### ISSUE TITLE
Hierarchical Quota 

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#998]
**What would you like to be added**:

Support for hierarchical quota.

**Why is this needed**:

Currently Kueue supports two levels of quota management which is sufficient for many users. However, some users have deeper organizations and require hierarchical quota.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
Is this the same as #79?
