### ISSUE TITLE
Integrate with cluster-autoscaler's ProvisioningRequest

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#999]
**What would you like to be added**:

Use #993 to integrate with the ProvisioningRequest API by cluster autoscaler https://github.com/kubernetes/autoscaler/pull/5848

**Why is this needed**:

This will allow atomic scale ups (depending on the provider implementation of cluster-autoscaler).

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@alculquicondor Is this still needed? I think this already done.
